#version 450
uniform vec3 _WorldSpaceCameraPos;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform float _FogStart;
uniform float _FogEnd;
uniform float _FogGlobalDensity;
uniform float _FogFallOff;
uniform float _FogHeight;
uniform float _FogStartDis;
uniform float _FogGradientDis;
layout(std140, binding = 1) uniform UnityPerDraw{
  vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
  vec4 hlslcc_mtx4x4unity_WorldToObject[4];
  vec4 unity_LODFade;
  vec4 unity_WorldTransformParams;
  vec4 unity_RenderingLayer;
  vec4 unity_LightData;
  vec4 unity_LightIndices[2];
  vec4 unity_ProbesOcclusion;
  vec4 unity_SpecCube0_HDR;
  vec4 unity_SpecCube1_HDR;
  vec4 unity_SpecCube0_BoxMax;
  vec4 unity_SpecCube0_BoxMin;
  vec4 unity_SpecCube0_ProbePosition;
  vec4 unity_SpecCube1_BoxMax;
  vec4 unity_SpecCube1_BoxMin;
  vec4 unity_SpecCube1_ProbePosition;
  vec4 unity_LightmapST;
  vec4 unity_DynamicLightmapST;
  vec4 unity_SHAr;
  vec4 unity_SHAg;
  vec4 unity_SHAb;
  vec4 unity_SHBr;
  vec4 unity_SHBg;
  vec4 unity_SHBb;
  vec4 unity_SHC;
  vec4 hlslcc_mtx4x4unity_MatrixPreviousM[4];
  vec4 hlslcc_mtx4x4unity_MatrixPreviousMI[4];
  vec4 unity_MotionVectorsParams;
};
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _MainTex_ST;
  vec4 _EmissionColor;
  vec4 _Color;
  vec4 _Fresnel_Color;
  vec4 _Fresnel_Color_Edge;
  vec4 _GPUSKin_TextureSize;
  vec4 _ShadowColor;
  float _VertexOffsetY;
  float _MainLightOn;
  float _MaxAddIntensity1;
  float _EmissionIntensity;
  float _Fresnel_Bisa;
  float _Fresnel_Scale;
  float _Fresnel_Intensity;
  float _CutOff;
  float _AlphaIsR;
  float _Intensity;
  float _NoMainTextureOn;
  float _HeroDayNight_ON;
  float _EMISSIONMAPON_BUILDING_ON;
  float _FadeY;
  float _AlphFadeY_ON;
  float _Fresnel_Scale_Edge;
  float _EMISSIONMAPON_ON;
  float _BlinnPhongOn;
  float _Fresnel_ON;
  float _SheetAnimationON;
  float _MainTexSheetAnimSpeed;
  vec4 _MainTexSheet;
};
in vec4 in_POSITION0;
in vec2 in_TEXCOORD0;
in vec3 in_NORMAL0;
out vec2 vs_TEXCOORD0;
out vec3 vs_TEXCOORD1;
out vec4 vs_TEXCOORD2;
out vec3 vs_TEXCOORD3;
out vec3 vs_TEXCOORD5;
out vec3 vs_TEXCOORD6;
vec3 u_xlat0;
vec4 u_xlat16_0;
vec4 u_xlat1;
vec3 u_xlat2;
vec3 u_xlat16_3;
vec3 u_xlat16_4;
float u_xlat5;
float u_xlat7;
float u_xlat15;
void main(){
  (u_xlat0.x = (in_POSITION0.y + _VertexOffsetY));
  (u_xlat0.xyz = (u_xlat0.xxx * hlslcc_mtx4x4unity_ObjectToWorld[1].xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[0].xyz * in_POSITION0.xxx) + u_xlat0.xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[2].xyz * in_POSITION0.zzz) + u_xlat0.xyz));
  (u_xlat0.xyz = (u_xlat0.xyz + hlslcc_mtx4x4unity_ObjectToWorld[3].xyz));
  (u_xlat1 = (u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx) + u_xlat1));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz) + u_xlat1));
  (gl_Position = (u_xlat1 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (vs_TEXCOORD0.xy = in_TEXCOORD0.xy);
  (u_xlat1.x = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[0].xyz));
  (u_xlat1.y = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[1].xyz));
  (u_xlat1.z = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[2].xyz));
  (u_xlat15 = dot(u_xlat1.xyz, u_xlat1.xyz));
  (u_xlat15 = max(u_xlat15, 0.0));
  (u_xlat15 = inversesqrt(u_xlat15));
  (u_xlat1.xyz = (vec3(u_xlat15) * u_xlat1.xyz));
  (vs_TEXCOORD1.xyz = u_xlat1.xyz);
  (u_xlat15 = (u_xlat0.y + (-_WorldSpaceCameraPos.y)));
  (u_xlat15 = (u_xlat15 + (-_FogHeight)));
  (u_xlat2.x = (_FogFallOff * 0.0099999998));
  (u_xlat15 = (u_xlat15 * u_xlat2.x));
  (u_xlat2.x = exp2((-u_xlat15)));
  (u_xlat7 = ((-u_xlat2.x) + 1.0));
  (u_xlat2.x = (u_xlat2.x * _FogGlobalDensity));
  (u_xlat15 = (u_xlat7 / u_xlat15));
  (u_xlat15 = (u_xlat2.x * u_xlat15));
  (u_xlat2.xyz = ((-u_xlat0.xyz) + _WorldSpaceCameraPos.xyz));
  (vs_TEXCOORD2.xyz = u_xlat0.xyz);
  (u_xlat0.x = dot(u_xlat2.xyz, u_xlat2.xyz));
  (u_xlat0.x = max(u_xlat0.x, 6.1035156e-05));
  (u_xlat0.x = sqrt(u_xlat0.x));
  (u_xlat0.x = (u_xlat0.x + (-_FogStartDis)));
  (u_xlat0.x = (u_xlat0.x / _FogGradientDis));
  (u_xlat0.x = max(u_xlat0.x, 0.0));
  (u_xlat0.x = ((u_xlat15 * u_xlat0.x) + (-_FogStart)));
  (u_xlat5 = ((-_FogStart) + _FogEnd));
  (u_xlat5 = (1.0 / u_xlat5));
  (u_xlat0.x = (u_xlat5 * u_xlat0.x));
  (u_xlat0.x = clamp(u_xlat0.x, 0.0, 1.0));
  (u_xlat5 = ((u_xlat0.x * -2.0) + 3.0));
  (u_xlat0.x = (u_xlat0.x * u_xlat0.x));
  (vs_TEXCOORD2.w = (u_xlat0.x * u_xlat5));
  (u_xlat16_3.x = (u_xlat1.y * u_xlat1.y));
  (u_xlat16_3.x = ((u_xlat1.x * u_xlat1.x) + (-u_xlat16_3.x)));
  (u_xlat16_0 = (u_xlat1.yzzx * u_xlat1.xyzz));
  (u_xlat16_4.x = dot(unity_SHBr, u_xlat16_0));
  (u_xlat16_4.y = dot(unity_SHBg, u_xlat16_0));
  (u_xlat16_4.z = dot(unity_SHBb, u_xlat16_0));
  (u_xlat16_3.xyz = ((unity_SHC.xyz * u_xlat16_3.xxx) + u_xlat16_4.xyz));
  (u_xlat1.w = 1.0);
  (u_xlat16_4.x = dot(unity_SHAr, u_xlat1));
  (u_xlat16_4.y = dot(unity_SHAg, u_xlat1));
  (u_xlat16_4.z = dot(unity_SHAb, u_xlat1));
  (u_xlat16_3.xyz = (u_xlat16_3.xyz + u_xlat16_4.xyz));
  (vs_TEXCOORD3.xyz = max(u_xlat16_3.xyz, vec3(0.0, 0.0, 0.0)));
  (vs_TEXCOORD5.xyz = vec3(0.0, 0.0, 0.0));
  (vs_TEXCOORD6.xyz = vec3(0.0, 0.0, 0.0));
  return ;
}
