#version 450
uniform vec4 _Time;
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _Remap_Tex_ST;
  vec4 _Turb_Tex_ST;
  vec4 _Diss_Tex_Mask_ST;
  vec4 _Mask_Tex_ST;
  vec4 _Diss_Tex_ST;
  vec4 _Main_Tex_ST;
  vec4 _Main_Tex_Color;
  vec4 _Diss_Tex_EdgeColor;
  vec2 _Diss_Tex_Mask_UV;
  vec2 _Diss_Tex_UV;
  vec2 _Turb_Tex_UV;
  vec2 _Mask_Tex_UV;
  vec2 _Main_Tex_UV;
  vec2 _Remap_UV;
  float _Diss_Tex_EdgeWidth;
  float _Main_Tex_Alpha;
  float _Turb_Mask_Value;
  float _Diss_Tex_Edge_NO;
  float _Main_Tex_A_NO_R;
  float _Mask_Tex_Rotator;
  float _Mask_Tex_A;
  float _Diss_Tex_Particle_ON;
  float _Turb_Diss_Value;
  float _Diss_Tex_Mask_value;
  float _Diss_Tex_Soft_value;
  float _Turb_Remap_Value;
  float _Main_Tex_Brightness;
  float _Main_Tex_Particle_Speed;
  float _Turb_MainTex_ON;
  float _Turb_Main_Value;
  float _Diss_Tex_value;
  float _Remap_A_NO_R;
};
layout(location = 0) uniform sampler2D _Main_Tex;
in vec4 vs_TEXCOORD1;
in vec4 vs_TEXCOORD2;
in vec4 vs_COLOR0;
layout(location = 0) out vec4 SV_Target0;
vec4 u_xlat0;
vec4 u_xlat16_0;
vec4 u_xlat16_1;
vec3 u_xlat16_3;
vec2 u_xlat4;
void main(){
  (u_xlat0.xy = ((vs_TEXCOORD1.xy * _Main_Tex_ST.xy) + _Main_Tex_ST.zw));
  (u_xlat4.xy = (u_xlat0.xy + vs_TEXCOORD2.xy));
  (u_xlat0.xy = ((_Time.yy * _Main_Tex_UV.xy) + u_xlat0.xy));
  (u_xlat4.xy = ((-u_xlat0.xy) + u_xlat4.xy));
  (u_xlat0.xy = ((vec2(vec2(_Main_Tex_Particle_Speed, _Main_Tex_Particle_Speed)) * u_xlat4.xy) + u_xlat0.xy));
  (u_xlat16_0 = texture(_Main_Tex, u_xlat0.xy));
  (u_xlat16_1.x = ((-u_xlat16_0.w) + u_xlat16_0.x));
  (u_xlat16_1.x = ((_Main_Tex_A_NO_R * u_xlat16_1.x) + u_xlat16_0.w));
  (u_xlat16_3.xyz = (u_xlat16_0.xyz * _Main_Tex_Color.xyz));
  (u_xlat16_1.yzw = (u_xlat16_3.xyz * vec3(_Main_Tex_Brightness)));
  (u_xlat16_1.x = (u_xlat16_1.x * _Main_Tex_Color.w));
  (u_xlat16_1.x = (u_xlat16_1.x * _Main_Tex_Alpha));
  (u_xlat0 = (u_xlat16_1.yzwx * vs_COLOR0));
  (SV_Target0 = u_xlat0);
  return ;
}
