#version 450
uniform vec4 _Time;
uniform vec3 _WorldSpaceCameraPos;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform int unity_BaseInstanceID;
uniform float _FogStart;
uniform float _FogEnd;
uniform float _FogGlobalDensity;
uniform float _FogFallOff;
uniform float _FogHeight;
uniform float _FogStartDis;
uniform float _FogGradientDis;
struct unity_Builtins0Array_Type {
  vec4 hlslcc_mtx4x4unity_ObjectToWorldArray[4];
  vec4 hlslcc_mtx4x4unity_WorldToObjectArray[4];
};
layout(std140, binding = 1) uniform UnityInstancing_PerDraw0{
  unity_Builtins0Array_Type unity_Builtins0Array[128];
};
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _MainTex_ST;
  vec4 _PositionOffset;
  vec4 _Color;
  float _Glossiness;
  float _Metallic;
  float _Speed;
  float _MaxDist;
  float _SpeedController;
  float _ClipSize;
  float _ScaleMultiplier;
};
struct PropsArray_Type {
  float _InstanceID;
  float _AsyncOffset;
  float _StartOffset;
};
layout(std140, binding = 2) uniform UnityInstancing_Props{
  PropsArray_Type PropsArray[128];
};
layout(location = 1) uniform sampler2D _PosTex;
in vec2 in_TEXCOORD0;
in vec2 in_TEXCOORD1;
out vec2 vs_TEXCOORD0;
out float vs_TEXCOORD2;
flat out uint vs_SV_InstanceID0;
vec4 u_xlat0;
vec4 u_xlat1;
float u_xlat2;
bool u_xlatb2;
float u_xlat4;
int u_xlati4;
float u_xlat6;
void main(){
  (u_xlat0.y = 0.0);
  (u_xlati4 = (gl_InstanceID + unity_BaseInstanceID));
  (u_xlat0.x = (123.34 * PropsArray[u_xlati4]._InstanceID));
  (u_xlat0.xy = fract(u_xlat0.xy));
  (u_xlat6 = (u_xlat0.x + 34.345001));
  (u_xlat0.xy = ((u_xlat0.xx * vec2(u_xlat6)) + u_xlat0.xy));
  (u_xlat0.x = (u_xlat0.y * u_xlat0.x));
  (u_xlat0.x = fract(u_xlat0.x));
  (u_xlat0.x = ((u_xlat0.x * 0.099999964) + 0.94999999));
  (u_xlat2 = (_Time.y * _Speed));
  (u_xlat0.x = ((u_xlat2 * _SpeedController) + u_xlat0.x));
  (u_xlat0.x = (u_xlat0.x + in_TEXCOORD1.y));
  (u_xlat0.x = (u_xlat0.x / _ClipSize));
  (u_xlatb2 = (u_xlat0.x >= (-u_xlat0.x)));
  (u_xlat0.x = fract(abs(u_xlat0.x)));
  (u_xlat0.x = ((u_xlatb2) ? (u_xlat0.x) : ((-u_xlat0.x))));
  (u_xlat0.x = ((u_xlat0.x * _ClipSize) + PropsArray[u_xlati4]._StartOffset));
  (u_xlat0.y = (u_xlat0.x + PropsArray[u_xlati4]._AsyncOffset));
  (u_xlati4 = int((u_xlati4 << 3)));
  (u_xlat0.x = in_TEXCOORD1.x);
  (u_xlat0.xyw = textureLod(_PosTex, u_xlat0.xy, 0.0).xyz);
  (u_xlat0.xyw = ((u_xlat0.xyw * vec3(2.0, 2.0, 2.0)) + vec3(-1.0, -1.0, -1.0)));
  (u_xlat0.xyw = (u_xlat0.xyw * vec3(vec3(_MaxDist, _MaxDist, _MaxDist))));
  (u_xlat1.xyz = (u_xlat0.yyy * unity_Builtins0Array[(u_xlati4 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[1].xyz));
  (u_xlat1.xyz = ((unity_Builtins0Array[(u_xlati4 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[0].xyz * u_xlat0.xxx) + u_xlat1.xyz));
  (u_xlat0.xyw = ((unity_Builtins0Array[(u_xlati4 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[2].xyz * u_xlat0.www) + u_xlat1.xyz));
  (u_xlat0.xyz = (u_xlat0.xyw + unity_Builtins0Array[(u_xlati4 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[3].xyz));
  (u_xlat1 = (u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx) + u_xlat1));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz) + u_xlat1));
  (gl_Position = (u_xlat1 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (u_xlat0.w = (u_xlat0.y + (-_WorldSpaceCameraPos.y)));
  (u_xlat0.xyz = ((-u_xlat0.xyz) + _WorldSpaceCameraPos.xyz));
  (u_xlat0.x = dot(u_xlat0.xyz, u_xlat0.xyz));
  (u_xlat0.x = max(u_xlat0.x, 6.1035156e-05));
  (u_xlat0.x = sqrt(u_xlat0.x));
  (u_xlat0.xy = (u_xlat0.xw + (-vec2(_FogStartDis, _FogHeight))));
  (u_xlat0.x = (u_xlat0.x / _FogGradientDis));
  (u_xlat0.x = max(u_xlat0.x, 0.0));
  (u_xlat4 = (_FogFallOff * 0.0099999998));
  (u_xlat2 = (u_xlat0.y * u_xlat4));
  (u_xlat4 = exp2((-u_xlat2)));
  (u_xlat6 = ((-u_xlat4) + 1.0));
  (u_xlat4 = (u_xlat4 * _FogGlobalDensity));
  (u_xlat2 = (u_xlat6 / u_xlat2));
  (u_xlat2 = (u_xlat4 * u_xlat2));
  (u_xlat0.x = ((u_xlat2 * u_xlat0.x) + (-_FogStart)));
  (u_xlat2 = ((-_FogStart) + _FogEnd));
  (u_xlat2 = (1.0 / u_xlat2));
  (u_xlat0.x = (u_xlat2 * u_xlat0.x));
  (u_xlat0.x = clamp(u_xlat0.x, 0.0, 1.0));
  (u_xlat2 = ((u_xlat0.x * -2.0) + 3.0));
  (u_xlat0.x = (u_xlat0.x * u_xlat0.x));
  (vs_TEXCOORD2 = (u_xlat0.x * u_xlat2));
  (vs_TEXCOORD0.xy = ((in_TEXCOORD0.xy * _MainTex_ST.xy) + _MainTex_ST.zw));
  (vs_SV_InstanceID0 = uint(gl_InstanceID));
  return ;
}
