#version 450
uniform vec3 _WorldSpaceCameraPos;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform int unity_BaseInstanceID;
uniform float _FogStart;
uniform float _FogEnd;
uniform float _FogGlobalDensity;
uniform float _FogFallOff;
uniform float _FogHeight;
uniform float _FogStartDis;
uniform float _FogGradientDis;
struct unity_Builtins0Array_Type {
  vec4 hlslcc_mtx4x4unity_ObjectToWorldArray[4];
  vec4 hlslcc_mtx4x4unity_WorldToObjectArray[4];
};
layout(std140, binding = 2) uniform UnityInstancing_PerDraw0{
  unity_Builtins0Array_Type unity_Builtins0Array[128];
};
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _MainTex_ST;
  vec4 _EmissionColor;
  vec4 _Color;
  vec4 _Fresnel_Color_Edge;
  vec4 _GPUSKin_TextureSize;
  vec4 _ShadowColor;
  float _VertexOffsetY;
  float _MainLightOn;
  float _MaxAddIntensity1;
  float _EmissionIntensity;
  float _CutOff;
  float _AlphaIsR;
  float _Intensity;
  float _NoMainTextureOn;
  float _HeroDayNight_ON;
  float _EMISSIONMAPON_BUILDING_ON;
  float _FadeY;
  float _AlphFadeY_ON;
};
struct GPUSkinArray_Type {
  vec4 _GPUSKin_ClipParams;
};
layout(std140, binding = 3) uniform UnityInstancing_GPUSkin{
  GPUSkinArray_Type GPUSkinArray[128];
};
layout(location = 1) uniform sampler2D _GPUSKin_Matrix;
in vec4 in_POSITION0;
in vec2 in_TEXCOORD0;
in vec3 in_NORMAL0;
in vec4 in_TEXCOORD3;
in vec4 in_TEXCOORD4;
out vec2 vs_TEXCOORD0;
out vec3 vs_TEXCOORD1;
out vec4 vs_TEXCOORD2;
flat out uint vs_SV_InstanceID0;
float u_xlat0;
int u_xlati0;
vec4 u_xlat1;
vec4 u_xlat2;
vec4 u_xlat3;
vec2 u_xlat16_3;
vec4 u_xlat4;
vec4 u_xlat5;
vec4 u_xlat6;
vec4 u_xlat7;
vec3 u_xlat8;
float u_xlat9;
float u_xlat16;
vec2 u_xlat17;
void main(){
  (u_xlati0 = (gl_InstanceID + unity_BaseInstanceID));
  (u_xlat8.x = ((GPUSkinArray[u_xlati0]._GPUSKin_ClipParams.y * _GPUSKin_TextureSize.z) + GPUSkinArray[u_xlati0]._GPUSKin_ClipParams.x));
  (u_xlati0 = int((u_xlati0 << 3)));
  (u_xlat8.x = trunc(u_xlat8.x));
  (u_xlat1 = ((in_TEXCOORD3.xxzz * vec4(3.0, 3.0, 3.0, 3.0)) + u_xlat8.xxxx));
  (u_xlat2 = ((in_TEXCOORD4.xxzz * vec4(3.0, 3.0, 3.0, 3.0)) + u_xlat8.xxxx));
  (u_xlat16_3.xy = (vec2(1.0, 1.0) / vec2(_GPUSKin_TextureSize.xy)));
  (u_xlat8.xy = (u_xlat1.yw * u_xlat16_3.xx));
  (u_xlat8.xy = floor(u_xlat8.xy));
  (u_xlat4.xy = (((-u_xlat8.xy) * _GPUSKin_TextureSize.xx) + u_xlat1.yw));
  (u_xlat1 = (u_xlat1 + vec4(1.0, 2.0, 1.0, 2.0)));
  (u_xlat8.xy = (u_xlat8.xy + vec2(0.5, 0.5)));
  (u_xlat5.zw = (u_xlat16_3.yy * u_xlat8.xy));
  (u_xlat8.xy = (u_xlat4.xy + vec2(0.5, 0.5)));
  (u_xlat5.xy = (u_xlat16_3.xx * u_xlat8.xy));
  (u_xlat4 = textureLod(_GPUSKin_Matrix, u_xlat5.yw, 0.0));
  (u_xlat5 = textureLod(_GPUSKin_Matrix, u_xlat5.xz, 0.0));
  (u_xlat5.x = dot(u_xlat5, in_POSITION0));
  (u_xlat4.x = dot(u_xlat4, in_POSITION0));
  (u_xlat6 = (u_xlat16_3.xxxx * u_xlat1));
  (u_xlat6 = floor(u_xlat6));
  (u_xlat1 = (((-u_xlat6) * _GPUSKin_TextureSize.xxxx) + u_xlat1));
  (u_xlat6 = (u_xlat6 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat6 = (u_xlat16_3.yyyy * u_xlat6));
  (u_xlat1 = (u_xlat1 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat1 = (u_xlat16_3.xxxx * u_xlat1.xzyw));
  (u_xlat7.xz = u_xlat1.yw);
  (u_xlat7.yw = u_xlat6.zw);
  (u_xlat1.yw = u_xlat6.xy);
  (u_xlat6 = textureLod(_GPUSKin_Matrix, u_xlat7.xy, 0.0));
  (u_xlat7 = textureLod(_GPUSKin_Matrix, u_xlat7.zw, 0.0));
  (u_xlat4.z = dot(u_xlat7, in_POSITION0));
  (u_xlat4.y = dot(u_xlat6, in_POSITION0));
  (u_xlat8.xyz = (u_xlat4.xyz * in_TEXCOORD3.www));
  (u_xlat4 = textureLod(_GPUSKin_Matrix, u_xlat1.xy, 0.0));
  (u_xlat1 = textureLod(_GPUSKin_Matrix, u_xlat1.zw, 0.0));
  (u_xlat5.z = dot(u_xlat1, in_POSITION0));
  (u_xlat5.y = dot(u_xlat4, in_POSITION0));
  (u_xlat8.xyz = ((u_xlat5.xyz * in_TEXCOORD3.yyy) + u_xlat8.xyz));
  (u_xlat1.xy = (u_xlat2.yw * u_xlat16_3.xx));
  (u_xlat1.xy = floor(u_xlat1.xy));
  (u_xlat17.xy = (((-u_xlat1.xy) * _GPUSKin_TextureSize.xx) + u_xlat2.yw));
  (u_xlat2 = (u_xlat2 + vec4(1.0, 2.0, 1.0, 2.0)));
  (u_xlat1.xy = (u_xlat1.xy + vec2(0.5, 0.5)));
  (u_xlat4.zw = (u_xlat16_3.yy * u_xlat1.xy));
  (u_xlat1.xy = (u_xlat17.xy + vec2(0.5, 0.5)));
  (u_xlat4.xy = (u_xlat16_3.xx * u_xlat1.xy));
  (u_xlat1 = textureLod(_GPUSKin_Matrix, u_xlat4.xz, 0.0));
  (u_xlat4 = textureLod(_GPUSKin_Matrix, u_xlat4.yw, 0.0));
  (u_xlat4.x = dot(u_xlat4, in_POSITION0));
  (u_xlat1.x = dot(u_xlat1, in_POSITION0));
  (u_xlat5 = (u_xlat16_3.xxxx * u_xlat2));
  (u_xlat5 = floor(u_xlat5));
  (u_xlat2 = (((-u_xlat5) * _GPUSKin_TextureSize.xxxx) + u_xlat2));
  (u_xlat5 = (u_xlat5 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat5 = (u_xlat16_3.yyyy * u_xlat5));
  (u_xlat2 = (u_xlat2 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat2 = (u_xlat16_3.xxxx * u_xlat2.zxwy));
  (u_xlat3.xz = u_xlat2.yw);
  (u_xlat3.yw = u_xlat5.xy);
  (u_xlat2.yw = u_xlat5.zw);
  (u_xlat5 = textureLod(_GPUSKin_Matrix, u_xlat3.xy, 0.0));
  (u_xlat3 = textureLod(_GPUSKin_Matrix, u_xlat3.zw, 0.0));
  (u_xlat1.z = dot(u_xlat3, in_POSITION0));
  (u_xlat1.y = dot(u_xlat5, in_POSITION0));
  (u_xlat8.xyz = ((u_xlat1.xyz * in_TEXCOORD4.yyy) + u_xlat8.xyz));
  (u_xlat1 = textureLod(_GPUSKin_Matrix, u_xlat2.xy, 0.0));
  (u_xlat2 = textureLod(_GPUSKin_Matrix, u_xlat2.zw, 0.0));
  (u_xlat4.z = dot(u_xlat2, in_POSITION0));
  (u_xlat4.y = dot(u_xlat1, in_POSITION0));
  (u_xlat8.xyz = ((u_xlat4.xyz * in_TEXCOORD4.www) + u_xlat8.xyz));
  (u_xlat16 = (u_xlat8.y + _VertexOffsetY));
  (u_xlat1.xyz = (vec3(u_xlat16) * unity_Builtins0Array[(u_xlati0 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[1].xyz));
  (u_xlat1.xyz = ((unity_Builtins0Array[(u_xlati0 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[0].xyz * u_xlat8.xxx) + u_xlat1.xyz));
  (u_xlat8.xyz = ((unity_Builtins0Array[(u_xlati0 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[2].xyz * u_xlat8.zzz) + u_xlat1.xyz));
  (u_xlat8.xyz = (u_xlat8.xyz + unity_Builtins0Array[(u_xlati0 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[3].xyz));
  (u_xlat1 = (u_xlat8.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat8.xxxx) + u_xlat1));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat8.zzzz) + u_xlat1));
  (gl_Position = (u_xlat1 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (vs_TEXCOORD0.xy = in_TEXCOORD0.xy);
  (u_xlat1.x = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati0 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[0].xyz));
  (u_xlat1.y = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati0 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[1].xyz));
  (u_xlat1.z = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati0 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[2].xyz));
  (u_xlat0 = dot(u_xlat1.xyz, u_xlat1.xyz));
  (u_xlat0 = max(u_xlat0, 0.0));
  (u_xlat0 = inversesqrt(u_xlat0));
  (vs_TEXCOORD1.xyz = (vec3(u_xlat0) * u_xlat1.xyz));
  (u_xlat0 = (u_xlat8.y + (-_WorldSpaceCameraPos.y)));
  (u_xlat0 = (u_xlat0 + (-_FogHeight)));
  (u_xlat1.x = (_FogFallOff * 0.0099999998));
  (u_xlat0 = (u_xlat0 * u_xlat1.x));
  (u_xlat1.x = exp2((-u_xlat0)));
  (u_xlat9 = ((-u_xlat1.x) + 1.0));
  (u_xlat1.x = (u_xlat1.x * _FogGlobalDensity));
  (u_xlat0 = (u_xlat9 / u_xlat0));
  (u_xlat0 = (u_xlat1.x * u_xlat0));
  (u_xlat1.xyz = ((-u_xlat8.xyz) + _WorldSpaceCameraPos.xyz));
  (vs_TEXCOORD2.xyz = u_xlat8.xyz);
  (u_xlat8.x = dot(u_xlat1.xyz, u_xlat1.xyz));
  (u_xlat8.x = max(u_xlat8.x, 6.1035156e-05));
  (u_xlat8.x = sqrt(u_xlat8.x));
  (u_xlat8.x = (u_xlat8.x + (-_FogStartDis)));
  (u_xlat8.x = (u_xlat8.x / _FogGradientDis));
  (u_xlat8.x = max(u_xlat8.x, 0.0));
  (u_xlat0 = ((u_xlat0 * u_xlat8.x) + (-_FogStart)));
  (u_xlat8.x = ((-_FogStart) + _FogEnd));
  (u_xlat8.x = (1.0 / u_xlat8.x));
  (u_xlat0 = (u_xlat8.x * u_xlat0));
  (u_xlat0 = clamp(u_xlat0, 0.0, 1.0));
  (u_xlat8.x = ((u_xlat0 * -2.0) + 3.0));
  (u_xlat0 = (u_xlat0 * u_xlat0));
  (vs_TEXCOORD2.w = (u_xlat0 * u_xlat8.x));
  (vs_SV_InstanceID0 = uint(gl_InstanceID));
  return ;
}
