#version 450
uniform vec3 _WorldSpaceCameraPos;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform int unity_BaseInstanceID;
uniform float _FogStart;
uniform float _FogEnd;
uniform float _FogGlobalDensity;
uniform float _FogFallOff;
uniform float _FogHeight;
uniform float _FogStartDis;
uniform float _FogGradientDis;
struct unity_Builtins0Array_Type {
  vec4 hlslcc_mtx4x4unity_ObjectToWorldArray[4];
  vec4 hlslcc_mtx4x4unity_WorldToObjectArray[4];
};
layout(std140, binding = 1) uniform UnityInstancing_PerDraw0{
  unity_Builtins0Array_Type unity_Builtins0Array[128];
};
struct unity_Builtins2Array_Type {
  vec4 unity_SHArArray;
  vec4 unity_SHAgArray;
  vec4 unity_SHAbArray;
  vec4 unity_SHBrArray;
  vec4 unity_SHBgArray;
  vec4 unity_SHBbArray;
  vec4 unity_SHCArray;
};
layout(std140, binding = 2) uniform UnityInstancing_PerDraw2{
  unity_Builtins2Array_Type unity_Builtins2Array[128];
};
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _MainTex_ST;
  vec4 _EmissionColor;
  vec4 _Color;
  vec4 _Fresnel_Color;
  vec4 _Fresnel_Color_Edge;
  vec4 _GPUSKin_TextureSize;
  vec4 _ShadowColor;
  float _VertexOffsetY;
  float _MainLightOn;
  float _MaxAddIntensity1;
  float _EmissionIntensity;
  float _Fresnel_Bisa;
  float _Fresnel_Scale;
  float _Fresnel_Intensity;
  float _CutOff;
  float _AlphaIsR;
  float _Intensity;
  float _NoMainTextureOn;
  float _HeroDayNight_ON;
  float _EMISSIONMAPON_BUILDING_ON;
  float _FadeY;
  float _AlphFadeY_ON;
  float _Fresnel_Scale_Edge;
  float _EMISSIONMAPON_ON;
  float _BlinnPhongOn;
  float _Fresnel_ON;
  float _SheetAnimationON;
  float _MainTexSheetAnimSpeed;
  vec4 _MainTexSheet;
};
in vec4 in_POSITION0;
in vec2 in_TEXCOORD0;
in vec3 in_NORMAL0;
out vec2 vs_TEXCOORD0;
out vec3 vs_TEXCOORD1;
out vec4 vs_TEXCOORD2;
out vec3 vs_TEXCOORD3;
out vec3 vs_TEXCOORD5;
out vec3 vs_TEXCOORD6;
flat out uint vs_SV_InstanceID0;
float u_xlat0;
vec3 u_xlat1;
vec4 u_xlat16_1;
vec4 u_xlat2;
vec3 u_xlat3;
vec3 u_xlat16_4;
vec3 u_xlat16_5;
int u_xlati6;
float u_xlat12;
int u_xlati12;
float u_xlat18;
void main(){
  (u_xlat0 = (in_POSITION0.y + _VertexOffsetY));
  (u_xlati6 = (gl_InstanceID + unity_BaseInstanceID));
  (u_xlati12 = int((u_xlati6 << 3)));
  (u_xlati6 = (u_xlati6 * 7));
  (u_xlat1.xyz = (vec3(u_xlat0) * unity_Builtins0Array[(u_xlati12 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[1].xyz));
  (u_xlat1.xyz = ((unity_Builtins0Array[(u_xlati12 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[0].xyz * in_POSITION0.xxx) + u_xlat1.xyz));
  (u_xlat1.xyz = ((unity_Builtins0Array[(u_xlati12 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[2].xyz * in_POSITION0.zzz) + u_xlat1.xyz));
  (u_xlat1.xyz = (u_xlat1.xyz + unity_Builtins0Array[(u_xlati12 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[3].xyz));
  (u_xlat2 = (u_xlat1.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat2 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat1.xxxx) + u_xlat2));
  (u_xlat2 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat1.zzzz) + u_xlat2));
  (gl_Position = (u_xlat2 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (vs_TEXCOORD0.xy = in_TEXCOORD0.xy);
  (u_xlat2.x = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati12 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[0].xyz));
  (u_xlat2.y = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati12 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[1].xyz));
  (u_xlat2.z = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati12 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[2].xyz));
  (u_xlat0 = dot(u_xlat2.xyz, u_xlat2.xyz));
  (u_xlat0 = max(u_xlat0, 0.0));
  (u_xlat0 = inversesqrt(u_xlat0));
  (u_xlat2.xyz = (vec3(u_xlat0) * u_xlat2.xyz));
  (vs_TEXCOORD1.xyz = u_xlat2.xyz);
  (u_xlat0 = (u_xlat1.y + (-_WorldSpaceCameraPos.y)));
  (u_xlat0 = (u_xlat0 + (-_FogHeight)));
  (u_xlat12 = (_FogFallOff * 0.0099999998));
  (u_xlat0 = (u_xlat0 * u_xlat12));
  (u_xlat12 = exp2((-u_xlat0)));
  (u_xlat18 = ((-u_xlat12) + 1.0));
  (u_xlat12 = (u_xlat12 * _FogGlobalDensity));
  (u_xlat0 = (u_xlat18 / u_xlat0));
  (u_xlat0 = (u_xlat12 * u_xlat0));
  (u_xlat3.xyz = ((-u_xlat1.xyz) + _WorldSpaceCameraPos.xyz));
  (vs_TEXCOORD2.xyz = u_xlat1.xyz);
  (u_xlat12 = dot(u_xlat3.xyz, u_xlat3.xyz));
  (u_xlat12 = max(u_xlat12, 6.1035156e-05));
  (u_xlat12 = sqrt(u_xlat12));
  (u_xlat12 = (u_xlat12 + (-_FogStartDis)));
  (u_xlat12 = (u_xlat12 / _FogGradientDis));
  (u_xlat12 = max(u_xlat12, 0.0));
  (u_xlat0 = ((u_xlat0 * u_xlat12) + (-_FogStart)));
  (u_xlat12 = ((-_FogStart) + _FogEnd));
  (u_xlat12 = (1.0 / u_xlat12));
  (u_xlat0 = (u_xlat12 * u_xlat0));
  (u_xlat0 = clamp(u_xlat0, 0.0, 1.0));
  (u_xlat12 = ((u_xlat0 * -2.0) + 3.0));
  (u_xlat0 = (u_xlat0 * u_xlat0));
  (vs_TEXCOORD2.w = (u_xlat0 * u_xlat12));
  (u_xlat16_4.x = (u_xlat2.y * u_xlat2.y));
  (u_xlat16_4.x = ((u_xlat2.x * u_xlat2.x) + (-u_xlat16_4.x)));
  (u_xlat16_1 = (u_xlat2.yzzx * u_xlat2.xyzz));
  (u_xlat16_5.x = dot(unity_Builtins2Array[(u_xlati6 / 7)].unity_SHBrArray, u_xlat16_1));
  (u_xlat16_5.y = dot(unity_Builtins2Array[(u_xlati6 / 7)].unity_SHBgArray, u_xlat16_1));
  (u_xlat16_5.z = dot(unity_Builtins2Array[(u_xlati6 / 7)].unity_SHBbArray, u_xlat16_1));
  (u_xlat16_4.xyz = ((unity_Builtins2Array[(u_xlati6 / 7)].unity_SHCArray.xyz * u_xlat16_4.xxx) + u_xlat16_5.xyz));
  (u_xlat2.w = 1.0);
  (u_xlat16_5.x = dot(unity_Builtins2Array[(u_xlati6 / 7)].unity_SHArArray, u_xlat2));
  (u_xlat16_5.y = dot(unity_Builtins2Array[(u_xlati6 / 7)].unity_SHAgArray, u_xlat2));
  (u_xlat16_5.z = dot(unity_Builtins2Array[(u_xlati6 / 7)].unity_SHAbArray, u_xlat2));
  (u_xlat16_4.xyz = (u_xlat16_4.xyz + u_xlat16_5.xyz));
  (vs_TEXCOORD3.xyz = max(u_xlat16_4.xyz, vec3(0.0, 0.0, 0.0)));
  (vs_TEXCOORD5.xyz = vec3(0.0, 0.0, 0.0));
  (vs_TEXCOORD6.xyz = vec3(0.0, 0.0, 0.0));
  (vs_SV_InstanceID0 = uint(gl_InstanceID));
  return ;
}
