#version 450
uniform vec3 _WorldSpaceCameraPos;
uniform vec4 _ScreenParams;
uniform vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
uniform vec4 hlslcc_mtx4x4unity_WorldToObject[4];
uniform vec4 hlslcc_mtx4x4glstate_matrix_projection[4];
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform vec4 _FaceColor;
uniform float _FaceDilate;
uniform float _OutlineSoftness;
uniform vec4 _OutlineColor;
uniform float _OutlineWidth;
uniform float _WeightNormal;
uniform float _WeightBold;
uniform float _ScaleRatioA;
uniform float _VertexOffsetX;
uniform float _VertexOffsetY;
uniform vec4 _ClipRect;
uniform float _MaskSoftnessX;
uniform float _MaskSoftnessY;
uniform float _GradientScale;
uniform float _ScaleX;
uniform float _ScaleY;
uniform float _PerspectiveFilter;
uniform float _Sharpness;
in vec4 in_POSITION0;
in vec3 in_NORMAL0;
in vec4 in_COLOR0;
in vec2 in_TEXCOORD0;
in vec2 in_TEXCOORD1;
out vec4 vs_COLOR0;
out vec4 vs_COLOR1;
out vec4 vs_TEXCOORD0;
out vec4 vs_TEXCOORD1;
out vec4 vs_TEXCOORD2;
vec2 u_xlat0;
bool u_xlatb0;
vec4 u_xlat1;
vec4 u_xlat2;
vec4 u_xlat3;
vec4 u_xlat16_3;
vec4 u_xlat4;
float u_xlat5;
float u_xlat7;
float u_xlat10;
float u_xlat12;
float u_xlat15;
bool u_xlatb15;
void main(){
  (u_xlat0.xy = (in_POSITION0.xy + vec2(_VertexOffsetX, _VertexOffsetY)));
  (u_xlat1 = (u_xlat0.yyyy * hlslcc_mtx4x4unity_ObjectToWorld[1]));
  (u_xlat1 = ((hlslcc_mtx4x4unity_ObjectToWorld[0] * u_xlat0.xxxx) + u_xlat1));
  (u_xlat1 = ((hlslcc_mtx4x4unity_ObjectToWorld[2] * in_POSITION0.zzzz) + u_xlat1));
  (u_xlat2 = (u_xlat1 + hlslcc_mtx4x4unity_ObjectToWorld[3]));
  (u_xlat1.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[3].xyz * in_POSITION0.www) + u_xlat1.xyz));
  (u_xlat1.xyz = ((-u_xlat1.xyz) + _WorldSpaceCameraPos.xyz));
  (u_xlat3 = (u_xlat2.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat3 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat2.xxxx) + u_xlat3));
  (u_xlat3 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat2.zzzz) + u_xlat3));
  (u_xlat2 = ((hlslcc_mtx4x4unity_MatrixVP[3] * u_xlat2.wwww) + u_xlat3));
  (gl_Position = u_xlat2);
  (u_xlat16_3 = (in_COLOR0 * _FaceColor));
  (u_xlat16_3.xyz = (u_xlat16_3.www * u_xlat16_3.xyz));
  (vs_COLOR0 = u_xlat16_3);
  (u_xlat10 = dot(u_xlat1.xyz, u_xlat1.xyz));
  (u_xlat10 = inversesqrt(u_xlat10));
  (u_xlat1.xyz = (vec3(u_xlat10) * u_xlat1.xyz));
  (u_xlat2.x = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[0].xyz));
  (u_xlat2.y = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[1].xyz));
  (u_xlat2.z = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[2].xyz));
  (u_xlat10 = dot(u_xlat2.xyz, u_xlat2.xyz));
  (u_xlat10 = inversesqrt(u_xlat10));
  (u_xlat2.xyz = (vec3(u_xlat10) * u_xlat2.xyz));
  (u_xlat10 = dot(u_xlat2.xyz, u_xlat1.xyz));
  (u_xlat1.xy = (_ScreenParams.yy * hlslcc_mtx4x4glstate_matrix_projection[1].xy));
  (u_xlat1.xy = ((hlslcc_mtx4x4glstate_matrix_projection[0].xy * _ScreenParams.xx) + u_xlat1.xy));
  (u_xlat1.xy = (abs(u_xlat1.xy) * vec2(_ScaleX, _ScaleY)));
  (u_xlat1.xy = (u_xlat2.ww / u_xlat1.xy));
  (u_xlat15 = dot(u_xlat1.xy, u_xlat1.xy));
  (u_xlat1.xy = ((vec2(_MaskSoftnessX, _MaskSoftnessY) * vec2(0.25, 0.25)) + u_xlat1.xy));
  (u_xlat1.zw = (vec2(0.25, 0.25) / u_xlat1.xy));
  (u_xlat15 = inversesqrt(u_xlat15));
  (u_xlat2.x = (abs(in_TEXCOORD1.y) * _GradientScale));
  (u_xlat7 = (_Sharpness + 1.0));
  (u_xlat2.x = (u_xlat7 * u_xlat2.x));
  (u_xlat7 = (u_xlat15 * u_xlat2.x));
  (u_xlat12 = ((-_PerspectiveFilter) + 1.0));
  (u_xlat12 = (u_xlat12 * abs(u_xlat7)));
  (u_xlat15 = ((u_xlat15 * u_xlat2.x) + (-u_xlat12)));
  (u_xlat10 = ((abs(u_xlat10) * u_xlat15) + u_xlat12));
  (u_xlatb15 = (hlslcc_mtx4x4glstate_matrix_projection[3].w == 0.0));
  (u_xlat10 = ((u_xlatb15) ? (u_xlat10) : (u_xlat7)));
  (u_xlat15 = (_OutlineSoftness * _ScaleRatioA));
  (u_xlat15 = ((u_xlat15 * u_xlat10) + 1.0));
  (u_xlat2.x = (u_xlat10 / u_xlat15));
  (u_xlat10 = (_OutlineWidth * _ScaleRatioA));
  (u_xlat10 = (u_xlat2.x * u_xlat10));
  (u_xlat15 = min(u_xlat10, 1.0));
  (u_xlat15 = sqrt(u_xlat15));
  (u_xlat4.x = (in_COLOR0.w * _OutlineColor.w));
  (u_xlat4.xyz = ((_OutlineColor.xyz * u_xlat4.xxx) + (-u_xlat16_3.xyz)));
  (u_xlat4.w = ((_OutlineColor.w * in_COLOR0.w) + (-u_xlat16_3.w)));
  (u_xlat3 = ((vec4(u_xlat15) * u_xlat4) + u_xlat16_3));
  (vs_COLOR1 = u_xlat3);
  (u_xlat3 = max(_ClipRect, vec4(-20000000000.0, -20000000000.0, -20000000000.0, -20000000000.0)));
  (u_xlat3 = min(u_xlat3, vec4(20000000000.0, 20000000000.0, 20000000000.0, 20000000000.0)));
  (u_xlat4.xy = (u_xlat0.xy + (-u_xlat3.xy)));
  (u_xlat0.xy = ((u_xlat0.xy * vec2(2.0, 2.0)) + (-u_xlat3.xy)));
  (u_xlat1.xy = ((-u_xlat3.zw) + u_xlat0.xy));
  (u_xlat0.xy = ((-u_xlat3.xy) + u_xlat3.zw));
  (vs_TEXCOORD0.zw = (u_xlat4.xy / u_xlat0.xy));
  (vs_TEXCOORD2 = u_xlat1);
  (vs_TEXCOORD0.xy = in_TEXCOORD0.xy);
  (u_xlatb0 = (0.0 >= in_TEXCOORD1.y));
  (u_xlat0.x = ((u_xlatb0) ? (1.0) : (0.0)));
  (u_xlat5 = ((-_WeightNormal) + _WeightBold));
  (u_xlat0.x = ((u_xlat0.x * u_xlat5) + _WeightNormal));
  (u_xlat0.x = ((u_xlat0.x * 0.25) + _FaceDilate));
  (u_xlat0.x = (u_xlat0.x * _ScaleRatioA));
  (u_xlat0.x = (((-u_xlat0.x) * 0.5) + 0.5));
  (u_xlat2.w = ((u_xlat0.x * u_xlat2.x) + -0.5));
  (u_xlat2.y = (((-u_xlat10) * 0.5) + u_xlat2.w));
  (u_xlat2.z = ((u_xlat10 * 0.5) + u_xlat2.w));
  (vs_TEXCOORD1 = u_xlat2);
  return ;
}
