#version 450
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform vec4 hlslcc_mtx4x4_MainLightWorldToShadow[20];
layout(std140, binding = 0) uniform UnityPerDraw{
  vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
  vec4 hlslcc_mtx4x4unity_WorldToObject[4];
  vec4 unity_LODFade;
  vec4 unity_WorldTransformParams;
  vec4 unity_RenderingLayer;
  vec4 unity_LightData;
  vec4 unity_LightIndices[2];
  vec4 unity_ProbesOcclusion;
  vec4 unity_SpecCube0_HDR;
  vec4 unity_SpecCube1_HDR;
  vec4 unity_SpecCube0_BoxMax;
  vec4 unity_SpecCube0_BoxMin;
  vec4 unity_SpecCube0_ProbePosition;
  vec4 unity_SpecCube1_BoxMax;
  vec4 unity_SpecCube1_BoxMin;
  vec4 unity_SpecCube1_ProbePosition;
  vec4 unity_LightmapST;
  vec4 unity_DynamicLightmapST;
  vec4 unity_SHAr;
  vec4 unity_SHAg;
  vec4 unity_SHAb;
  vec4 unity_SHBr;
  vec4 unity_SHBg;
  vec4 unity_SHBb;
  vec4 unity_SHC;
  vec4 hlslcc_mtx4x4unity_MatrixPreviousM[4];
  vec4 hlslcc_mtx4x4unity_MatrixPreviousMI[4];
  vec4 unity_MotionVectorsParams;
};
in vec4 in_POSITION0;
in vec3 in_NORMAL0;
in vec4 in_TEXCOORD0;
out vec4 vs_TEXCOORD0;
out vec4 vs_TEXCOORD1;
out vec2 vs_TEXCOORD3;
out vec3 vs_TEXCOORD4;
out vec3 vs_TEXCOORD5;
vec4 u_xlat0;
vec4 u_xlat1;
vec4 u_xlat16_1;
vec3 u_xlat16_2;
vec3 u_xlat16_3;
float u_xlat12;
void main(){
  (u_xlat0.xyz = (in_POSITION0.yyy * hlslcc_mtx4x4unity_ObjectToWorld[1].xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[0].xyz * in_POSITION0.xxx) + u_xlat0.xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[2].xyz * in_POSITION0.zzz) + u_xlat0.xyz));
  (u_xlat0.xyz = (u_xlat0.xyz + hlslcc_mtx4x4unity_ObjectToWorld[3].xyz));
  (u_xlat1 = (u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx) + u_xlat1));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz) + u_xlat1));
  (gl_Position = (u_xlat1 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (vs_TEXCOORD0.xyz = u_xlat0.xyz);
  (vs_TEXCOORD0.w = 0.0);
  (u_xlat1.xyz = (u_xlat0.yyy * hlslcc_mtx4x4_MainLightWorldToShadow[1].xyz));
  (u_xlat0.xyw = ((hlslcc_mtx4x4_MainLightWorldToShadow[0].xyz * u_xlat0.xxx) + u_xlat1.xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4_MainLightWorldToShadow[2].xyz * u_xlat0.zzz) + u_xlat0.xyw));
  (vs_TEXCOORD1.xyz = (u_xlat0.xyz + hlslcc_mtx4x4_MainLightWorldToShadow[3].xyz));
  (vs_TEXCOORD1.w = 0.0);
  (vs_TEXCOORD3.xy = in_TEXCOORD0.xy);
  (u_xlat0.x = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[0].xyz));
  (u_xlat0.y = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[1].xyz));
  (u_xlat0.z = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[2].xyz));
  (u_xlat12 = dot(u_xlat0.xyz, u_xlat0.xyz));
  (u_xlat12 = max(u_xlat12, 0.0));
  (u_xlat12 = inversesqrt(u_xlat12));
  (u_xlat0.xyz = (vec3(u_xlat12) * u_xlat0.xyz));
  (vs_TEXCOORD4.xyz = u_xlat0.xyz);
  (u_xlat12 = dot(u_xlat0.xyz, u_xlat0.xyz));
  (u_xlat12 = inversesqrt(u_xlat12));
  (u_xlat0 = (vec4(u_xlat12) * u_xlat0.xyzz));
  (u_xlat16_2.x = (u_xlat0.y * u_xlat0.y));
  (u_xlat16_2.x = ((u_xlat0.x * u_xlat0.x) + (-u_xlat16_2.x)));
  (u_xlat16_1 = (u_xlat0.yzwx * u_xlat0.xywz));
  (u_xlat16_3.x = dot(unity_SHBr, u_xlat16_1));
  (u_xlat16_3.y = dot(unity_SHBg, u_xlat16_1));
  (u_xlat16_3.z = dot(unity_SHBb, u_xlat16_1));
  (u_xlat16_2.xyz = ((unity_SHC.xyz * u_xlat16_2.xxx) + u_xlat16_3.xyz));
  (u_xlat0.w = 1.0);
  (u_xlat16_3.x = dot(unity_SHAr, u_xlat0));
  (u_xlat16_3.y = dot(unity_SHAg, u_xlat0));
  (u_xlat16_3.z = dot(unity_SHAb, u_xlat0));
  (u_xlat16_2.xyz = (u_xlat16_2.xyz + u_xlat16_3.xyz));
  (vs_TEXCOORD5.xyz = max(u_xlat16_2.xyz, vec3(0.0, 0.0, 0.0)));
  return ;
}
