#version 450
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform int unity_BaseInstanceID;
struct unity_Builtins0Array_Type {
  vec4 hlslcc_mtx4x4unity_ObjectToWorldArray[4];
  vec4 hlslcc_mtx4x4unity_WorldToObjectArray[4];
};
layout(std140, binding = 1) uniform UnityInstancing_PerDraw0{
  unity_Builtins0Array_Type unity_Builtins0Array[128];
};
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _Remp_Tex_ST;
  vec4 _Mask_Tex_ST;
  vec4 _Diss_Tex_ST;
  vec4 _Turb_Tex_UV;
  vec4 _Turb_Tex_ST;
  vec4 _Main_Tex_ST;
  vec4 _MainTex_ST;
  vec4 _Main_Tex_Color;
  vec4 _Diss_Tex_EdgeColor;
  vec2 _Remp_Tex_UV;
  vec2 _Main_Tex_UV;
  vec2 _Mask_Tex_UV;
  vec2 _Diss_Tex_UV;
  float _Diss_Tex_EdgeWidth;
  float _Main_Tex_Alpha;
  float _Diss_Tex_value;
  float _Turb_Mask_Value;
  float _Turb_Diss_Value;
  float _Main_Tex_A_NO_R;
  float _StencilReadMask;
  float _Turb_RempTex_Value;
  float _Mask_Tex_Rotator;
  float _Main_Tex_Brightness;
  float _Main_Tex_Rotator;
  float _Turb_Main_Value;
  float _StencilComp;
  float _StencilWriteMask;
  float _Stencil;
  float _StencilOp;
  float _Diss_Tex_Soft_value;
  float _Tex_2_A_NO_R;
  float _Mask_Tex_A;
  float _Diss_Tex_Particle_ON;
  float _Main_Tex_Particle_Speed;
  float _Turb_MainTex_ON;
  float _Turb_Noise_Polar_ON;
  float _Diss_Tex_Edge_NO;
  float _RotatorFromZero_On;
  int _UseUITex;
  int _MaskTex02On;
  int _Mask_Tex02_A;
  float _Mask_Tex02_Rotator;
  vec4 _Mask_Tex02_UV;
  vec4 _Mask_Tex02_ST;
  int _Mask01RotatorFromZero_On;
  int _Mask02RotatorFromZero_On;
  int _HDRColorFix;
};
in vec4 in_POSITION0;
in vec4 in_TEXCOORD0;
in vec4 in_TEXCOORD1;
in vec4 in_COLOR0;
out vec4 vs_TEXCOORD0;
out vec4 vs_TEXCOORD1;
out vec2 vs_TEXCOORD2;
out vec4 vs_TEXCOORD3;
out vec4 vs_COLOR0;
out vec4 vs_TEXCOORD4;
out vec4 vs_TEXCOORD5;
flat out uint vs_SV_InstanceID0;
vec4 u_xlat0;
int u_xlati0;
bool u_xlatb0;
vec4 u_xlat1;
vec2 u_xlat16_2;
bool u_xlatb4;
float u_xlat6;
float u_xlat9;
bool u_xlatb9;
void main(){
  (u_xlati0 = (gl_InstanceID + unity_BaseInstanceID));
  (u_xlati0 = int((u_xlati0 << 3)));
  (u_xlat1 = (in_POSITION0.yyyy * unity_Builtins0Array[(u_xlati0 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[1]));
  (u_xlat1 = ((unity_Builtins0Array[(u_xlati0 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[0] * in_POSITION0.xxxx) + u_xlat1));
  (u_xlat1 = ((unity_Builtins0Array[(u_xlati0 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[2] * in_POSITION0.zzzz) + u_xlat1));
  (u_xlat0 = (u_xlat1 + unity_Builtins0Array[(u_xlati0 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[3]));
  (u_xlat1 = (u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx) + u_xlat1));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz) + u_xlat1));
  (gl_Position = ((hlslcc_mtx4x4unity_MatrixVP[3] * u_xlat0.wwww) + u_xlat1));
  (vs_TEXCOORD0.xy = in_TEXCOORD0.xy);
  (vs_TEXCOORD0.zw = vec2(0.0, 0.0));
  (vs_TEXCOORD1 = in_TEXCOORD1);
  (u_xlat16_2.xy = (vec2(_Main_Tex_Rotator, _Mask_Tex_Rotator) * vec2(0.017453294, 0.017453294)));
  (vs_TEXCOORD2.x = cos(u_xlat16_2.x));
  (vs_TEXCOORD2.y = sin(u_xlat16_2.x));
  (u_xlat0.xy = ((in_TEXCOORD0.xy * _Turb_Tex_ST.xy) + _Turb_Tex_ST.zw));
  (u_xlat0.xy = (u_xlat0.xy + vec2(-0.5, -0.5)));
  (u_xlat6 = max(abs(u_xlat0.y), abs(u_xlat0.x)));
  (u_xlat6 = (1.0 / u_xlat6));
  (u_xlat9 = min(abs(u_xlat0.y), abs(u_xlat0.x)));
  (u_xlat6 = (u_xlat6 * u_xlat9));
  (u_xlat9 = (u_xlat6 * u_xlat6));
  (u_xlat1.x = ((u_xlat9 * 0.0208351) + -0.085133001));
  (u_xlat1.x = ((u_xlat9 * u_xlat1.x) + 0.180141));
  (u_xlat1.x = ((u_xlat9 * u_xlat1.x) + -0.3302995));
  (u_xlat9 = ((u_xlat9 * u_xlat1.x) + 0.99986601));
  (u_xlat1.x = (u_xlat9 * u_xlat6));
  (u_xlat1.x = ((u_xlat1.x * -2.0) + 1.5707964));
  (u_xlatb4 = (abs(u_xlat0.y) < abs(u_xlat0.x)));
  (u_xlat1.x = ((u_xlatb4) ? (u_xlat1.x) : (0.0)));
  (u_xlat6 = ((u_xlat6 * u_xlat9) + u_xlat1.x));
  (u_xlatb9 = (u_xlat0.y < (-u_xlat0.y)));
  (u_xlat9 = ((u_xlatb9) ? (-3.1415927) : (0.0)));
  (u_xlat6 = (u_xlat9 + u_xlat6));
  (u_xlat9 = min(u_xlat0.y, u_xlat0.x));
  (u_xlatb9 = (u_xlat9 < (-u_xlat9)));
  (u_xlat1.x = max(u_xlat0.y, u_xlat0.x));
  (u_xlat0.x = dot(u_xlat0.xy, u_xlat0.xy));
  (u_xlat0.x = sqrt(u_xlat0.x));
  (vs_TEXCOORD3.z = dot(u_xlat0.xx, _Turb_Tex_UV.zz));
  (u_xlatb0 = (u_xlat1.x >= (-u_xlat1.x)));
  (u_xlatb0 = (u_xlatb0 && u_xlatb9));
  (u_xlat0.x = ((u_xlatb0) ? ((-u_xlat6)) : (u_xlat6)));
  (u_xlat0.x = (u_xlat0.x * _Turb_Tex_UV.w));
  (vs_TEXCOORD3.w = (u_xlat0.x * 0.15915));
  (vs_TEXCOORD3.x = cos(u_xlat16_2.y));
  (vs_TEXCOORD3.y = sin(u_xlat16_2.y));
  (vs_COLOR0 = in_COLOR0);
  (vs_TEXCOORD4 = vec4(0.0, 0.0, 0.0, 0.0));
  (u_xlat16_2.x = (_Mask_Tex02_Rotator * 0.017453294));
  (u_xlat0.x = sin(u_xlat16_2.x));
  (u_xlat1.x = cos(u_xlat16_2.x));
  (vs_TEXCOORD5.x = u_xlat1.x);
  (vs_TEXCOORD5.y = u_xlat0.x);
  (vs_TEXCOORD5.zw = vec2(0.0, 0.0));
  (vs_SV_InstanceID0 = uint(gl_InstanceID));
  return ;
}
