#version 450
uniform vec2 _GlobalMipBias;
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _MainTex_ST;
  vec4 _MainColor;
  vec4 _Main02Color;
  vec4 _MainTex02_ST;
  vec4 _mainUVMove;
  vec4 _main02UVMove;
  vec4 _NoiseColor;
  vec4 _NoiseTex_ST;
  vec4 _noiseUVMove;
  vec4 _WPODir;
  vec4 _DissolveTex_ST;
  vec4 _EdgeColor;
  vec4 _depc;
  vec4 _dissolveUVMove;
  vec4 _MaskTex_ST;
  vec4 _maskUVMove;
  vec4 _FresnelColor;
  vec4 _FalseViewDir;
  vec4 _HeightFadeParam;
  int _MaskType;
  float _HeightFade;
  float _MWarpMode;
  float _M02WarpMode;
  float _UVChannel;
  float _BlackOff;
  float _BlackOff_1;
  float _NWarpMode;
  float _DistortIntensity;
  float _DissolveDirToggle;
  float _DissolveDir;
  float _InvertDissolveDir;
  float _particleUV;
  float _dissolveMode;
  float _DWarpMode;
  float _DistortMod;
  float _WPOMod;
  float _MaskTexUV;
  float _MKWarpMode;
  float _CameraOffset;
  float _BlendMode;
  float _InvertMode;
  float _FalseFresnel;
  float _FresnelPower;
  float _Desaturate;
  float _MainColorIntensity;
  float _Main02ColorIntensity;
  float _NoiseColorIntensity;
  float _EdgeColorIntensity;
  float _FresnelColorIntensity;
  float _MainAngle;
  float _Main02Angle;
  float _NoiseAngle;
  float _DissolveAngle;
  float _MaskAngle;
  float _RimIntencity;
  float _ScreenSpaceUV_ON;
  float _MNBlendMode;
};
layout(location = 0) uniform sampler2D _MainTex;
layout(location = 1) uniform sampler2D _MainTex02;
in vec4 vs_TEXCOORD0;
in vec4 vs_TEXCOORD3;
in vec3 vs_TEXCOORD5;
layout(location = 0) out vec4 SV_Target0;
float u_xlat0;
vec4 u_xlat1;
vec4 u_xlat16_1;
vec4 u_xlat16_2;
float u_xlat16_3;
vec4 u_xlat16_4;
float u_xlat5;
vec3 u_xlat16_8;
void main(){
  (u_xlat0 = ((-_HeightFadeParam.x) + _HeightFadeParam.y));
  (u_xlat0 = (1.0 / float(u_xlat0)));
  (u_xlat5 = (vs_TEXCOORD5.y + (-_HeightFadeParam.x)));
  (u_xlat0 = (u_xlat0 * u_xlat5));
  (u_xlat0 = clamp(u_xlat0, 0.0, 1.0));
  (u_xlat0 = (u_xlat0 + -1.0));
  (u_xlat0 = ((_HeightFade * u_xlat0) + 1.0));
  (u_xlat1 = vs_TEXCOORD0);
  (u_xlat1 = clamp(u_xlat1, 0.0, 1.0));
  (u_xlat1 = (u_xlat1 + (-vs_TEXCOORD0)));
  (u_xlat1 = ((vec4(_MWarpMode, _MWarpMode, _M02WarpMode, _M02WarpMode) * u_xlat1) + vs_TEXCOORD0));
  (u_xlat16_2 = texture(_MainTex, u_xlat1.xy, _GlobalMipBias.x));
  (u_xlat16_1 = texture(_MainTex02, u_xlat1.zw, _GlobalMipBias.x));
  (u_xlat16_3 = (u_xlat16_1.x + u_xlat16_2.x));
  (u_xlat16_3 = clamp(u_xlat16_3, 0.0, 1.0));
  (u_xlat16_3 = (((-u_xlat16_1.x) * u_xlat16_2.x) + u_xlat16_3));
  (u_xlat16_4 = (u_xlat16_2 * u_xlat16_1));
  (u_xlat16_2 = (u_xlat16_2 * _MainColor));
  (u_xlat16_2 = (u_xlat16_2 * vec4(_MainColorIntensity)));
  (u_xlat16_1 = (u_xlat16_1 * _Main02Color));
  (u_xlat16_1 = ((u_xlat16_1 * vec4(vec4(_Main02ColorIntensity, _Main02ColorIntensity, _Main02ColorIntensity, _Main02ColorIntensity))) + u_xlat16_2));
  (u_xlat16_3 = ((_MNBlendMode * u_xlat16_3) + u_xlat16_4.x));
  (u_xlat16_2 = (u_xlat16_4 * _MainColor));
  (u_xlat16_1 = (((-u_xlat16_2) * vec4(_MainColorIntensity)) + u_xlat16_1));
  (u_xlat16_2 = (u_xlat16_2 * vec4(_MainColorIntensity)));
  (u_xlat16_1 = ((vec4(_MNBlendMode) * u_xlat16_1) + u_xlat16_2));
  (u_xlat16_3 = ((u_xlat16_1.w * u_xlat16_3) + (-u_xlat16_1.w)));
  (u_xlat16_3 = ((_BlackOff * u_xlat16_3) + u_xlat16_1.w));
  (u_xlat16_3 = clamp(u_xlat16_3, 0.0, 1.0));
  (u_xlat0 = (u_xlat0 * u_xlat16_3));
  (u_xlat16_3 = (u_xlat0 * vs_TEXCOORD3.w));
  (u_xlat16_8.x = dot(u_xlat16_1.xyz, vec3(0.22, 0.70700002, 0.071000002)));
  (u_xlat16_8.xyz = ((-u_xlat16_1.xyz) + u_xlat16_8.xxx));
  (u_xlat16_8.xyz = ((vec3(vec3(_Desaturate, _Desaturate, _Desaturate)) * u_xlat16_8.xyz) + u_xlat16_1.xyz));
  (u_xlat16_8.xyz = (u_xlat16_8.xyz * vs_TEXCOORD3.xyz));
  (SV_Target0.xyz = (vec3(u_xlat16_3) * u_xlat16_8.xyz));
  (SV_Target0.w = u_xlat16_3);
  return ;
}
