#version 450
uniform vec3 _WorldSpaceCameraPos;
uniform vec4 _ProjectionParams;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform int unity_BaseInstanceID;
uniform float _FogStart;
uniform float _FogEnd;
uniform float _FogGlobalDensity;
uniform float _FogFallOff;
uniform float _FogHeight;
uniform float _FogStartDis;
uniform float _FogGradientDis;
layout(std140, binding = 0) uniform UnityPerDraw{
  vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
  vec4 hlslcc_mtx4x4unity_WorldToObject[4];
  vec4 unity_LODFade;
  vec4 unity_WorldTransformParams;
  vec4 unity_RenderingLayer;
  vec4 unity_LightData;
  vec4 unity_LightIndices[2];
  vec4 unity_ProbesOcclusion;
  vec4 unity_SpecCube0_HDR;
  vec4 unity_SpecCube1_HDR;
  vec4 unity_SpecCube0_BoxMax;
  vec4 unity_SpecCube0_BoxMin;
  vec4 unity_SpecCube0_ProbePosition;
  vec4 unity_SpecCube1_BoxMax;
  vec4 unity_SpecCube1_BoxMin;
  vec4 unity_SpecCube1_ProbePosition;
  vec4 unity_LightmapST;
  vec4 unity_DynamicLightmapST;
  vec4 unity_SHAr;
  vec4 unity_SHAg;
  vec4 unity_SHAb;
  vec4 unity_SHBr;
  vec4 unity_SHBg;
  vec4 unity_SHBb;
  vec4 unity_SHC;
  vec4 hlslcc_mtx4x4unity_MatrixPreviousM[4];
  vec4 hlslcc_mtx4x4unity_MatrixPreviousMI[4];
  vec4 unity_MotionVectorsParams;
};
struct unity_Builtins0Array_Type {
  vec4 hlslcc_mtx4x4unity_ObjectToWorldArray[4];
  vec4 hlslcc_mtx4x4unity_WorldToObjectArray[4];
};
layout(std140, binding = 2) uniform UnityInstancing_PerDraw0{
  unity_Builtins0Array_Type unity_Builtins0Array[128];
};
struct unity_Builtins2Array_Type {
  vec4 unity_SHArArray;
  vec4 unity_SHAgArray;
  vec4 unity_SHAbArray;
  vec4 unity_SHBrArray;
  vec4 unity_SHBgArray;
  vec4 unity_SHBbArray;
  vec4 unity_SHCArray;
};
layout(std140, binding = 3) uniform UnityInstancing_PerDraw2{
  unity_Builtins2Array_Type unity_Builtins2Array[128];
};
in vec4 in_POSITION0;
in vec3 in_NORMAL0;
in vec4 in_TANGENT0;
in vec2 in_TEXCOORD0;
in vec2 in_TEXCOORD1;
out vec4 vs_TEXCOORD0;
out vec4 vs_TEXCOORD2;
out vec4 vs_TEXCOORD3;
out vec4 vs_TEXCOORD4;
out vec4 vs_TEXCOORD5;
out vec4 vs_TEXCOORD6;
flat out uint vs_SV_InstanceID0;
vec4 u_xlat0;
int u_xlati0;
vec3 u_xlat1;
vec4 u_xlat2;
vec4 u_xlat3;
vec4 u_xlat16_3;
vec4 u_xlat4;
vec4 u_xlat5;
vec3 u_xlat16_6;
vec3 u_xlat16_7;
vec3 u_xlat8;
int u_xlati8;
float u_xlat16;
float u_xlat24;
float u_xlat25;
bool u_xlatb25;
void main(){
  (u_xlati0 = (gl_InstanceID + unity_BaseInstanceID));
  (u_xlati8 = int((u_xlati0 << 3)));
  (u_xlati0 = (u_xlati0 * 7));
  (u_xlat1.xyz = (in_POSITION0.yyy * unity_Builtins0Array[(u_xlati8 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[1].xyz));
  (u_xlat1.xyz = ((unity_Builtins0Array[(u_xlati8 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[0].xyz * in_POSITION0.xxx) + u_xlat1.xyz));
  (u_xlat1.xyz = ((unity_Builtins0Array[(u_xlati8 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[2].xyz * in_POSITION0.zzz) + u_xlat1.xyz));
  (u_xlat1.xyz = (u_xlat1.xyz + unity_Builtins0Array[(u_xlati8 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[3].xyz));
  (u_xlat2 = (u_xlat1.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat2 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat1.xxxx) + u_xlat2));
  (u_xlat2 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat1.zzzz) + u_xlat2));
  (u_xlat2 = (u_xlat2 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (gl_Position = u_xlat2);
  (u_xlat3.xy = in_TEXCOORD0.xy);
  (u_xlat3.zw = in_TEXCOORD1.xy);
  (vs_TEXCOORD0 = u_xlat3);
  (u_xlat3.x = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati8 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[0].xyz));
  (u_xlat3.y = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati8 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[1].xyz));
  (u_xlat3.z = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati8 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[2].xyz));
  (u_xlat16 = dot(u_xlat3.xyz, u_xlat3.xyz));
  (u_xlat16 = max(u_xlat16, 0.0));
  (u_xlat16 = inversesqrt(u_xlat16));
  (u_xlat3 = (vec4(u_xlat16) * u_xlat3.xyzz));
  (u_xlat4.xyz = u_xlat3.xyw);
  (u_xlat4.w = u_xlat1.x);
  (vs_TEXCOORD2 = u_xlat4);
  (u_xlat5.xyz = (in_TANGENT0.yyy * unity_Builtins0Array[(u_xlati8 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[1].xyz));
  (u_xlat5.xyz = ((unity_Builtins0Array[(u_xlati8 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[0].xyz * in_TANGENT0.xxx) + u_xlat5.xyz));
  (u_xlat8.xyz = ((unity_Builtins0Array[(u_xlati8 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[2].xyz * in_TANGENT0.zzz) + u_xlat5.xyz));
  (u_xlat25 = dot(u_xlat8.xyz, u_xlat8.xyz));
  (u_xlat25 = max(u_xlat25, 0.0));
  (u_xlat25 = inversesqrt(u_xlat25));
  (u_xlat5.xyz = (u_xlat8.xyz * vec3(u_xlat25)));
  (u_xlat5.w = u_xlat1.y);
  (vs_TEXCOORD3 = u_xlat5);
  (u_xlat8.xyz = (u_xlat3.wxy * u_xlat5.yzx));
  (u_xlat8.xyz = ((u_xlat3.ywx * u_xlat5.zxy) + (-u_xlat8.xyz)));
  (u_xlatb25 = (unity_WorldTransformParams.w >= 0.0));
  (u_xlat25 = ((u_xlatb25) ? (1.0) : (-1.0)));
  (u_xlat16_6.x = (u_xlat25 * in_TANGENT0.w));
  (vs_TEXCOORD4.xyz = (u_xlat8.xyz * u_xlat16_6.xxx));
  (vs_TEXCOORD4.w = u_xlat1.z);
  (u_xlat16_6.x = (u_xlat4.y * u_xlat4.y));
  (u_xlat16_6.x = ((u_xlat4.x * u_xlat4.x) + (-u_xlat16_6.x)));
  (u_xlat16_3 = (u_xlat3.ywzx * u_xlat3));
  (u_xlat16_7.x = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHBrArray, u_xlat16_3));
  (u_xlat16_7.y = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHBgArray, u_xlat16_3));
  (u_xlat16_7.z = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHBbArray, u_xlat16_3));
  (u_xlat16_6.xyz = ((unity_Builtins2Array[(u_xlati0 / 7)].unity_SHCArray.xyz * u_xlat16_6.xxx) + u_xlat16_7.xyz));
  (u_xlat4.w = 1.0);
  (u_xlat16_7.x = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHArArray, u_xlat4));
  (u_xlat16_7.y = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHAgArray, u_xlat4));
  (u_xlat16_7.z = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHAbArray, u_xlat4));
  (u_xlat16_6.xyz = (u_xlat16_6.xyz + u_xlat16_7.xyz));
  (vs_TEXCOORD5.xyz = max(u_xlat16_6.xyz, vec3(0.0, 0.0, 0.0)));
  (u_xlat0.x = (u_xlat1.y + (-_WorldSpaceCameraPos.y)));
  (u_xlat8.xyz = ((-u_xlat1.xyz) + _WorldSpaceCameraPos.xyz));
  (u_xlat8.x = dot(u_xlat8.xyz, u_xlat8.xyz));
  (u_xlat8.x = max(u_xlat8.x, 6.1035156e-05));
  (u_xlat0.y = sqrt(u_xlat8.x));
  (u_xlat0.xy = (u_xlat0.xy + (-vec2(_FogHeight, _FogStartDis))));
  (u_xlat8.x = (u_xlat0.y / _FogGradientDis));
  (u_xlat8.x = max(u_xlat8.x, 0.0));
  (u_xlat16 = (_FogFallOff * 0.0099999998));
  (u_xlat0.x = (u_xlat0.x * u_xlat16));
  (u_xlat16 = exp2((-u_xlat0.x)));
  (u_xlat24 = ((-u_xlat16) + 1.0));
  (u_xlat16 = (u_xlat16 * _FogGlobalDensity));
  (u_xlat0.x = (u_xlat24 / u_xlat0.x));
  (u_xlat0.x = (u_xlat16 * u_xlat0.x));
  (u_xlat0.x = ((u_xlat0.x * u_xlat8.x) + (-_FogStart)));
  (u_xlat8.x = ((-_FogStart) + _FogEnd));
  (u_xlat8.x = (1.0 / u_xlat8.x));
  (u_xlat0.x = (u_xlat8.x * u_xlat0.x));
  (u_xlat0.x = clamp(u_xlat0.x, 0.0, 1.0));
  (u_xlat8.x = ((u_xlat0.x * -2.0) + 3.0));
  (u_xlat0.x = (u_xlat0.x * u_xlat0.x));
  (u_xlat0.x = (u_xlat0.x * u_xlat8.x));
  (vs_TEXCOORD5.w = u_xlat0.x);
  (u_xlat0.x = (u_xlat2.y * _ProjectionParams.x));
  (u_xlat0.w = (u_xlat0.x * 0.5));
  (u_xlat0.xz = (u_xlat2.xw * vec2(0.5, 0.5)));
  (vs_TEXCOORD6.zw = u_xlat2.zw);
  (vs_TEXCOORD6.xy = (u_xlat0.zz + u_xlat0.xw));
  (vs_SV_InstanceID0 = uint(gl_InstanceID));
  return ;
}
