#version 450
uniform vec3 _WorldSpaceCameraPos;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform int unity_BaseInstanceID;
uniform vec4 hlslcc_mtx4x4_MainLightWorldToShadow[20];
uniform float _FogStart;
uniform float _FogEnd;
uniform float _FogGlobalDensity;
uniform float _FogFallOff;
uniform float _FogHeight;
uniform float _FogStartDis;
uniform float _FogGradientDis;
struct unity_Builtins0Array_Type {
  vec4 hlslcc_mtx4x4unity_ObjectToWorldArray[4];
  vec4 hlslcc_mtx4x4unity_WorldToObjectArray[4];
};
layout(std140, binding = 2) uniform UnityInstancing_PerDraw0{
  unity_Builtins0Array_Type unity_Builtins0Array[128];
};
struct unity_Builtins2Array_Type {
  vec4 unity_SHArArray;
  vec4 unity_SHAgArray;
  vec4 unity_SHAbArray;
  vec4 unity_SHBrArray;
  vec4 unity_SHBgArray;
  vec4 unity_SHBbArray;
  vec4 unity_SHCArray;
};
layout(std140, binding = 3) uniform UnityInstancing_PerDraw2{
  unity_Builtins2Array_Type unity_Builtins2Array[128];
};
in vec4 in_POSITION0;
in vec3 in_NORMAL0;
in vec4 in_TEXCOORD0;
out vec4 vs_TEXCOORD0;
out vec4 vs_TEXCOORD1;
out vec2 vs_TEXCOORD3;
out vec3 vs_TEXCOORD4;
out vec3 vs_TEXCOORD5;
flat out uint vs_SV_InstanceID0;
int u_xlati0;
vec4 u_xlat1;
vec4 u_xlat2;
vec4 u_xlat16_2;
vec3 u_xlat16_3;
vec3 u_xlat16_4;
vec3 u_xlat5;
int u_xlati5;
float u_xlat10;
float u_xlat15;
float u_xlat16;
void main(){
  (u_xlati0 = (gl_InstanceID + unity_BaseInstanceID));
  (u_xlati5 = int((u_xlati0 << 3)));
  (u_xlati0 = (u_xlati0 * 7));
  (u_xlat1.xyz = (in_POSITION0.yyy * unity_Builtins0Array[(u_xlati5 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[1].xyz));
  (u_xlat1.xyz = ((unity_Builtins0Array[(u_xlati5 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[0].xyz * in_POSITION0.xxx) + u_xlat1.xyz));
  (u_xlat1.xyz = ((unity_Builtins0Array[(u_xlati5 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[2].xyz * in_POSITION0.zzz) + u_xlat1.xyz));
  (u_xlat1.xyz = (u_xlat1.xyz + unity_Builtins0Array[(u_xlati5 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[3].xyz));
  (u_xlat2 = (u_xlat1.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat2 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat1.xxxx) + u_xlat2));
  (u_xlat2 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat1.zzzz) + u_xlat2));
  (gl_Position = (u_xlat2 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (u_xlat10 = (_FogFallOff * 0.0099999998));
  (u_xlat15 = (u_xlat1.y + (-_WorldSpaceCameraPos.y)));
  (u_xlat15 = (u_xlat15 + (-_FogHeight)));
  (u_xlat10 = (u_xlat15 * u_xlat10));
  (u_xlat15 = exp2((-u_xlat10)));
  (u_xlat16 = ((-u_xlat15) + 1.0));
  (u_xlat15 = (u_xlat15 * _FogGlobalDensity));
  (u_xlat10 = (u_xlat16 / u_xlat10));
  (u_xlat10 = (u_xlat15 * u_xlat10));
  (u_xlat2.xyz = ((-u_xlat1.xyz) + _WorldSpaceCameraPos.xyz));
  (u_xlat15 = dot(u_xlat2.xyz, u_xlat2.xyz));
  (u_xlat15 = max(u_xlat15, 6.1035156e-05));
  (u_xlat15 = sqrt(u_xlat15));
  (u_xlat15 = (u_xlat15 + (-_FogStartDis)));
  (u_xlat15 = (u_xlat15 / _FogGradientDis));
  (u_xlat15 = max(u_xlat15, 0.0));
  (u_xlat10 = ((u_xlat10 * u_xlat15) + (-_FogStart)));
  (u_xlat15 = ((-_FogStart) + _FogEnd));
  (u_xlat15 = (1.0 / u_xlat15));
  (u_xlat10 = (u_xlat15 * u_xlat10));
  (u_xlat10 = clamp(u_xlat10, 0.0, 1.0));
  (u_xlat15 = ((u_xlat10 * -2.0) + 3.0));
  (u_xlat10 = (u_xlat10 * u_xlat10));
  (vs_TEXCOORD0.w = (u_xlat10 * u_xlat15));
  (vs_TEXCOORD0.xyz = u_xlat1.xyz);
  (u_xlat2.xyz = (u_xlat1.yyy * hlslcc_mtx4x4_MainLightWorldToShadow[1].xyz));
  (u_xlat1.xyw = ((hlslcc_mtx4x4_MainLightWorldToShadow[0].xyz * u_xlat1.xxx) + u_xlat2.xyz));
  (u_xlat1.xyz = ((hlslcc_mtx4x4_MainLightWorldToShadow[2].xyz * u_xlat1.zzz) + u_xlat1.xyw));
  (vs_TEXCOORD1.xyz = (u_xlat1.xyz + hlslcc_mtx4x4_MainLightWorldToShadow[3].xyz));
  (vs_TEXCOORD1.w = 0.0);
  (vs_TEXCOORD3.xy = in_TEXCOORD0.xy);
  (u_xlat1.x = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati5 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[0].xyz));
  (u_xlat1.y = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati5 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[1].xyz));
  (u_xlat1.z = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati5 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[2].xyz));
  (u_xlat5.x = dot(u_xlat1.xyz, u_xlat1.xyz));
  (u_xlat5.x = max(u_xlat5.x, 0.0));
  (u_xlat5.x = inversesqrt(u_xlat5.x));
  (u_xlat5.xyz = (u_xlat5.xxx * u_xlat1.xyz));
  (vs_TEXCOORD4.xyz = u_xlat5.xyz);
  (u_xlat1.x = dot(u_xlat5.xyz, u_xlat5.xyz));
  (u_xlat1.x = inversesqrt(u_xlat1.x));
  (u_xlat1 = (u_xlat5.xyzz * u_xlat1.xxxx));
  (u_xlat16_3.x = (u_xlat1.y * u_xlat1.y));
  (u_xlat16_3.x = ((u_xlat1.x * u_xlat1.x) + (-u_xlat16_3.x)));
  (u_xlat16_2 = (u_xlat1.yzwx * u_xlat1.xywz));
  (u_xlat16_4.x = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHBrArray, u_xlat16_2));
  (u_xlat16_4.y = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHBgArray, u_xlat16_2));
  (u_xlat16_4.z = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHBbArray, u_xlat16_2));
  (u_xlat16_3.xyz = ((unity_Builtins2Array[(u_xlati0 / 7)].unity_SHCArray.xyz * u_xlat16_3.xxx) + u_xlat16_4.xyz));
  (u_xlat1.w = 1.0);
  (u_xlat16_4.x = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHArArray, u_xlat1));
  (u_xlat16_4.y = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHAgArray, u_xlat1));
  (u_xlat16_4.z = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHAbArray, u_xlat1));
  (u_xlat16_3.xyz = (u_xlat16_3.xyz + u_xlat16_4.xyz));
  (vs_TEXCOORD5.xyz = max(u_xlat16_3.xyz, vec3(0.0, 0.0, 0.0)));
  (vs_SV_InstanceID0 = uint(gl_InstanceID));
  return ;
}
