#version 450
uniform vec4 _ScreenParams;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
layout(std140, binding = 1) uniform UnityPerDraw{
  vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
  vec4 hlslcc_mtx4x4unity_WorldToObject[4];
  vec4 unity_LODFade;
  vec4 unity_WorldTransformParams;
  vec4 unity_RenderingLayer;
  vec4 unity_LightData;
  vec4 unity_LightIndices[2];
  vec4 unity_ProbesOcclusion;
  vec4 unity_SpecCube0_HDR;
  vec4 unity_SpecCube1_HDR;
  vec4 unity_SpecCube0_BoxMax;
  vec4 unity_SpecCube0_BoxMin;
  vec4 unity_SpecCube0_ProbePosition;
  vec4 unity_SpecCube1_BoxMax;
  vec4 unity_SpecCube1_BoxMin;
  vec4 unity_SpecCube1_ProbePosition;
  vec4 unity_LightmapST;
  vec4 unity_DynamicLightmapST;
  vec4 unity_SHAr;
  vec4 unity_SHAg;
  vec4 unity_SHAb;
  vec4 unity_SHBr;
  vec4 unity_SHBg;
  vec4 unity_SHBb;
  vec4 unity_SHC;
  vec4 hlslcc_mtx4x4unity_MatrixPreviousM[4];
  vec4 hlslcc_mtx4x4unity_MatrixPreviousMI[4];
  vec4 unity_MotionVectorsParams;
};
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _BaseColor;
  float _Cutoff;
  float _Surface;
  float _WidthOutLine;
  float _OutlineScale;
  float _OutlineWidth;
  float _CameraDistanceImpact;
  float _OutlineDepthOffset;
};
in vec4 in_POSITION0;
in vec4 in_NORMAL0;
out vec3 vs_TEXCOORD0;
vec4 phase0_Output0_1;
out float vs_TEXCOORD1;
vec3 u_xlat0;
vec4 u_xlat1;
vec4 u_xlat2;
vec3 u_xlat3;
float u_xlat6;
void main(){
  (u_xlat0.xyz = (in_NORMAL0.yyy * hlslcc_mtx4x4unity_ObjectToWorld[1].xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[0].xyz * in_NORMAL0.xxx) + u_xlat0.xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[2].xyz * in_NORMAL0.zzz) + u_xlat0.xyz));
  (u_xlat3.xz = (u_xlat0.yy * hlslcc_mtx4x4unity_MatrixVP[1].xy));
  (u_xlat0.xy = ((hlslcc_mtx4x4unity_MatrixVP[0].xy * u_xlat0.xx) + u_xlat3.xz));
  (u_xlat0.xy = ((hlslcc_mtx4x4unity_MatrixVP[2].xy * u_xlat0.zz) + u_xlat0.xy));
  (u_xlat6 = dot(u_xlat0.xy, u_xlat0.xy));
  (u_xlat6 = inversesqrt(u_xlat6));
  (u_xlat0.xy = (vec2(u_xlat6) * u_xlat0.xy));
  (u_xlat6 = (1.0 / float(_ScreenParams.y)));
  (u_xlat6 = (u_xlat6 * _ScreenParams.x));
  (u_xlat1.x = (1.0 / float(u_xlat6)));
  (u_xlat1.y = 1.0);
  (u_xlat0.xy = (u_xlat0.xy * u_xlat1.xy));
  (u_xlat0.xy = (u_xlat0.xy * vec2(_OutlineWidth)));
  (u_xlat1.xyz = (in_POSITION0.xyz * vec3(vec3(_OutlineScale, _OutlineScale, _OutlineScale))));
  (u_xlat2 = (u_xlat1.yyyy * hlslcc_mtx4x4unity_ObjectToWorld[1]));
  (u_xlat2 = ((hlslcc_mtx4x4unity_ObjectToWorld[0] * u_xlat1.xxxx) + u_xlat2));
  (u_xlat1 = ((hlslcc_mtx4x4unity_ObjectToWorld[2] * u_xlat1.zzzz) + u_xlat2));
  (u_xlat1 = (u_xlat1 + hlslcc_mtx4x4unity_ObjectToWorld[3]));
  (u_xlat2 = (u_xlat1.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat2 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat1.xxxx) + u_xlat2));
  (u_xlat2 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat1.zzzz) + u_xlat2));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[3] * u_xlat1.wwww) + u_xlat2));
  (u_xlat6 = ((-u_xlat1.w) + 4.0));
  (u_xlat6 = ((_CameraDistanceImpact * u_xlat6) + u_xlat1.w));
  (u_xlat0.xy = (vec2(u_xlat6) * u_xlat0.xy));
  (gl_Position.xy = ((u_xlat0.xy * vec2(0.0049999999, 0.0049999999)) + u_xlat1.xy));
  (gl_Position.z = ((_OutlineDepthOffset * 0.2) + u_xlat1.z));
  (gl_Position.w = u_xlat1.w);
  (phase0_Output0_1 = vec4(0.0, 0.0, 0.0, 0.0));
  (vs_TEXCOORD0 = phase0_Output0_1.xyz);
  (vs_TEXCOORD1 = phase0_Output0_1.w);
  return ;
}
