#version 450
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform int unity_BaseInstanceID;
struct unity_Builtins0Array_Type {
  vec4 hlslcc_mtx4x4unity_ObjectToWorldArray[4];
  vec4 hlslcc_mtx4x4unity_WorldToObjectArray[4];
};
layout(std140, binding = 1) uniform UnityInstancing_PerDraw0{
  unity_Builtins0Array_Type unity_Builtins0Array[128];
};
struct unity_Builtins2Array_Type {
  vec4 unity_SHArArray;
  vec4 unity_SHAgArray;
  vec4 unity_SHAbArray;
  vec4 unity_SHBrArray;
  vec4 unity_SHBgArray;
  vec4 unity_SHBbArray;
  vec4 unity_SHCArray;
};
layout(std140, binding = 2) uniform UnityInstancing_PerDraw2{
  unity_Builtins2Array_Type unity_Builtins2Array[128];
};
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _MainTex_ST;
  vec4 _EmissionColor;
  vec4 _Color;
  vec4 _Fresnel_Color;
  vec4 _Fresnel_Color_Edge;
  vec4 _GPUSKin_TextureSize;
  vec4 _ShadowColor;
  float _VertexOffsetY;
  float _MainLightOn;
  float _MaxAddIntensity1;
  float _EmissionIntensity;
  float _Fresnel_Bisa;
  float _Fresnel_Scale;
  float _Fresnel_Intensity;
  float _CutOff;
  float _AlphaIsR;
  float _Intensity;
  float _NoMainTextureOn;
  float _HeroDayNight_ON;
  float _EMISSIONMAPON_BUILDING_ON;
  float _FadeY;
  float _AlphFadeY_ON;
  float _Fresnel_Scale_Edge;
  float _EMISSIONMAPON_ON;
  float _BlinnPhongOn;
  float _Fresnel_ON;
  float _SheetAnimationON;
  float _MainTexSheetAnimSpeed;
  vec4 _MainTexSheet;
};
struct GPUSkinArray_Type {
  vec4 _GPUSKin_ClipParams;
};
layout(std140, binding = 3) uniform UnityInstancing_GPUSkin{
  GPUSkinArray_Type GPUSkinArray[128];
};
layout(location = 2) uniform sampler2D _GPUSKin_Matrix;
in vec4 in_POSITION0;
in vec2 in_TEXCOORD0;
in vec3 in_NORMAL0;
in vec4 in_TEXCOORD3;
in vec4 in_TEXCOORD4;
out vec2 vs_TEXCOORD0;
out vec3 vs_TEXCOORD1;
out vec4 vs_TEXCOORD2;
out vec3 vs_TEXCOORD3;
out vec3 vs_TEXCOORD5;
out vec3 vs_TEXCOORD6;
flat out uint vs_SV_InstanceID0;
int u_xlati0;
vec4 u_xlat1;
int u_xlati1;
vec4 u_xlat2;
vec4 u_xlat16_2;
vec4 u_xlat3;
vec4 u_xlat4;
vec2 u_xlat16_4;
vec4 u_xlat5;
vec4 u_xlat6;
vec4 u_xlat7;
vec4 u_xlat8;
vec4 u_xlat9;
vec4 u_xlat10;
vec4 u_xlat11;
vec3 u_xlat16_12;
vec3 u_xlat16_13;
vec3 u_xlat14;
vec3 u_xlat15;
vec2 u_xlat28;
void main(){
  (u_xlati0 = (gl_InstanceID + unity_BaseInstanceID));
  (u_xlat14.x = floor(GPUSkinArray[u_xlati0]._GPUSKin_ClipParams.y));
  (u_xlat28.x = (u_xlat14.x + 1.0));
  (u_xlat14.x = ((u_xlat14.x * _GPUSKin_TextureSize.z) + GPUSkinArray[u_xlati0]._GPUSKin_ClipParams.x));
  (u_xlat28.x = ((u_xlat28.x * _GPUSKin_TextureSize.z) + GPUSkinArray[u_xlati0]._GPUSKin_ClipParams.x));
  (u_xlat1 = ((in_TEXCOORD3.xxzz * vec4(3.0, 3.0, 3.0, 3.0)) + u_xlat28.xxxx));
  (u_xlat2 = ((in_TEXCOORD4.xxzz * vec4(3.0, 3.0, 3.0, 3.0)) + u_xlat28.xxxx));
  (u_xlat3 = (u_xlat1 + vec4(1.0, 2.0, 1.0, 2.0)));
  (u_xlat16_4.xy = (vec2(1.0, 1.0) / vec2(_GPUSKin_TextureSize.xy)));
  (u_xlat5 = (u_xlat3 * u_xlat16_4.xxxx));
  (u_xlat5 = floor(u_xlat5));
  (u_xlat3 = (((-u_xlat5) * _GPUSKin_TextureSize.xxxx) + u_xlat3));
  (u_xlat5 = (u_xlat5 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat5 = (u_xlat16_4.yyyy * u_xlat5));
  (u_xlat3 = (u_xlat3 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat3 = (u_xlat16_4.xxxx * u_xlat3.xzyw));
  (u_xlat6.xz = u_xlat3.yw);
  (u_xlat6.yw = u_xlat5.zw);
  (u_xlat3.yw = u_xlat5.xy);
  (u_xlat5 = textureLod(_GPUSKin_Matrix, u_xlat6.xy, 0.0));
  (u_xlat6 = textureLod(_GPUSKin_Matrix, u_xlat6.zw, 0.0));
  (u_xlat7 = ((in_TEXCOORD3.xxzz * vec4(3.0, 3.0, 3.0, 3.0)) + u_xlat14.xxxx));
  (u_xlat8 = ((in_TEXCOORD4.xxzz * vec4(3.0, 3.0, 3.0, 3.0)) + u_xlat14.xxxx));
  (u_xlat9 = (u_xlat7 + vec4(1.0, 2.0, 1.0, 2.0)));
  (u_xlat10 = (u_xlat16_4.xxxx * u_xlat9));
  (u_xlat10 = floor(u_xlat10));
  (u_xlat9 = (((-u_xlat10) * _GPUSKin_TextureSize.xxxx) + u_xlat9));
  (u_xlat10 = (u_xlat10 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat10 = (u_xlat16_4.yyyy * u_xlat10));
  (u_xlat9 = (u_xlat9 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat9 = (u_xlat16_4.xxxx * u_xlat9.xzyw));
  (u_xlat11.xz = u_xlat9.yw);
  (u_xlat11.yw = u_xlat10.zw);
  (u_xlat9.yw = u_xlat10.xy);
  (u_xlat10 = textureLod(_GPUSKin_Matrix, u_xlat11.xy, 0.0));
  (u_xlat11 = textureLod(_GPUSKin_Matrix, u_xlat11.zw, 0.0));
  (u_xlat5 = (u_xlat5 + (-u_xlat10)));
  (u_xlat14.x = fract(GPUSkinArray[u_xlati0]._GPUSKin_ClipParams.y));
  (u_xlat5 = ((u_xlat14.xxxx * u_xlat5) + u_xlat10));
  (u_xlat5.y = dot(u_xlat5, in_POSITION0));
  (u_xlat6 = (u_xlat6 + (-u_xlat11)));
  (u_xlat6 = ((u_xlat14.xxxx * u_xlat6) + u_xlat11));
  (u_xlat5.z = dot(u_xlat6, in_POSITION0));
  (u_xlat28.xy = (u_xlat1.yw * u_xlat16_4.xx));
  (u_xlat28.xy = floor(u_xlat28.xy));
  (u_xlat1.xy = (((-u_xlat28.xy) * _GPUSKin_TextureSize.xx) + u_xlat1.yw));
  (u_xlat28.xy = (u_xlat28.xy + vec2(0.5, 0.5)));
  (u_xlat6.zw = (u_xlat16_4.yy * u_xlat28.xy));
  (u_xlat28.xy = (u_xlat1.xy + vec2(0.5, 0.5)));
  (u_xlat6.xy = (u_xlat16_4.xx * u_xlat28.xy));
  (u_xlat1 = textureLod(_GPUSKin_Matrix, u_xlat6.yw, 0.0));
  (u_xlat6 = textureLod(_GPUSKin_Matrix, u_xlat6.xz, 0.0));
  (u_xlat28.xy = (u_xlat16_4.xx * u_xlat7.yw));
  (u_xlat28.xy = floor(u_xlat28.xy));
  (u_xlat7.xy = (((-u_xlat28.xy) * _GPUSKin_TextureSize.xx) + u_xlat7.yw));
  (u_xlat28.xy = (u_xlat28.xy + vec2(0.5, 0.5)));
  (u_xlat10.zw = (u_xlat16_4.yy * u_xlat28.xy));
  (u_xlat28.xy = (u_xlat7.xy + vec2(0.5, 0.5)));
  (u_xlat10.xy = (u_xlat16_4.xx * u_xlat28.xy));
  (u_xlat7 = textureLod(_GPUSKin_Matrix, u_xlat10.yw, 0.0));
  (u_xlat10 = textureLod(_GPUSKin_Matrix, u_xlat10.xz, 0.0));
  (u_xlat1 = (u_xlat1 + (-u_xlat7)));
  (u_xlat1 = ((u_xlat14.xxxx * u_xlat1) + u_xlat7));
  (u_xlat5.x = dot(u_xlat1, in_POSITION0));
  (u_xlat1.xyz = (u_xlat5.xyz * in_TEXCOORD3.www));
  (u_xlat5 = textureLod(_GPUSKin_Matrix, u_xlat3.xy, 0.0));
  (u_xlat3 = textureLod(_GPUSKin_Matrix, u_xlat3.zw, 0.0));
  (u_xlat7 = textureLod(_GPUSKin_Matrix, u_xlat9.xy, 0.0));
  (u_xlat9 = textureLod(_GPUSKin_Matrix, u_xlat9.zw, 0.0));
  (u_xlat5 = (u_xlat5 + (-u_xlat7)));
  (u_xlat5 = ((u_xlat14.xxxx * u_xlat5) + u_xlat7));
  (u_xlat5.y = dot(u_xlat5, in_POSITION0));
  (u_xlat3 = (u_xlat3 + (-u_xlat9)));
  (u_xlat3 = ((u_xlat14.xxxx * u_xlat3) + u_xlat9));
  (u_xlat5.z = dot(u_xlat3, in_POSITION0));
  (u_xlat3 = (u_xlat6 + (-u_xlat10)));
  (u_xlat3 = ((u_xlat14.xxxx * u_xlat3) + u_xlat10));
  (u_xlat5.x = dot(u_xlat3, in_POSITION0));
  (u_xlat1.xyz = ((u_xlat5.xyz * in_TEXCOORD3.yyy) + u_xlat1.xyz));
  (u_xlat3 = (u_xlat2 + vec4(1.0, 2.0, 1.0, 2.0)));
  (u_xlat5 = (u_xlat16_4.xxxx * u_xlat3));
  (u_xlat5 = floor(u_xlat5));
  (u_xlat3 = (((-u_xlat5) * _GPUSKin_TextureSize.xxxx) + u_xlat3));
  (u_xlat5 = (u_xlat5 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat5 = (u_xlat16_4.yyyy * u_xlat5));
  (u_xlat3 = (u_xlat3 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat3 = (u_xlat16_4.xxxx * u_xlat3.zxwy));
  (u_xlat6.xz = u_xlat3.yw);
  (u_xlat6.yw = u_xlat5.xy);
  (u_xlat3.yw = u_xlat5.zw);
  (u_xlat5 = textureLod(_GPUSKin_Matrix, u_xlat6.xy, 0.0));
  (u_xlat6 = textureLod(_GPUSKin_Matrix, u_xlat6.zw, 0.0));
  (u_xlat7 = (u_xlat8 + vec4(1.0, 2.0, 1.0, 2.0)));
  (u_xlat9 = (u_xlat16_4.xxxx * u_xlat7));
  (u_xlat9 = floor(u_xlat9));
  (u_xlat7 = (((-u_xlat9) * _GPUSKin_TextureSize.xxxx) + u_xlat7));
  (u_xlat9 = (u_xlat9 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat9 = (u_xlat16_4.yyyy * u_xlat9));
  (u_xlat7 = (u_xlat7 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat7 = (u_xlat16_4.xxxx * u_xlat7.zxwy));
  (u_xlat10.xz = u_xlat7.yw);
  (u_xlat10.yw = u_xlat9.xy);
  (u_xlat7.yw = u_xlat9.zw);
  (u_xlat9 = textureLod(_GPUSKin_Matrix, u_xlat10.xy, 0.0));
  (u_xlat10 = textureLod(_GPUSKin_Matrix, u_xlat10.zw, 0.0));
  (u_xlat5 = (u_xlat5 + (-u_xlat9)));
  (u_xlat5 = ((u_xlat14.xxxx * u_xlat5) + u_xlat9));
  (u_xlat5.y = dot(u_xlat5, in_POSITION0));
  (u_xlat6 = (u_xlat6 + (-u_xlat10)));
  (u_xlat6 = ((u_xlat14.xxxx * u_xlat6) + u_xlat10));
  (u_xlat5.z = dot(u_xlat6, in_POSITION0));
  (u_xlat28.xy = (u_xlat2.yw * u_xlat16_4.xx));
  (u_xlat28.xy = floor(u_xlat28.xy));
  (u_xlat2.xy = (((-u_xlat28.xy) * _GPUSKin_TextureSize.xx) + u_xlat2.yw));
  (u_xlat28.xy = (u_xlat28.xy + vec2(0.5, 0.5)));
  (u_xlat6.zw = (u_xlat16_4.yy * u_xlat28.xy));
  (u_xlat28.xy = (u_xlat2.xy + vec2(0.5, 0.5)));
  (u_xlat6.xy = (u_xlat16_4.xx * u_xlat28.xy));
  (u_xlat2 = textureLod(_GPUSKin_Matrix, u_xlat6.xz, 0.0));
  (u_xlat6 = textureLod(_GPUSKin_Matrix, u_xlat6.yw, 0.0));
  (u_xlat28.xy = (u_xlat16_4.xx * u_xlat8.yw));
  (u_xlat28.xy = floor(u_xlat28.xy));
  (u_xlat8.xy = (((-u_xlat28.xy) * _GPUSKin_TextureSize.xx) + u_xlat8.yw));
  (u_xlat28.xy = (u_xlat28.xy + vec2(0.5, 0.5)));
  (u_xlat9.zw = (u_xlat16_4.yy * u_xlat28.xy));
  (u_xlat28.xy = (u_xlat8.xy + vec2(0.5, 0.5)));
  (u_xlat9.xy = (u_xlat16_4.xx * u_xlat28.xy));
  (u_xlat4 = textureLod(_GPUSKin_Matrix, u_xlat9.xz, 0.0));
  (u_xlat8 = textureLod(_GPUSKin_Matrix, u_xlat9.yw, 0.0));
  (u_xlat2 = (u_xlat2 + (-u_xlat4)));
  (u_xlat2 = ((u_xlat14.xxxx * u_xlat2) + u_xlat4));
  (u_xlat5.x = dot(u_xlat2, in_POSITION0));
  (u_xlat1.xyz = ((u_xlat5.xyz * in_TEXCOORD4.yyy) + u_xlat1.xyz));
  (u_xlat2 = textureLod(_GPUSKin_Matrix, u_xlat3.xy, 0.0));
  (u_xlat3 = textureLod(_GPUSKin_Matrix, u_xlat3.zw, 0.0));
  (u_xlat4 = textureLod(_GPUSKin_Matrix, u_xlat7.xy, 0.0));
  (u_xlat5 = textureLod(_GPUSKin_Matrix, u_xlat7.zw, 0.0));
  (u_xlat2 = (u_xlat2 + (-u_xlat4)));
  (u_xlat2 = ((u_xlat14.xxxx * u_xlat2) + u_xlat4));
  (u_xlat2.y = dot(u_xlat2, in_POSITION0));
  (u_xlat3 = (u_xlat3 + (-u_xlat5)));
  (u_xlat3 = ((u_xlat14.xxxx * u_xlat3) + u_xlat5));
  (u_xlat2.z = dot(u_xlat3, in_POSITION0));
  (u_xlat3 = (u_xlat6 + (-u_xlat8)));
  (u_xlat3 = ((u_xlat14.xxxx * u_xlat3) + u_xlat8));
  (u_xlat2.x = dot(u_xlat3, in_POSITION0));
  (u_xlat14.xyz = ((u_xlat2.xyz * in_TEXCOORD4.www) + u_xlat1.xyz));
  (u_xlat28.x = (u_xlat14.y + _VertexOffsetY));
  (u_xlati1 = int((u_xlati0 << 3)));
  (u_xlati0 = (u_xlati0 * 7));
  (u_xlat15.xyz = (u_xlat28.xxx * unity_Builtins0Array[(u_xlati1 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[1].xyz));
  (u_xlat15.xyz = ((unity_Builtins0Array[(u_xlati1 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[0].xyz * u_xlat14.xxx) + u_xlat15.xyz));
  (u_xlat14.xyz = ((unity_Builtins0Array[(u_xlati1 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[2].xyz * u_xlat14.zzz) + u_xlat15.xyz));
  (u_xlat14.xyz = (u_xlat14.xyz + unity_Builtins0Array[(u_xlati1 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[3].xyz));
  (u_xlat2 = (u_xlat14.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat2 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat14.xxxx) + u_xlat2));
  (u_xlat2 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat14.zzzz) + u_xlat2));
  (vs_TEXCOORD2.xyz = u_xlat14.xyz);
  (gl_Position = (u_xlat2 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (vs_TEXCOORD0.xy = in_TEXCOORD0.xy);
  (u_xlat2.x = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati1 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[0].xyz));
  (u_xlat2.y = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati1 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[1].xyz));
  (u_xlat2.z = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati1 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[2].xyz));
  (u_xlat14.x = dot(u_xlat2.xyz, u_xlat2.xyz));
  (u_xlat14.x = max(u_xlat14.x, 0.0));
  (u_xlat14.x = inversesqrt(u_xlat14.x));
  (u_xlat1.xyz = (u_xlat14.xxx * u_xlat2.xyz));
  (vs_TEXCOORD1.xyz = u_xlat1.xyz);
  (vs_TEXCOORD2.w = 0.0);
  (u_xlat16_12.x = (u_xlat1.y * u_xlat1.y));
  (u_xlat16_12.x = ((u_xlat1.x * u_xlat1.x) + (-u_xlat16_12.x)));
  (u_xlat16_2 = (u_xlat1.yzzx * u_xlat1.xyzz));
  (u_xlat16_13.x = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHBrArray, u_xlat16_2));
  (u_xlat16_13.y = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHBgArray, u_xlat16_2));
  (u_xlat16_13.z = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHBbArray, u_xlat16_2));
  (u_xlat16_12.xyz = ((unity_Builtins2Array[(u_xlati0 / 7)].unity_SHCArray.xyz * u_xlat16_12.xxx) + u_xlat16_13.xyz));
  (u_xlat1.w = 1.0);
  (u_xlat16_13.x = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHArArray, u_xlat1));
  (u_xlat16_13.y = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHAgArray, u_xlat1));
  (u_xlat16_13.z = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHAbArray, u_xlat1));
  (u_xlat16_12.xyz = (u_xlat16_12.xyz + u_xlat16_13.xyz));
  (vs_TEXCOORD3.xyz = max(u_xlat16_12.xyz, vec3(0.0, 0.0, 0.0)));
  (vs_TEXCOORD5.xyz = vec3(0.0, 0.0, 0.0));
  (vs_TEXCOORD6.xyz = vec3(0.0, 0.0, 0.0));
  (vs_SV_InstanceID0 = uint(gl_InstanceID));
  return ;
}
