#version 450
uniform vec4 _MainLightPosition;
uniform vec3 _WorldSpaceCameraPos;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform int unity_BaseInstanceID;
uniform float _FogStart;
uniform float _FogEnd;
uniform float _FogGlobalDensity;
uniform float _FogFallOff;
uniform float _FogHeight;
uniform float _FogStartDis;
uniform float _FogGradientDis;
struct unity_Builtins0Array_Type {
  vec4 hlslcc_mtx4x4unity_ObjectToWorldArray[4];
  vec4 hlslcc_mtx4x4unity_WorldToObjectArray[4];
};
layout(std140, binding = 1) uniform UnityInstancing_PerDraw0{
  unity_Builtins0Array_Type unity_Builtins0Array[128];
};
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _CustomLightDir;
  vec4 _GPUSKin_TextureSize;
  vec4 _ShadowColor;
  float _UseCustomLightDir;
  float _GroundHeight;
  float _ShadowFalloff;
  float _Alpha;
};
struct GPUSkinArray_Type {
  vec4 _GPUSKin_ClipParams;
};
layout(std140, binding = 2) uniform UnityInstancing_GPUSkin{
  GPUSkinArray_Type GPUSkinArray[128];
};
layout(location = 0) uniform sampler2D _GPUSKin_Matrix;
in vec4 in_POSITION0;
in vec4 in_TEXCOORD3;
in vec4 in_TEXCOORD4;
out vec4 vs_COLOR0;
out float vs_TEXCOORD0;
flat out uint vs_SV_InstanceID0;
vec4 u_xlat0;
int u_xlati0;
vec4 u_xlat1;
vec4 u_xlat2;
vec4 u_xlat3;
vec4 u_xlat4;
vec2 u_xlat16_4;
vec4 u_xlat5;
vec4 u_xlat6;
vec4 u_xlat7;
vec4 u_xlat8;
vec4 u_xlat9;
vec4 u_xlat10;
vec4 u_xlat11;
vec3 u_xlat16_12;
vec3 u_xlat13;
vec2 u_xlat26;
float u_xlat39;
void main(){
  (u_xlati0 = (gl_InstanceID + unity_BaseInstanceID));
  (u_xlat13.x = floor(GPUSkinArray[u_xlati0]._GPUSKin_ClipParams.y));
  (u_xlat26.x = (u_xlat13.x + 1.0));
  (u_xlat13.x = ((u_xlat13.x * _GPUSKin_TextureSize.z) + GPUSkinArray[u_xlati0]._GPUSKin_ClipParams.x));
  (u_xlat26.x = ((u_xlat26.x * _GPUSKin_TextureSize.z) + GPUSkinArray[u_xlati0]._GPUSKin_ClipParams.x));
  (u_xlat1 = ((in_TEXCOORD3.xxzz * vec4(3.0, 3.0, 3.0, 3.0)) + u_xlat26.xxxx));
  (u_xlat2 = ((in_TEXCOORD4.xxzz * vec4(3.0, 3.0, 3.0, 3.0)) + u_xlat26.xxxx));
  (u_xlat3 = (u_xlat1 + vec4(1.0, 2.0, 1.0, 2.0)));
  (u_xlat16_4.xy = (vec2(1.0, 1.0) / vec2(_GPUSKin_TextureSize.xy)));
  (u_xlat5 = (u_xlat3 * u_xlat16_4.xxxx));
  (u_xlat5 = floor(u_xlat5));
  (u_xlat3 = (((-u_xlat5) * _GPUSKin_TextureSize.xxxx) + u_xlat3));
  (u_xlat5 = (u_xlat5 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat5 = (u_xlat16_4.yyyy * u_xlat5));
  (u_xlat3 = (u_xlat3 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat3 = (u_xlat16_4.xxxx * u_xlat3.xzyw));
  (u_xlat6.xz = u_xlat3.yw);
  (u_xlat6.yw = u_xlat5.zw);
  (u_xlat3.yw = u_xlat5.xy);
  (u_xlat5 = textureLod(_GPUSKin_Matrix, u_xlat6.xy, 0.0));
  (u_xlat6 = textureLod(_GPUSKin_Matrix, u_xlat6.zw, 0.0));
  (u_xlat7 = ((in_TEXCOORD3.xxzz * vec4(3.0, 3.0, 3.0, 3.0)) + u_xlat13.xxxx));
  (u_xlat8 = ((in_TEXCOORD4.xxzz * vec4(3.0, 3.0, 3.0, 3.0)) + u_xlat13.xxxx));
  (u_xlat9 = (u_xlat7 + vec4(1.0, 2.0, 1.0, 2.0)));
  (u_xlat10 = (u_xlat16_4.xxxx * u_xlat9));
  (u_xlat10 = floor(u_xlat10));
  (u_xlat9 = (((-u_xlat10) * _GPUSKin_TextureSize.xxxx) + u_xlat9));
  (u_xlat10 = (u_xlat10 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat10 = (u_xlat16_4.yyyy * u_xlat10));
  (u_xlat9 = (u_xlat9 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat9 = (u_xlat16_4.xxxx * u_xlat9.xzyw));
  (u_xlat11.xz = u_xlat9.yw);
  (u_xlat11.yw = u_xlat10.zw);
  (u_xlat9.yw = u_xlat10.xy);
  (u_xlat10 = textureLod(_GPUSKin_Matrix, u_xlat11.xy, 0.0));
  (u_xlat11 = textureLod(_GPUSKin_Matrix, u_xlat11.zw, 0.0));
  (u_xlat5 = (u_xlat5 + (-u_xlat10)));
  (u_xlat13.x = fract(GPUSkinArray[u_xlati0]._GPUSKin_ClipParams.y));
  (u_xlati0 = int((u_xlati0 << 3)));
  (u_xlat5 = ((u_xlat13.xxxx * u_xlat5) + u_xlat10));
  (u_xlat5.y = dot(u_xlat5, in_POSITION0));
  (u_xlat6 = (u_xlat6 + (-u_xlat11)));
  (u_xlat6 = ((u_xlat13.xxxx * u_xlat6) + u_xlat11));
  (u_xlat5.z = dot(u_xlat6, in_POSITION0));
  (u_xlat26.xy = (u_xlat1.yw * u_xlat16_4.xx));
  (u_xlat26.xy = floor(u_xlat26.xy));
  (u_xlat1.xy = (((-u_xlat26.xy) * _GPUSKin_TextureSize.xx) + u_xlat1.yw));
  (u_xlat26.xy = (u_xlat26.xy + vec2(0.5, 0.5)));
  (u_xlat6.zw = (u_xlat16_4.yy * u_xlat26.xy));
  (u_xlat26.xy = (u_xlat1.xy + vec2(0.5, 0.5)));
  (u_xlat6.xy = (u_xlat16_4.xx * u_xlat26.xy));
  (u_xlat1 = textureLod(_GPUSKin_Matrix, u_xlat6.yw, 0.0));
  (u_xlat6 = textureLod(_GPUSKin_Matrix, u_xlat6.xz, 0.0));
  (u_xlat26.xy = (u_xlat16_4.xx * u_xlat7.yw));
  (u_xlat26.xy = floor(u_xlat26.xy));
  (u_xlat7.xy = (((-u_xlat26.xy) * _GPUSKin_TextureSize.xx) + u_xlat7.yw));
  (u_xlat26.xy = (u_xlat26.xy + vec2(0.5, 0.5)));
  (u_xlat10.zw = (u_xlat16_4.yy * u_xlat26.xy));
  (u_xlat26.xy = (u_xlat7.xy + vec2(0.5, 0.5)));
  (u_xlat10.xy = (u_xlat16_4.xx * u_xlat26.xy));
  (u_xlat7 = textureLod(_GPUSKin_Matrix, u_xlat10.yw, 0.0));
  (u_xlat10 = textureLod(_GPUSKin_Matrix, u_xlat10.xz, 0.0));
  (u_xlat1 = (u_xlat1 + (-u_xlat7)));
  (u_xlat1 = ((u_xlat13.xxxx * u_xlat1) + u_xlat7));
  (u_xlat5.x = dot(u_xlat1, in_POSITION0));
  (u_xlat1.xyz = (u_xlat5.xyz * in_TEXCOORD3.www));
  (u_xlat5 = textureLod(_GPUSKin_Matrix, u_xlat3.xy, 0.0));
  (u_xlat3 = textureLod(_GPUSKin_Matrix, u_xlat3.zw, 0.0));
  (u_xlat7 = textureLod(_GPUSKin_Matrix, u_xlat9.xy, 0.0));
  (u_xlat9 = textureLod(_GPUSKin_Matrix, u_xlat9.zw, 0.0));
  (u_xlat5 = (u_xlat5 + (-u_xlat7)));
  (u_xlat5 = ((u_xlat13.xxxx * u_xlat5) + u_xlat7));
  (u_xlat5.y = dot(u_xlat5, in_POSITION0));
  (u_xlat3 = (u_xlat3 + (-u_xlat9)));
  (u_xlat3 = ((u_xlat13.xxxx * u_xlat3) + u_xlat9));
  (u_xlat5.z = dot(u_xlat3, in_POSITION0));
  (u_xlat3 = (u_xlat6 + (-u_xlat10)));
  (u_xlat3 = ((u_xlat13.xxxx * u_xlat3) + u_xlat10));
  (u_xlat5.x = dot(u_xlat3, in_POSITION0));
  (u_xlat1.xyz = ((u_xlat5.xyz * in_TEXCOORD3.yyy) + u_xlat1.xyz));
  (u_xlat3 = (u_xlat2 + vec4(1.0, 2.0, 1.0, 2.0)));
  (u_xlat5 = (u_xlat16_4.xxxx * u_xlat3));
  (u_xlat5 = floor(u_xlat5));
  (u_xlat3 = (((-u_xlat5) * _GPUSKin_TextureSize.xxxx) + u_xlat3));
  (u_xlat5 = (u_xlat5 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat5 = (u_xlat16_4.yyyy * u_xlat5));
  (u_xlat3 = (u_xlat3 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat3 = (u_xlat16_4.xxxx * u_xlat3.zxwy));
  (u_xlat6.xz = u_xlat3.yw);
  (u_xlat6.yw = u_xlat5.xy);
  (u_xlat3.yw = u_xlat5.zw);
  (u_xlat5 = textureLod(_GPUSKin_Matrix, u_xlat6.xy, 0.0));
  (u_xlat6 = textureLod(_GPUSKin_Matrix, u_xlat6.zw, 0.0));
  (u_xlat7 = (u_xlat8 + vec4(1.0, 2.0, 1.0, 2.0)));
  (u_xlat9 = (u_xlat16_4.xxxx * u_xlat7));
  (u_xlat9 = floor(u_xlat9));
  (u_xlat7 = (((-u_xlat9) * _GPUSKin_TextureSize.xxxx) + u_xlat7));
  (u_xlat9 = (u_xlat9 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat9 = (u_xlat16_4.yyyy * u_xlat9));
  (u_xlat7 = (u_xlat7 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat7 = (u_xlat16_4.xxxx * u_xlat7.zxwy));
  (u_xlat10.xz = u_xlat7.yw);
  (u_xlat10.yw = u_xlat9.xy);
  (u_xlat7.yw = u_xlat9.zw);
  (u_xlat9 = textureLod(_GPUSKin_Matrix, u_xlat10.xy, 0.0));
  (u_xlat10 = textureLod(_GPUSKin_Matrix, u_xlat10.zw, 0.0));
  (u_xlat5 = (u_xlat5 + (-u_xlat9)));
  (u_xlat5 = ((u_xlat13.xxxx * u_xlat5) + u_xlat9));
  (u_xlat5.y = dot(u_xlat5, in_POSITION0));
  (u_xlat6 = (u_xlat6 + (-u_xlat10)));
  (u_xlat6 = ((u_xlat13.xxxx * u_xlat6) + u_xlat10));
  (u_xlat5.z = dot(u_xlat6, in_POSITION0));
  (u_xlat26.xy = (u_xlat2.yw * u_xlat16_4.xx));
  (u_xlat26.xy = floor(u_xlat26.xy));
  (u_xlat2.xy = (((-u_xlat26.xy) * _GPUSKin_TextureSize.xx) + u_xlat2.yw));
  (u_xlat26.xy = (u_xlat26.xy + vec2(0.5, 0.5)));
  (u_xlat6.zw = (u_xlat16_4.yy * u_xlat26.xy));
  (u_xlat26.xy = (u_xlat2.xy + vec2(0.5, 0.5)));
  (u_xlat6.xy = (u_xlat16_4.xx * u_xlat26.xy));
  (u_xlat2 = textureLod(_GPUSKin_Matrix, u_xlat6.xz, 0.0));
  (u_xlat6 = textureLod(_GPUSKin_Matrix, u_xlat6.yw, 0.0));
  (u_xlat26.xy = (u_xlat16_4.xx * u_xlat8.yw));
  (u_xlat26.xy = floor(u_xlat26.xy));
  (u_xlat8.xy = (((-u_xlat26.xy) * _GPUSKin_TextureSize.xx) + u_xlat8.yw));
  (u_xlat26.xy = (u_xlat26.xy + vec2(0.5, 0.5)));
  (u_xlat9.zw = (u_xlat16_4.yy * u_xlat26.xy));
  (u_xlat26.xy = (u_xlat8.xy + vec2(0.5, 0.5)));
  (u_xlat9.xy = (u_xlat16_4.xx * u_xlat26.xy));
  (u_xlat4 = textureLod(_GPUSKin_Matrix, u_xlat9.xz, 0.0));
  (u_xlat8 = textureLod(_GPUSKin_Matrix, u_xlat9.yw, 0.0));
  (u_xlat2 = (u_xlat2 + (-u_xlat4)));
  (u_xlat2 = ((u_xlat13.xxxx * u_xlat2) + u_xlat4));
  (u_xlat5.x = dot(u_xlat2, in_POSITION0));
  (u_xlat1.xyz = ((u_xlat5.xyz * in_TEXCOORD4.yyy) + u_xlat1.xyz));
  (u_xlat2 = textureLod(_GPUSKin_Matrix, u_xlat3.xy, 0.0));
  (u_xlat3 = textureLod(_GPUSKin_Matrix, u_xlat3.zw, 0.0));
  (u_xlat4 = textureLod(_GPUSKin_Matrix, u_xlat7.xy, 0.0));
  (u_xlat5 = textureLod(_GPUSKin_Matrix, u_xlat7.zw, 0.0));
  (u_xlat2 = (u_xlat2 + (-u_xlat4)));
  (u_xlat2 = ((u_xlat13.xxxx * u_xlat2) + u_xlat4));
  (u_xlat2.y = dot(u_xlat2, in_POSITION0));
  (u_xlat3 = (u_xlat3 + (-u_xlat5)));
  (u_xlat3 = ((u_xlat13.xxxx * u_xlat3) + u_xlat5));
  (u_xlat2.z = dot(u_xlat3, in_POSITION0));
  (u_xlat3 = (u_xlat6 + (-u_xlat8)));
  (u_xlat3 = ((u_xlat13.xxxx * u_xlat3) + u_xlat8));
  (u_xlat2.x = dot(u_xlat3, in_POSITION0));
  (u_xlat13.xyz = ((u_xlat2.xyz * in_TEXCOORD4.www) + u_xlat1.xyz));
  (u_xlat1.xyz = (u_xlat13.yyy * unity_Builtins0Array[(u_xlati0 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[1].xyz));
  (u_xlat1.xyz = ((unity_Builtins0Array[(u_xlati0 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[0].xyz * u_xlat13.xxx) + u_xlat1.xyz));
  (u_xlat13.xyz = ((unity_Builtins0Array[(u_xlati0 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[2].xyz * u_xlat13.zzz) + u_xlat1.xyz));
  (u_xlat0.xyz = (u_xlat13.xyz + unity_Builtins0Array[(u_xlati0 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[3].xyz));
  (u_xlat39 = (u_xlat0.y + (-_GroundHeight)));
  (u_xlat39 = max(u_xlat39, 0.0));
  (u_xlat16_12.xyz = ((-_MainLightPosition.xyz) + _CustomLightDir.xyz));
  (u_xlat16_12.xyz = ((vec3(_UseCustomLightDir) * u_xlat16_12.xyz) + _MainLightPosition.xyz));
  (u_xlat1.xy = (vec2(u_xlat39) * u_xlat16_12.xz));
  (u_xlat39 = (1.0 / float(u_xlat16_12.y)));
  (u_xlat1.xy = (((-u_xlat1.xy) * vec2(u_xlat39)) + u_xlat0.xz));
  (u_xlat39 = min(u_xlat0.y, _GroundHeight));
  (u_xlat2 = (vec4(u_xlat39) * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat2 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat1.xxxx) + u_xlat2));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat1.yyyy) + u_xlat2));
  (gl_Position = (u_xlat1 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (vs_COLOR0.w = (_ShadowColor.w * 0.89999998));
  (vs_COLOR0.xyz = _ShadowColor.xyz);
  (u_xlat0.w = (u_xlat0.y + (-_WorldSpaceCameraPos.y)));
  (u_xlat0.xyz = ((-u_xlat0.xyz) + _WorldSpaceCameraPos.xyz));
  (u_xlat0.x = dot(u_xlat0.xyz, u_xlat0.xyz));
  (u_xlat0.x = max(u_xlat0.x, 6.1035156e-05));
  (u_xlat0.x = sqrt(u_xlat0.x));
  (u_xlat0.xy = (u_xlat0.xw + (-vec2(_FogStartDis, _FogHeight))));
  (u_xlat0.x = (u_xlat0.x / _FogGradientDis));
  (u_xlat0.x = max(u_xlat0.x, 0.0));
  (u_xlat26.x = (_FogFallOff * 0.0099999998));
  (u_xlat13.x = (u_xlat0.y * u_xlat26.x));
  (u_xlat26.x = exp2((-u_xlat13.x)));
  (u_xlat39 = ((-u_xlat26.x) + 1.0));
  (u_xlat26.x = (u_xlat26.x * _FogGlobalDensity));
  (u_xlat13.x = (u_xlat39 / u_xlat13.x));
  (u_xlat13.x = (u_xlat26.x * u_xlat13.x));
  (u_xlat0.x = ((u_xlat13.x * u_xlat0.x) + (-_FogStart)));
  (u_xlat13.x = ((-_FogStart) + _FogEnd));
  (u_xlat13.x = (1.0 / u_xlat13.x));
  (u_xlat0.x = (u_xlat13.x * u_xlat0.x));
  (u_xlat0.x = clamp(u_xlat0.x, 0.0, 1.0));
  (u_xlat13.x = ((u_xlat0.x * -2.0) + 3.0));
  (u_xlat0.x = (u_xlat0.x * u_xlat0.x));
  (vs_TEXCOORD0 = (u_xlat0.x * u_xlat13.x));
  (vs_SV_InstanceID0 = uint(gl_InstanceID));
  return ;
}
