#version 450
uniform vec4 _TimeParameters;
uniform vec4 _ProjectionParams;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform int unity_BaseInstanceID;
uniform vec4 XYZVectorWPower;
uniform float _HeightMax;
uniform float _HeightMin;
uniform float _WindFrequency;
uniform float _WindPower;
struct unity_Builtins0Array_Type {
  vec4 hlslcc_mtx4x4unity_ObjectToWorldArray[4];
  vec4 hlslcc_mtx4x4unity_WorldToObjectArray[4];
};
layout(std140, binding = 1) uniform UnityInstancing_PerDraw0{
  unity_Builtins0Array_Type unity_Builtins0Array[128];
};
in vec4 in_POSITION0;
in vec4 in_TEXCOORD0;
out vec4 vs_TEXCOORD0;
out vec2 vs_TEXCOORD1;
out vec4 vs_TEXCOORD4;
flat out uint vs_SV_InstanceID0;
vec4 u_xlat0;
vec4 u_xlat1;
vec3 u_xlat2;
vec3 u_xlat3;
bool u_xlatb4;
int u_xlati7;
float u_xlat9;
float u_xlat10;
void main(){
  (u_xlat0.x = ((-_HeightMin) + _HeightMax));
  (u_xlat0.x = (1.0 / u_xlat0.x));
  (u_xlat3.x = (in_POSITION0.y + (-_HeightMin)));
  (u_xlat0.x = (u_xlat0.x * u_xlat3.x));
  (u_xlat0.x = clamp(u_xlat0.x, 0.0, 1.0));
  (u_xlat3.x = ((u_xlat0.x * -2.0) + 3.0));
  (u_xlat0.x = (u_xlat0.x * u_xlat0.x));
  (u_xlat0.x = (u_xlat0.x * u_xlat3.x));
  (u_xlat3.x = dot(XYZVectorWPower.xyz, XYZVectorWPower.xyz));
  (u_xlat3.x = inversesqrt(u_xlat3.x));
  (u_xlat3.xyz = (u_xlat3.xxx * XYZVectorWPower.xyz));
  (u_xlat1.x = (_TimeParameters.x * XYZVectorWPower.w));
  (u_xlat1.x = (u_xlat1.x * 0.00031830987));
  (u_xlatb4 = (u_xlat1.x >= (-u_xlat1.x)));
  (u_xlat1.x = fract(abs(u_xlat1.x)));
  (u_xlat1.x = ((u_xlatb4) ? (u_xlat1.x) : ((-u_xlat1.x))));
  (u_xlat1.xy = (u_xlat1.xx * vec2(3141.5928, 6283.1855)));
  (u_xlati7 = (gl_InstanceID + unity_BaseInstanceID));
  (u_xlati7 = int((u_xlati7 << 3)));
  (u_xlat2.xyz = (in_POSITION0.yyy * unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[1].xyz));
  (u_xlat2.xyz = ((unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[0].xyz * in_POSITION0.xxx) + u_xlat2.xyz));
  (u_xlat2.xyz = ((unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[2].xyz * in_POSITION0.zzz) + u_xlat2.xyz));
  (u_xlat2.xyz = (u_xlat2.xyz + unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[3].xyz));
  (u_xlat2.xyz = (((-XYZVectorWPower.xyz) * vec3(100.0, 0.0, 100.0)) + u_xlat2.xyz));
  (u_xlat10 = dot(u_xlat2.xyz, u_xlat2.xyz));
  (u_xlat10 = sqrt(u_xlat10));
  (u_xlat1.x = ((_WindFrequency * u_xlat10) + u_xlat1.x));
  (u_xlat2.x = sin(u_xlat1.x));
  (u_xlat1.x = (u_xlat1.x + u_xlat2.x));
  (u_xlat1.x = (u_xlat1.x + 3.0999999));
  (u_xlat1.x = sin(u_xlat1.x));
  (u_xlat1.x = (u_xlat1.x * u_xlat1.x));
  (u_xlat3.xyz = (u_xlat3.xyz * u_xlat1.xxx));
  (u_xlat1.x = (_WindFrequency * 3.0));
  (u_xlat1.x = ((u_xlat10 * u_xlat1.x) + u_xlat1.y));
  (u_xlat1.x = sin(u_xlat1.x));
  (u_xlat3.xyz = ((u_xlat1.xxx * vec3(0.1, 0.1, 0.1)) + u_xlat3.xyz));
  (u_xlat3.xyz = (u_xlat3.xyz + unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[3].xyz));
  (u_xlat1.xyw = (u_xlat3.yyy * unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[1].xyz));
  (u_xlat1.xyw = ((unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[0].xyz * u_xlat3.xxx) + u_xlat1.xyw));
  (u_xlat3.xyz = ((unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[2].xyz * u_xlat3.zzz) + u_xlat1.xyw));
  (u_xlat3.xyz = (u_xlat3.xyz + unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[3].xyz));
  (u_xlat3.xyz = (u_xlat3.xyz * vec3(vec3(_WindPower, _WindPower, _WindPower))));
  (u_xlat2.xz = in_POSITION0.xz);
  (u_xlat2.y = 0.0);
  (u_xlat1.xyw = ((-u_xlat2.xyz) + in_POSITION0.xyz));
  (u_xlat0.xyz = ((u_xlat3.xyz * u_xlat0.xxx) + u_xlat1.xyw));
  (u_xlat9 = dot(u_xlat0.xyz, u_xlat0.xyz));
  (u_xlat9 = inversesqrt(u_xlat9));
  (u_xlat0.xyz = (vec3(u_xlat9) * u_xlat0.xyz));
  (u_xlat0.xyz = ((u_xlat0.xyz * abs(u_xlat1.yyy)) + u_xlat2.xyz));
  (u_xlat1.xyw = (u_xlat0.yyy * unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[1].xyz));
  (u_xlat0.xyw = ((unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[0].xyz * u_xlat0.xxx) + u_xlat1.xyw));
  (u_xlat0.xyz = ((unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[2].xyz * u_xlat0.zzz) + u_xlat0.xyw));
  (u_xlat0.xyz = (u_xlat0.xyz + unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[3].xyz));
  (u_xlat1 = (u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx) + u_xlat1));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz) + u_xlat1));
  (vs_TEXCOORD0.xyz = u_xlat0.xyz);
  (u_xlat0 = (u_xlat1 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (gl_Position = u_xlat0);
  (vs_TEXCOORD0.w = 0.0);
  (vs_TEXCOORD1.xy = in_TEXCOORD0.xy);
  (u_xlat0.y = (u_xlat0.y * _ProjectionParams.x));
  (u_xlat1.xzw = (u_xlat0.xwy * vec3(0.5, 0.5, 0.5)));
  (vs_TEXCOORD4.zw = u_xlat0.zw);
  (vs_TEXCOORD4.xy = (u_xlat1.zz + u_xlat1.xw));
  (vs_SV_InstanceID0 = uint(gl_InstanceID));
  return ;
}
