#version 450
uniform vec4 _LightColor1;
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _MainTex_Color;
  vec4 _MainTex_ST;
  vec4 _SnowColor;
  vec4 _SnowAlbedo_ST;
  vec4 _SnowNormal_ST;
  vec4 _Snow_Mask_ST;
  float _LightIntensity1;
  float _SnowAmount;
  float _MIn_int;
  float _Float1;
};
layout(location = 0) uniform sampler2D _SnowNormal;
layout(location = 1) uniform sampler2D _Snow_Mask;
layout(location = 2) uniform sampler2D _MainTex;
layout(location = 3) uniform sampler2D _SnowAlbedo;
in vec4 vs_TEXCOORD3;
in vec4 vs_TEXCOORD4;
in vec4 vs_TEXCOORD5;
in vec4 vs_TEXCOORD6;
layout(location = 0) out vec4 SV_Target0;
vec3 u_xlat0;
vec3 u_xlat16_0;
vec3 u_xlat16_1;
vec3 u_xlat2;
vec3 u_xlat16_2;
vec3 u_xlat3;
vec3 u_xlat16_3;
float u_xlat6;
void main(){
  (u_xlat0.xy = ((vs_TEXCOORD3.xy * _SnowNormal_ST.xy) + _SnowNormal_ST.zw));
  (u_xlat16_0.xyz = texture(_SnowNormal, u_xlat0.xy).xyz);
  (u_xlat16_1.xyz = ((u_xlat16_0.xyz * vec3(2.0, 2.0, 2.0)) + vec3(-1.0, -1.0, -1.0)));
  (u_xlat0.x = (vs_TEXCOORD4.y * _SnowAmount));
  (u_xlat0.x = clamp(u_xlat0.x, 0.0, 1.0));
  (u_xlat0.xyz = (u_xlat16_1.xyz + u_xlat0.xxx));
  (u_xlat2.x = vs_TEXCOORD5.y);
  (u_xlat2.y = vs_TEXCOORD6.y);
  (u_xlat2.z = vs_TEXCOORD4.y);
  (u_xlat0.x = dot(u_xlat2.xyz, u_xlat0.xyz));
  (u_xlat0.x = (u_xlat0.x * _SnowAmount));
  (u_xlat0.x = clamp(u_xlat0.x, 0.0, 1.0));
  (u_xlat3.xy = ((vs_TEXCOORD3.xy * _Snow_Mask_ST.xy) + _Snow_Mask_ST.zw));
  (u_xlat16_3.x = texture(_Snow_Mask, u_xlat3.xy).x);
  (u_xlat3.x = (u_xlat16_3.x + (-_MIn_int)));
  (u_xlat6 = ((-_MIn_int) + _Float1));
  (u_xlat6 = (1.0 / float(u_xlat6)));
  (u_xlat3.x = (u_xlat6 * u_xlat3.x));
  (u_xlat3.x = clamp(u_xlat3.x, 0.0, 1.0));
  (u_xlat0.x = (u_xlat3.x * u_xlat0.x));
  (u_xlat3.xy = ((vs_TEXCOORD3.xy * _SnowAlbedo_ST.xy) + _SnowAlbedo_ST.zw));
  (u_xlat16_3.xyz = texture(_SnowAlbedo, u_xlat3.xy).xyz);
  (u_xlat2.xy = ((vs_TEXCOORD3.xy * _MainTex_ST.xy) + _MainTex_ST.zw));
  (u_xlat16_2.xyz = texture(_MainTex, u_xlat2.xy).xyz);
  (u_xlat2.xyz = (u_xlat16_2.xyz * _MainTex_Color.xyz));
  (u_xlat3.xyz = ((_SnowColor.xyz * u_xlat16_3.xyz) + (-u_xlat2.xyz)));
  (u_xlat0.xyz = ((u_xlat0.xxx * u_xlat3.xyz) + u_xlat2.xyz));
  (u_xlat16_1.xyz = (_LightColor1.xyz * vec3(_LightIntensity1)));
  (SV_Target0.xyz = (u_xlat0.xyz * u_xlat16_1.xyz));
  (SV_Target0.w = 1.0);
  return ;
}
