#version 450
uniform vec3 _WorldSpaceCameraPos;
uniform vec4 _FogColor;
uniform float _FogStart;
uniform float _FogEnd;
uniform float _FogGlobalDensity;
uniform float _FogFallOff;
uniform float _FogHeight;
uniform float _FogStartDis;
uniform float _FogGradientDis;
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _Color;
  vec4 _VertexOffset;
  float _AlphaIsR;
  float _Intensity;
  float _Tiling;
};
layout(location = 0) uniform sampler2D _MainTex;
in vec2 vs_TEXCOORD0;
in vec3 vs_TEXCOORD1;
layout(location = 0) out vec4 SV_Target0;
vec3 u_xlat0;
vec4 u_xlat16_1;
vec4 u_xlat16_2;
vec3 u_xlat3;
float u_xlat16_5;
float u_xlat6;
void main(){
  (u_xlat0.x = (vs_TEXCOORD1.y + (-_WorldSpaceCameraPos.y)));
  (u_xlat0.x = (u_xlat0.x + (-_FogHeight)));
  (u_xlat3.x = (_FogFallOff * 0.0099999998));
  (u_xlat0.x = (u_xlat0.x * u_xlat3.x));
  (u_xlat3.x = exp2((-u_xlat0.x)));
  (u_xlat6 = ((-u_xlat3.x) + 1.0));
  (u_xlat3.x = (u_xlat3.x * _FogGlobalDensity));
  (u_xlat0.x = (u_xlat6 / u_xlat0.x));
  (u_xlat0.x = (u_xlat3.x * u_xlat0.x));
  (u_xlat3.xyz = ((-vs_TEXCOORD1.xyz) + _WorldSpaceCameraPos.xyz));
  (u_xlat3.x = dot(u_xlat3.xyz, u_xlat3.xyz));
  (u_xlat3.x = max(u_xlat3.x, 6.1035156e-05));
  (u_xlat3.x = sqrt(u_xlat3.x));
  (u_xlat3.x = (u_xlat3.x + (-_FogStartDis)));
  (u_xlat3.x = (u_xlat3.x / _FogGradientDis));
  (u_xlat3.x = max(u_xlat3.x, 0.0));
  (u_xlat0.x = ((u_xlat0.x * u_xlat3.x) + (-_FogStart)));
  (u_xlat3.x = ((-_FogStart) + _FogEnd));
  (u_xlat3.x = (1.0 / u_xlat3.x));
  (u_xlat0.x = (u_xlat3.x * u_xlat0.x));
  (u_xlat0.x = clamp(u_xlat0.x, 0.0, 1.0));
  (u_xlat3.x = ((u_xlat0.x * -2.0) + 3.0));
  (u_xlat0.x = (u_xlat0.x * u_xlat0.x));
  (u_xlat0.x = (u_xlat0.x * u_xlat3.x));
  (u_xlat0.x = min(u_xlat0.x, 1.0));
  (u_xlat0.x = (u_xlat0.x * _FogColor.w));
  (u_xlat3.xy = (vs_TEXCOORD0.xy * vec2(vec2(_Tiling, _Tiling))));
  (u_xlat16_1 = texture(_MainTex, u_xlat3.xy));
  (u_xlat16_2 = (_Color * vec4(vec4(_Intensity, _Intensity, _Intensity, _Intensity))));
  (u_xlat3.xyz = (((-u_xlat16_1.xyz) * u_xlat16_2.xyz) + _FogColor.xyz));
  (u_xlat16_1 = (u_xlat16_1 * u_xlat16_2));
  (u_xlat0.xyz = ((u_xlat0.xxx * u_xlat3.xyz) + u_xlat16_1.xyz));
  (SV_Target0.xyz = u_xlat0.xyz);
  (u_xlat16_2.x = (u_xlat16_1.w * _Color.w));
  (u_xlat16_5 = ((u_xlat16_1.x * _Color.w) + (-u_xlat16_2.x)));
  (SV_Target0.w = ((_AlphaIsR * u_xlat16_5) + u_xlat16_2.x));
  return ;
}
