#version 450
uniform vec3 _WorldSpaceCameraPos;
uniform int unity_BaseInstanceID;
uniform vec4 _FogColor;
uniform vec4 _LightColor1;
uniform vec4 _LightColor2;
uniform float _LightIntensity1;
uniform float _LightIntensity2;
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _MainTex_ST;
  vec4 _EmissionColor;
  vec4 _Color;
  vec4 _Fresnel_Color_Edge;
  vec4 _GPUSKin_TextureSize;
  vec4 _ShadowColor;
  float _VertexOffsetY;
  float _MainLightOn;
  float _MaxAddIntensity1;
  float _EmissionIntensity;
  float _CutOff;
  float _AlphaIsR;
  float _Intensity;
  float _NoMainTextureOn;
  float _HeroDayNight_ON;
  float _EMISSIONMAPON_BUILDING_ON;
  float _FadeY;
  float _AlphFadeY_ON;
};
struct FresnelArray_Type {
  vec4 _Fresnel_Color;
  float _Fresnel_Scale_Edge;
  float _Fresnel_Intensity;
  float _Fresnel_Bisa;
  float _Fresnel_Scale;
  float _Fresnel_ON;
};
layout(std140, binding = 1) uniform UnityInstancing_Fresnel{
  FresnelArray_Type FresnelArray[128];
};
layout(location = 0) uniform sampler2D _MainTex;
in vec2 vs_TEXCOORD0;
in vec3 vs_TEXCOORD1;
in vec4 vs_TEXCOORD2;
flat in uint vs_SV_InstanceID0;
layout(location = 0) out vec4 SV_Target0;
vec3 u_xlat0;
int u_xlati0;
vec3 u_xlat1;
vec4 u_xlat16_1;
vec3 u_xlat16_2;
vec4 u_xlat16_3;
vec3 u_xlat16_4;
vec3 u_xlat16_5;
vec3 u_xlat6;
bool u_xlatb6;
float u_xlat16_8;
float u_xlat18;
bool u_xlatb18;
float u_xlat19;
float u_xlat16_20;
float u_xlat16_21;
float u_xlat16_22;
void main(){
  (u_xlati0 = (int(vs_SV_InstanceID0) + unity_BaseInstanceID));
  (u_xlat6.xy = ((vs_TEXCOORD0.xy * _MainTex_ST.xy) + _MainTex_ST.zw));
  (u_xlat16_1 = texture(_MainTex, u_xlat6.xy));
  (u_xlat16_2.xyz = ((-u_xlat16_1.xyz) + vec3(1.0, 1.0, 1.0)));
  (u_xlat16_2.xyz = ((vec3(vec3(_NoMainTextureOn, _NoMainTextureOn, _NoMainTextureOn)) * u_xlat16_2.xyz) + u_xlat16_1.xyz));
  (u_xlat16_3 = (_Color * vec4(vec4(_Intensity, _Intensity, _Intensity, _Intensity))));
  (u_xlat16_2.xyz = (u_xlat16_2.xyz * u_xlat16_3.xyz));
  (u_xlat16_20 = (u_xlat16_1.w * u_xlat16_3.w));
  (u_xlat16_3.xyz = (_LightColor1.xyz * vec3(_LightIntensity1)));
  (u_xlat16_4.xyz = ((_LightColor2.xyz * vec3(vec3(_LightIntensity2, _LightIntensity2, _LightIntensity2))) + (-u_xlat16_3.xyz)));
  (u_xlat16_3.xyz = ((vec3(_HeroDayNight_ON) * u_xlat16_4.xyz) + u_xlat16_3.xyz));
  (u_xlat16_4.xyz = (u_xlat16_2.xyz * u_xlat16_3.xyz));
  (u_xlati0 = (u_xlati0 * 3));
  (u_xlatb6 = (0.5 < FresnelArray[(u_xlati0 / 3)]._Fresnel_ON));
  if (u_xlatb6)
  {
    (u_xlat6.x = dot(vs_TEXCOORD1.xyz, vs_TEXCOORD1.xyz));
    (u_xlat6.x = inversesqrt(u_xlat6.x));
    (u_xlat6.xyz = (u_xlat6.xxx * vs_TEXCOORD1.xyz));
    (u_xlat1.xyz = ((-vs_TEXCOORD2.xyz) + _WorldSpaceCameraPos.xyz));
    (u_xlat19 = dot(u_xlat1.xyz, u_xlat1.xyz));
    (u_xlat19 = inversesqrt(u_xlat19));
    (u_xlat1.xyz = (vec3(u_xlat19) * u_xlat1.xyz));
    (u_xlat16_21 = dot(u_xlat6.xyz, u_xlat1.xyz));
    (u_xlat16_21 = clamp(u_xlat16_21, 0.0, 1.0));
    (u_xlat16_21 = ((-u_xlat16_21) + 1.0));
    (u_xlat16_22 = (u_xlat16_21 * u_xlat16_21));
    (u_xlat16_21 = (u_xlat16_21 * u_xlat16_22));
    (u_xlat16_22 = (u_xlat16_21 * u_xlat16_22));
    (u_xlat16_22 = ((FresnelArray[(u_xlati0 / 3)]._Fresnel_Scale * u_xlat16_22) + FresnelArray[(u_xlati0 / 3)]._Fresnel_Bisa));
    (u_xlat16_21 = (u_xlat16_21 * FresnelArray[(u_xlati0 / 3)]._Fresnel_Scale_Edge));
    (u_xlat16_21 = (u_xlat16_21 * FresnelArray[(u_xlati0 / 3)]._Fresnel_Intensity));
    (u_xlat16_22 = (u_xlat16_22 * FresnelArray[(u_xlati0 / 3)]._Fresnel_Intensity));
    (u_xlat16_21 = (u_xlat16_21 * FresnelArray[(u_xlati0 / 3)]._Fresnel_Scale_Edge));
    (u_xlat16_5.xyz = ((FresnelArray[(u_xlati0 / 3)]._Fresnel_Color.xyz * vec3(u_xlat16_22)) + vec3(u_xlat16_21)));
    (u_xlat16_4.xyz = ((u_xlat16_2.xyz * u_xlat16_3.xyz) + u_xlat16_5.xyz));
  }
  (u_xlat0.x = vs_TEXCOORD2.w);
  (u_xlat0.x = clamp(u_xlat0.x, 0.0, 1.0));
  (u_xlat0.x = (u_xlat0.x * _FogColor.w));
  (u_xlat6.xyz = ((-u_xlat16_4.xyz) + _FogColor.xyz));
  (u_xlat0.xyz = ((u_xlat0.xxx * u_xlat6.xyz) + u_xlat16_4.xyz));
  (u_xlat16_8 = (u_xlat16_20 * _Color.w));
  (u_xlat16_2.x = ((u_xlat16_2.x * _Color.w) + (-u_xlat16_8)));
  (u_xlat16_2.x = ((_AlphaIsR * u_xlat16_2.x) + u_xlat16_8));
  (u_xlatb18 = (vs_TEXCOORD2.y >= _FadeY));
  (u_xlat18 = ((u_xlatb18) ? (1.0) : (0.0)));
  (u_xlat16_8 = ((u_xlat18 * u_xlat16_2.x) + (-u_xlat16_2.x)));
  (SV_Target0.w = ((_AlphFadeY_ON * u_xlat16_8) + u_xlat16_2.x));
  (SV_Target0.xyz = u_xlat0.xyz);
  return ;
}
