#version 450
uniform vec4 _MainLightPosition;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform vec4 _GPUSKin_ClipParams;
layout(std140, binding = 1) uniform UnityPerDraw{
  vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
  vec4 hlslcc_mtx4x4unity_WorldToObject[4];
  vec4 unity_LODFade;
  vec4 unity_WorldTransformParams;
  vec4 unity_RenderingLayer;
  vec4 unity_LightData;
  vec4 unity_LightIndices[2];
  vec4 unity_ProbesOcclusion;
  vec4 unity_SpecCube0_HDR;
  vec4 unity_SpecCube1_HDR;
  vec4 unity_SpecCube0_BoxMax;
  vec4 unity_SpecCube0_BoxMin;
  vec4 unity_SpecCube0_ProbePosition;
  vec4 unity_SpecCube1_BoxMax;
  vec4 unity_SpecCube1_BoxMin;
  vec4 unity_SpecCube1_ProbePosition;
  vec4 unity_LightmapST;
  vec4 unity_DynamicLightmapST;
  vec4 unity_SHAr;
  vec4 unity_SHAg;
  vec4 unity_SHAb;
  vec4 unity_SHBr;
  vec4 unity_SHBg;
  vec4 unity_SHBb;
  vec4 unity_SHC;
  vec4 hlslcc_mtx4x4unity_MatrixPreviousM[4];
  vec4 hlslcc_mtx4x4unity_MatrixPreviousMI[4];
  vec4 unity_MotionVectorsParams;
};
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _CustomLightDir;
  vec4 _GPUSKin_TextureSize;
  vec4 _ShadowColor;
  float _UseCustomLightDir;
  float _GroundHeight;
  float _ShadowFalloff;
  float _Alpha;
};
layout(location = 0) uniform sampler2D _GPUSKin_Matrix;
in vec4 in_POSITION0;
in vec4 in_TEXCOORD3;
in vec4 in_TEXCOORD4;
out vec4 vs_COLOR0;
vec4 u_xlat0;
vec4 u_xlat1;
vec4 u_xlat2;
vec4 u_xlat3;
vec4 u_xlat4;
vec2 u_xlat16_4;
vec4 u_xlat5;
vec4 u_xlat6;
vec4 u_xlat7;
vec4 u_xlat8;
vec4 u_xlat9;
vec4 u_xlat10;
vec3 u_xlat16_11;
vec3 u_xlat12;
vec3 u_xlat13;
float u_xlat36;
void main(){
  (u_xlat0.x = floor(_GPUSKin_ClipParams.y));
  (u_xlat12.x = (u_xlat0.x + 1.0));
  (u_xlat0.x = ((u_xlat0.x * _GPUSKin_TextureSize.z) + _GPUSKin_ClipParams.x));
  (u_xlat12.x = ((u_xlat12.x * _GPUSKin_TextureSize.z) + _GPUSKin_ClipParams.x));
  (u_xlat1 = ((in_TEXCOORD3.xxzz * vec4(3.0, 3.0, 3.0, 3.0)) + u_xlat12.xxxx));
  (u_xlat2 = ((in_TEXCOORD4.xxzz * vec4(3.0, 3.0, 3.0, 3.0)) + u_xlat12.xxxx));
  (u_xlat3 = (u_xlat1 + vec4(1.0, 2.0, 1.0, 2.0)));
  (u_xlat16_4.xy = (vec2(1.0, 1.0) / vec2(_GPUSKin_TextureSize.xy)));
  (u_xlat5 = (u_xlat3 * u_xlat16_4.xxxx));
  (u_xlat5 = floor(u_xlat5));
  (u_xlat3 = (((-u_xlat5) * _GPUSKin_TextureSize.xxxx) + u_xlat3));
  (u_xlat5 = (u_xlat5 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat5 = (u_xlat16_4.yyyy * u_xlat5));
  (u_xlat3 = (u_xlat3 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat3 = (u_xlat16_4.xxxx * u_xlat3.xzyw));
  (u_xlat6.xz = u_xlat3.yw);
  (u_xlat6.yw = u_xlat5.zw);
  (u_xlat3.yw = u_xlat5.xy);
  (u_xlat5 = textureLod(_GPUSKin_Matrix, u_xlat6.xy, 0.0));
  (u_xlat6 = textureLod(_GPUSKin_Matrix, u_xlat6.zw, 0.0));
  (u_xlat7 = ((in_TEXCOORD3.xxzz * vec4(3.0, 3.0, 3.0, 3.0)) + u_xlat0.xxxx));
  (u_xlat0 = ((in_TEXCOORD4.xxzz * vec4(3.0, 3.0, 3.0, 3.0)) + u_xlat0.xxxx));
  (u_xlat8 = (u_xlat7 + vec4(1.0, 2.0, 1.0, 2.0)));
  (u_xlat9 = (u_xlat16_4.xxxx * u_xlat8));
  (u_xlat9 = floor(u_xlat9));
  (u_xlat8 = (((-u_xlat9) * _GPUSKin_TextureSize.xxxx) + u_xlat8));
  (u_xlat9 = (u_xlat9 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat9 = (u_xlat16_4.yyyy * u_xlat9));
  (u_xlat8 = (u_xlat8 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat8 = (u_xlat16_4.xxxx * u_xlat8.xzyw));
  (u_xlat10.xz = u_xlat8.yw);
  (u_xlat10.yw = u_xlat9.zw);
  (u_xlat8.yw = u_xlat9.xy);
  (u_xlat9 = textureLod(_GPUSKin_Matrix, u_xlat10.xy, 0.0));
  (u_xlat10 = textureLod(_GPUSKin_Matrix, u_xlat10.zw, 0.0));
  (u_xlat5 = (u_xlat5 + (-u_xlat9)));
  (u_xlat1.x = fract(_GPUSKin_ClipParams.y));
  (u_xlat5 = ((u_xlat1.xxxx * u_xlat5) + u_xlat9));
  (u_xlat5.y = dot(u_xlat5, in_POSITION0));
  (u_xlat6 = (u_xlat6 + (-u_xlat10)));
  (u_xlat6 = ((u_xlat1.xxxx * u_xlat6) + u_xlat10));
  (u_xlat5.z = dot(u_xlat6, in_POSITION0));
  (u_xlat6.xy = (u_xlat1.yw * u_xlat16_4.xx));
  (u_xlat6.xy = floor(u_xlat6.xy));
  (u_xlat13.xy = (((-u_xlat6.xy) * _GPUSKin_TextureSize.xx) + u_xlat1.yw));
  (u_xlat6.xy = (u_xlat6.xy + vec2(0.5, 0.5)));
  (u_xlat6.zw = (u_xlat16_4.yy * u_xlat6.xy));
  (u_xlat13.xy = (u_xlat13.xy + vec2(0.5, 0.5)));
  (u_xlat6.xy = (u_xlat16_4.xx * u_xlat13.xy));
  (u_xlat9 = textureLod(_GPUSKin_Matrix, u_xlat6.yw, 0.0));
  (u_xlat6 = textureLod(_GPUSKin_Matrix, u_xlat6.xz, 0.0));
  (u_xlat13.xy = (u_xlat16_4.xx * u_xlat7.yw));
  (u_xlat13.xy = floor(u_xlat13.xy));
  (u_xlat7.xy = (((-u_xlat13.xy) * _GPUSKin_TextureSize.xx) + u_xlat7.yw));
  (u_xlat13.xy = (u_xlat13.xy + vec2(0.5, 0.5)));
  (u_xlat10.zw = (u_xlat16_4.yy * u_xlat13.xy));
  (u_xlat13.xy = (u_xlat7.xy + vec2(0.5, 0.5)));
  (u_xlat10.xy = (u_xlat16_4.xx * u_xlat13.xy));
  (u_xlat7 = textureLod(_GPUSKin_Matrix, u_xlat10.yw, 0.0));
  (u_xlat10 = textureLod(_GPUSKin_Matrix, u_xlat10.xz, 0.0));
  (u_xlat9 = ((-u_xlat7) + u_xlat9));
  (u_xlat7 = ((u_xlat1.xxxx * u_xlat9) + u_xlat7));
  (u_xlat5.x = dot(u_xlat7, in_POSITION0));
  (u_xlat13.xyz = (u_xlat5.xyz * in_TEXCOORD3.www));
  (u_xlat5 = textureLod(_GPUSKin_Matrix, u_xlat3.xy, 0.0));
  (u_xlat3 = textureLod(_GPUSKin_Matrix, u_xlat3.zw, 0.0));
  (u_xlat7 = textureLod(_GPUSKin_Matrix, u_xlat8.xy, 0.0));
  (u_xlat8 = textureLod(_GPUSKin_Matrix, u_xlat8.zw, 0.0));
  (u_xlat5 = (u_xlat5 + (-u_xlat7)));
  (u_xlat5 = ((u_xlat1.xxxx * u_xlat5) + u_xlat7));
  (u_xlat5.y = dot(u_xlat5, in_POSITION0));
  (u_xlat3 = (u_xlat3 + (-u_xlat8)));
  (u_xlat3 = ((u_xlat1.xxxx * u_xlat3) + u_xlat8));
  (u_xlat5.z = dot(u_xlat3, in_POSITION0));
  (u_xlat3 = (u_xlat6 + (-u_xlat10)));
  (u_xlat3 = ((u_xlat1.xxxx * u_xlat3) + u_xlat10));
  (u_xlat5.x = dot(u_xlat3, in_POSITION0));
  (u_xlat13.xyz = ((u_xlat5.xyz * in_TEXCOORD3.yyy) + u_xlat13.xyz));
  (u_xlat3 = (u_xlat2 + vec4(1.0, 2.0, 1.0, 2.0)));
  (u_xlat5 = (u_xlat16_4.xxxx * u_xlat3));
  (u_xlat5 = floor(u_xlat5));
  (u_xlat3 = (((-u_xlat5) * _GPUSKin_TextureSize.xxxx) + u_xlat3));
  (u_xlat5 = (u_xlat5 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat5 = (u_xlat16_4.yyyy * u_xlat5));
  (u_xlat3 = (u_xlat3 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat3 = (u_xlat16_4.xxxx * u_xlat3.zxwy));
  (u_xlat6.xz = u_xlat3.yw);
  (u_xlat6.yw = u_xlat5.xy);
  (u_xlat3.yw = u_xlat5.zw);
  (u_xlat5 = textureLod(_GPUSKin_Matrix, u_xlat6.xy, 0.0));
  (u_xlat6 = textureLod(_GPUSKin_Matrix, u_xlat6.zw, 0.0));
  (u_xlat7 = (u_xlat0 + vec4(1.0, 2.0, 1.0, 2.0)));
  (u_xlat8 = (u_xlat16_4.xxxx * u_xlat7));
  (u_xlat8 = floor(u_xlat8));
  (u_xlat7 = (((-u_xlat8) * _GPUSKin_TextureSize.xxxx) + u_xlat7));
  (u_xlat8 = (u_xlat8 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat8 = (u_xlat16_4.yyyy * u_xlat8));
  (u_xlat7 = (u_xlat7 + vec4(0.5, 0.5, 0.5, 0.5)));
  (u_xlat7 = (u_xlat16_4.xxxx * u_xlat7.zxwy));
  (u_xlat9.xz = u_xlat7.yw);
  (u_xlat9.yw = u_xlat8.xy);
  (u_xlat7.yw = u_xlat8.zw);
  (u_xlat8 = textureLod(_GPUSKin_Matrix, u_xlat9.xy, 0.0));
  (u_xlat9 = textureLod(_GPUSKin_Matrix, u_xlat9.zw, 0.0));
  (u_xlat5 = (u_xlat5 + (-u_xlat8)));
  (u_xlat5 = ((u_xlat1.xxxx * u_xlat5) + u_xlat8));
  (u_xlat5.y = dot(u_xlat5, in_POSITION0));
  (u_xlat6 = (u_xlat6 + (-u_xlat9)));
  (u_xlat6 = ((u_xlat1.xxxx * u_xlat6) + u_xlat9));
  (u_xlat5.z = dot(u_xlat6, in_POSITION0));
  (u_xlat0.xz = (u_xlat2.yw * u_xlat16_4.xx));
  (u_xlat0.xz = floor(u_xlat0.xz));
  (u_xlat2.xy = (((-u_xlat0.xz) * _GPUSKin_TextureSize.xx) + u_xlat2.yw));
  (u_xlat0.xz = (u_xlat0.xz + vec2(0.5, 0.5)));
  (u_xlat6.zw = (u_xlat16_4.yy * u_xlat0.xz));
  (u_xlat0.xz = (u_xlat2.xy + vec2(0.5, 0.5)));
  (u_xlat6.xy = (u_xlat16_4.xx * u_xlat0.xz));
  (u_xlat2 = textureLod(_GPUSKin_Matrix, u_xlat6.xz, 0.0));
  (u_xlat6 = textureLod(_GPUSKin_Matrix, u_xlat6.yw, 0.0));
  (u_xlat0.xz = (u_xlat16_4.xx * u_xlat0.yw));
  (u_xlat0.xz = floor(u_xlat0.xz));
  (u_xlat12.xz = (((-u_xlat0.xz) * _GPUSKin_TextureSize.xx) + u_xlat0.yw));
  (u_xlat0.xz = (u_xlat0.xz + vec2(0.5, 0.5)));
  (u_xlat8.zw = (u_xlat16_4.yy * u_xlat0.xz));
  (u_xlat0.xy = (u_xlat12.xz + vec2(0.5, 0.5)));
  (u_xlat8.xy = (u_xlat16_4.xx * u_xlat0.xy));
  (u_xlat0 = textureLod(_GPUSKin_Matrix, u_xlat8.xz, 0.0));
  (u_xlat4 = textureLod(_GPUSKin_Matrix, u_xlat8.yw, 0.0));
  (u_xlat2 = ((-u_xlat0) + u_xlat2));
  (u_xlat0 = ((u_xlat1.xxxx * u_xlat2) + u_xlat0));
  (u_xlat5.x = dot(u_xlat0, in_POSITION0));
  (u_xlat0.xyz = ((u_xlat5.xyz * in_TEXCOORD4.yyy) + u_xlat13.xyz));
  (u_xlat2 = textureLod(_GPUSKin_Matrix, u_xlat3.xy, 0.0));
  (u_xlat3 = textureLod(_GPUSKin_Matrix, u_xlat3.zw, 0.0));
  (u_xlat5 = textureLod(_GPUSKin_Matrix, u_xlat7.xy, 0.0));
  (u_xlat7 = textureLod(_GPUSKin_Matrix, u_xlat7.zw, 0.0));
  (u_xlat2 = (u_xlat2 + (-u_xlat5)));
  (u_xlat2 = ((u_xlat1.xxxx * u_xlat2) + u_xlat5));
  (u_xlat2.y = dot(u_xlat2, in_POSITION0));
  (u_xlat3 = (u_xlat3 + (-u_xlat7)));
  (u_xlat3 = ((u_xlat1.xxxx * u_xlat3) + u_xlat7));
  (u_xlat2.z = dot(u_xlat3, in_POSITION0));
  (u_xlat3 = ((-u_xlat4) + u_xlat6));
  (u_xlat1 = ((u_xlat1.xxxx * u_xlat3) + u_xlat4));
  (u_xlat2.x = dot(u_xlat1, in_POSITION0));
  (u_xlat0.xyz = ((u_xlat2.xyz * in_TEXCOORD4.www) + u_xlat0.xyz));
  (u_xlat1.xyz = (u_xlat0.yyy * hlslcc_mtx4x4unity_ObjectToWorld[1].xyz));
  (u_xlat0.xyw = ((hlslcc_mtx4x4unity_ObjectToWorld[0].xyz * u_xlat0.xxx) + u_xlat1.xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[2].xyz * u_xlat0.zzz) + u_xlat0.xyw));
  (u_xlat0.xyz = (u_xlat0.xyz + hlslcc_mtx4x4unity_ObjectToWorld[3].xyz));
  (u_xlat36 = (u_xlat0.y + (-_GroundHeight)));
  (u_xlat36 = max(u_xlat36, 0.0));
  (u_xlat16_11.xyz = ((-_MainLightPosition.xyz) + _CustomLightDir.xyz));
  (u_xlat16_11.xyz = ((vec3(_UseCustomLightDir) * u_xlat16_11.xyz) + _MainLightPosition.xyz));
  (u_xlat1.xy = (vec2(u_xlat36) * u_xlat16_11.xz));
  (u_xlat36 = (1.0 / float(u_xlat16_11.y)));
  (u_xlat0.xz = (((-u_xlat1.xy) * vec2(u_xlat36)) + u_xlat0.xz));
  (u_xlat12.x = min(u_xlat0.y, _GroundHeight));
  (u_xlat1 = (u_xlat12.xxxx * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx) + u_xlat1));
  (u_xlat0 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz) + u_xlat1));
  (gl_Position = (u_xlat0 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (vs_COLOR0.w = (_ShadowColor.w * 0.89999998));
  (vs_COLOR0.xyz = _ShadowColor.xyz);
  return ;
}
