#version 450
uniform vec4 _MainLightPosition;
uniform vec3 _WorldSpaceCameraPos;
uniform vec4 _LightColor2;
uniform float _LightIntensity2;
layout(std140, binding = 0) uniform UnityPerDraw{
  vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
  vec4 hlslcc_mtx4x4unity_WorldToObject[4];
  vec4 unity_LODFade;
  vec4 unity_WorldTransformParams;
  vec4 unity_RenderingLayer;
  vec4 unity_LightData;
  vec4 unity_LightIndices[2];
  vec4 unity_ProbesOcclusion;
  vec4 unity_SpecCube0_HDR;
  vec4 unity_SpecCube1_HDR;
  vec4 unity_SpecCube0_BoxMax;
  vec4 unity_SpecCube0_BoxMin;
  vec4 unity_SpecCube0_ProbePosition;
  vec4 unity_SpecCube1_BoxMax;
  vec4 unity_SpecCube1_BoxMin;
  vec4 unity_SpecCube1_ProbePosition;
  vec4 unity_LightmapST;
  vec4 unity_DynamicLightmapST;
  vec4 unity_SHAr;
  vec4 unity_SHAg;
  vec4 unity_SHAb;
  vec4 unity_SHBr;
  vec4 unity_SHBg;
  vec4 unity_SHBb;
  vec4 unity_SHC;
  vec4 hlslcc_mtx4x4unity_MatrixPreviousM[4];
  vec4 hlslcc_mtx4x4unity_MatrixPreviousMI[4];
  vec4 unity_MotionVectorsParams;
};
layout(std140, binding = 1) uniform UnityPerMaterial{
  vec4 _SepcularGloss_ST;
  vec4 _Dump_ST;
  vec4 _MainTex_ST;
  vec4 _DetailTex_ST;
  vec4 _ReflectionMap_HDR;
  vec4 _SpecColor;
  vec4 _BaseColor;
  vec4 ReflectionDir;
  vec4 _CustomSpecLightDir;
  vec4 _ShadowColor;
  vec4 _CustomLightDir;
  vec4 _AmbientSky;
  vec4 _AmbientEquator;
  vec4 _AmbientGround;
  float _Shininess;
  float _Reflectivity;
  float _Smoothness0;
  float _CutValue;
  float _Leather;
  float _Cloth;
  float _Skin;
  float _ReflectionIntenSity;
  float _DetailIntensity;
  float _CustomSpecLightDir_ON;
  vec4 _Fresnel_Color;
  float _Fresnel_Bisa;
  float _Fresnel_Scale;
  float _Fresnel_Intensity;
  float _Fresnel_ON;
  float _FadeY;
  float _AlphFadeY_ON;
};
layout(location = 0) uniform sampler2D _SepcularGloss;
layout(location = 1) uniform sampler2D _MainTex;
layout(location = 2) uniform sampler2D _DetailTex;
in vec4 vs_TEXCOORD0;
in vec2 vs_TEXCOORD3;
in vec3 vs_TEXCOORD4;
layout(location = 0) out vec4 SV_Target0;
vec3 u_xlat0;
vec4 u_xlat16_0;
vec3 u_xlat1;
vec4 u_xlat16_1;
bool u_xlatb1;
vec3 u_xlat2;
vec3 u_xlat3;
vec4 u_xlat16_4;
vec4 u_xlat16_5;
vec2 u_xlat6;
float u_xlat16_7;
float u_xlat8;
float u_xlat16_12;
float u_xlat16_20;
float u_xlat25;
float u_xlat10_26;
float u_xlat16_29;
void main(){
  (u_xlat0.xy = ((vs_TEXCOORD3.xy * _SepcularGloss_ST.xy) + _SepcularGloss_ST.zw));
  (u_xlat16_0 = texture(_SepcularGloss, u_xlat0.xy));
  (u_xlat1.xyz = ((-vs_TEXCOORD0.xyz) + _WorldSpaceCameraPos.xyz));
  (u_xlat25 = dot(u_xlat1.xyz, u_xlat1.xyz));
  (u_xlat25 = inversesqrt(u_xlat25));
  (u_xlat2.xyz = (vec3(u_xlat25) * u_xlat1.xyz));
  (u_xlat3.xyz = ((-_MainLightPosition.xyz) + _CustomSpecLightDir.xyz));
  (u_xlat3.xyz = ((vec3(vec3(_CustomSpecLightDir_ON, _CustomSpecLightDir_ON, _CustomSpecLightDir_ON)) * u_xlat3.xyz) + _MainLightPosition.xyz));
  (u_xlat1.xyz = ((u_xlat1.xyz * vec3(u_xlat25)) + u_xlat3.xyz));
  (u_xlat25 = dot(u_xlat1.xyz, u_xlat1.xyz));
  (u_xlat25 = inversesqrt(u_xlat25));
  (u_xlat1.xyz = (vec3(u_xlat25) * u_xlat1.xyz));
  (u_xlat25 = dot(vs_TEXCOORD4.xyz, vs_TEXCOORD4.xyz));
  (u_xlat25 = inversesqrt(u_xlat25));
  (u_xlat3.xyz = (vec3(u_xlat25) * vs_TEXCOORD4.xyz));
  (u_xlat16_4.x = dot(u_xlat1.xyz, u_xlat3.xyz));
  (u_xlat1.xy = ((vs_TEXCOORD3.xy * _MainTex_ST.xy) + _MainTex_ST.zw));
  (u_xlat16_1 = texture(_MainTex, u_xlat1.xy));
  (u_xlat16_5 = (_LightColor2 * _BaseColor));
  (u_xlat16_5 = (u_xlat16_5 * vec4(_LightIntensity2)));
  (u_xlat16_12 = (u_xlat16_1.w * u_xlat16_5.w));
  (u_xlat16_4.x = max(u_xlat16_4.x, 0.0));
  (u_xlat16_20 = (_Shininess * 128.0));
  (u_xlat25 = log2(u_xlat16_4.x));
  (u_xlat25 = (u_xlat25 * u_xlat16_20));
  (u_xlat25 = exp2(u_xlat25));
  (u_xlat6.xy = ((vs_TEXCOORD3.xy * _DetailTex_ST.xy) + _DetailTex_ST.zw));
  (u_xlat10_26 = texture(_DetailTex, u_xlat6.xy).x);
  (u_xlat16_4.xzw = (_LightColor2.xyz * _SpecColor.xyz));
  (u_xlat16_4.xzw = (u_xlat16_4.xzw * vec3(_LightIntensity2)));
  (u_xlat16_4.xzw = (vec3(u_xlat25) * u_xlat16_4.xzw));
  (u_xlat8 = (u_xlat16_0.y * u_xlat10_26));
  (u_xlat8 = (u_xlat8 * _Leather));
  (u_xlat8 = (u_xlat8 * _DetailIntensity));
  (u_xlat0.x = ((u_xlat16_0.x * _Smoothness0) + u_xlat8));
  (u_xlat0.x = ((u_xlat16_0.z * _Cloth) + u_xlat0.x));
  (u_xlat0.x = ((u_xlat16_0.w * _Skin) + u_xlat0.x));
  (u_xlat0.xyz = (u_xlat0.xxx * u_xlat16_4.xzw));
  (u_xlat0.xyz = clamp(u_xlat0.xyz, 0.0, 1.0));
  (u_xlat16_4.xzw = ((u_xlat16_1.xyz * u_xlat16_5.xyz) + u_xlat0.xyz));
  (u_xlat16_5.xyz = ((-_ShadowColor.xyz) + vec3(1.0, 1.0, 1.0)));
  (u_xlat16_5.xyz = ((unity_LightData.zzz * u_xlat16_5.xyz) + _ShadowColor.xyz));
  (u_xlat16_0.xyz = (u_xlat16_4.xzw * u_xlat16_5.xyz));
  (u_xlatb1 = (0.5 < _Fresnel_ON));
  if (u_xlatb1)
  {
    (u_xlat16_29 = dot(u_xlat3.xyz, u_xlat2.xyz));
    (u_xlat16_29 = clamp(u_xlat16_29, 0.0, 1.0));
    (u_xlat16_29 = ((-u_xlat16_29) + 1.0));
    (u_xlat16_7 = (u_xlat16_29 * u_xlat16_29));
    (u_xlat16_7 = (u_xlat16_7 * u_xlat16_7));
    (u_xlat16_29 = (u_xlat16_29 * u_xlat16_7));
    (u_xlat16_29 = ((_Fresnel_Scale * u_xlat16_29) + _Fresnel_Bisa));
    (u_xlat16_29 = (u_xlat16_29 * _Fresnel_Intensity));
    (u_xlat16_4.xzw = (((-u_xlat16_4.xzw) * u_xlat16_5.xyz) + _Fresnel_Color.xyz));
    (u_xlat16_0.xyz = ((vec3(u_xlat16_29) * u_xlat16_4.xzw) + u_xlat16_0.xyz));
  }
  (u_xlatb1 = (vs_TEXCOORD0.y >= _FadeY));
  (u_xlat1.x = ((u_xlatb1) ? (1.0) : (0.0)));
  (u_xlat16_4.x = ((u_xlat1.x * u_xlat16_12) + (-u_xlat16_12)));
  (u_xlat16_0.w = ((_AlphFadeY_ON * u_xlat16_4.x) + u_xlat16_12));
  (u_xlat16_4.x = (u_xlat16_0.w + (-_CutValue)));
  (u_xlatb1 = (u_xlat16_4.x < 0.0));
  if (u_xlatb1)
  {
    discard;
  }
  (SV_Target0 = u_xlat16_0);
  return ;
}
