#version 450
uniform vec4 _ProjectionParams;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
layout(std140, binding = 0) uniform UnityPerDraw{
  vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
  vec4 hlslcc_mtx4x4unity_WorldToObject[4];
  vec4 unity_LODFade;
  vec4 unity_WorldTransformParams;
  vec4 unity_RenderingLayer;
  vec4 unity_LightData;
  vec4 unity_LightIndices[2];
  vec4 unity_ProbesOcclusion;
  vec4 unity_SpecCube0_HDR;
  vec4 unity_SpecCube1_HDR;
  vec4 unity_SpecCube0_BoxMax;
  vec4 unity_SpecCube0_BoxMin;
  vec4 unity_SpecCube0_ProbePosition;
  vec4 unity_SpecCube1_BoxMax;
  vec4 unity_SpecCube1_BoxMin;
  vec4 unity_SpecCube1_ProbePosition;
  vec4 unity_LightmapST;
  vec4 unity_DynamicLightmapST;
  vec4 unity_SHAr;
  vec4 unity_SHAg;
  vec4 unity_SHAb;
  vec4 unity_SHBr;
  vec4 unity_SHBg;
  vec4 unity_SHBb;
  vec4 unity_SHC;
  vec4 hlslcc_mtx4x4unity_MatrixPreviousM[4];
  vec4 hlslcc_mtx4x4unity_MatrixPreviousMI[4];
  vec4 unity_MotionVectorsParams;
};
layout(std140, binding = 1) uniform UnityPerMaterial{
  vec4 _Control_ST;
  vec4 _DissolveTex_ST;
  vec4 _Control_TexelSize;
  vec4 _WorldEdge;
  vec4 _EnvColor;
  vec4 _Decal_Color;
  vec4 _CustomLightColor;
  vec4 _CustomLightDir;
  vec4 _DiffuseRemapScale0;
  vec4 _DiffuseRemapScale1;
  vec4 _DiffuseRemapScale2;
  vec4 _DiffuseRemapScale3;
  vec4 _Splat0_ST;
  vec4 _Splat1_ST;
  vec4 _Splat2_ST;
  vec4 _Splat3_ST;
  vec4 _EdgeColor;
  float _CustomEnv_ON;
  float _DissolveProgress;
  float _EdgeSize;
  float _DissolveMin;
  float _DissolveMax;
  float _CustomLightIntensity;
};
in vec4 in_POSITION0;
in vec2 in_TEXCOORD0;
out vec2 vs_TEXCOORD0;
out float vs_TEXCOORD4;
out vec4 vs_TEXCOORD1;
out vec4 vs_TEXCOORD2;
out vec4 vs_TEXCOORD3;
out vec3 vs_TEXCOORD5;
out vec2 vs_TEXCOORD6;
out vec4 vs_TEXCOORD7;
vec4 u_xlat0;
vec4 u_xlat1;
void main(){
  (vs_TEXCOORD0.xy = in_TEXCOORD0.xy);
  (vs_TEXCOORD1.xy = ((in_TEXCOORD0.xy * _Splat0_ST.xy) + _Splat0_ST.zw));
  (vs_TEXCOORD1.zw = ((in_TEXCOORD0.xy * _Splat1_ST.xy) + _Splat1_ST.zw));
  (vs_TEXCOORD2.xy = ((in_TEXCOORD0.xy * _Splat2_ST.xy) + _Splat2_ST.zw));
  (vs_TEXCOORD2.zw = ((in_TEXCOORD0.xy * _Splat3_ST.xy) + _Splat3_ST.zw));
  (vs_TEXCOORD3 = vec4(0.0, 1.0, 0.0, 1.0));
  (vs_TEXCOORD4 = 0.0);
  (u_xlat0.xyz = (in_POSITION0.yyy * hlslcc_mtx4x4unity_ObjectToWorld[1].xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[0].xyz * in_POSITION0.xxx) + u_xlat0.xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[2].xyz * in_POSITION0.zzz) + u_xlat0.xyz));
  (u_xlat0.xyz = (u_xlat0.xyz + hlslcc_mtx4x4unity_ObjectToWorld[3].xyz));
  (vs_TEXCOORD5.xyz = u_xlat0.xyz);
  (vs_TEXCOORD6.xy = vec2(0.0, 0.0));
  (u_xlat1 = (u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx) + u_xlat1));
  (u_xlat0 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz) + u_xlat1));
  (u_xlat0 = (u_xlat0 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (gl_Position = u_xlat0);
  (u_xlat0.y = (u_xlat0.y * _ProjectionParams.x));
  (u_xlat1.xzw = (u_xlat0.xwy * vec3(0.5, 0.5, 0.5)));
  (vs_TEXCOORD7.zw = u_xlat0.zw);
  (vs_TEXCOORD7.xy = (u_xlat1.zz + u_xlat1.xw));
  return ;
}
