#version 450
uniform vec4 _Time;
uniform vec4 _ProjectionParams;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
layout(std140, binding = 1) uniform UnityPerDraw{
  vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
  vec4 hlslcc_mtx4x4unity_WorldToObject[4];
  vec4 unity_LODFade;
  vec4 unity_WorldTransformParams;
  vec4 unity_RenderingLayer;
  vec4 unity_LightData;
  vec4 unity_LightIndices[2];
  vec4 unity_ProbesOcclusion;
  vec4 unity_SpecCube0_HDR;
  vec4 unity_SpecCube1_HDR;
  vec4 unity_SpecCube0_BoxMax;
  vec4 unity_SpecCube0_BoxMin;
  vec4 unity_SpecCube0_ProbePosition;
  vec4 unity_SpecCube1_BoxMax;
  vec4 unity_SpecCube1_BoxMin;
  vec4 unity_SpecCube1_ProbePosition;
  vec4 unity_LightmapST;
  vec4 unity_DynamicLightmapST;
  vec4 unity_SHAr;
  vec4 unity_SHAg;
  vec4 unity_SHAb;
  vec4 unity_SHBr;
  vec4 unity_SHBg;
  vec4 unity_SHBb;
  vec4 unity_SHC;
  vec4 hlslcc_mtx4x4unity_MatrixPreviousM[4];
  vec4 hlslcc_mtx4x4unity_MatrixPreviousMI[4];
  vec4 unity_MotionVectorsParams;
};
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _HeightTileSpeed;
  vec4 _MainTex_ST;
  vec4 _FogOfWarMask_ST;
  vec4 _Color;
  vec4 _Color1;
  vec4 _Color2;
  vec4 _Color0;
  float _Height;
  float _HeightAmount;
  float _Alpha;
  float _LightIntensity;
  float _InvFade;
  float _Brightness;
  float _Contrast;
  float _Saturation;
};
in vec4 in_POSITION0;
in vec2 in_TEXCOORD0;
out vec3 vs_TEXCOORD0;
out vec4 vs_TEXCOORD1;
out vec4 vs_TEXCOORD2;
out vec2 vs_TEXCOORD3;
vec4 u_xlat0;
vec4 u_xlat1;
vec2 u_xlat4;
void main(){
  (u_xlat0 = (in_POSITION0.yyyy * hlslcc_mtx4x4unity_ObjectToWorld[1]));
  (u_xlat0 = ((hlslcc_mtx4x4unity_ObjectToWorld[0] * in_POSITION0.xxxx) + u_xlat0));
  (u_xlat0 = ((hlslcc_mtx4x4unity_ObjectToWorld[2] * in_POSITION0.zzzz) + u_xlat0));
  (u_xlat0 = (u_xlat0 + hlslcc_mtx4x4unity_ObjectToWorld[3]));
  (u_xlat1 = (u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx) + u_xlat1));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz) + u_xlat1));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[3] * u_xlat0.wwww) + u_xlat1));
  (vs_TEXCOORD0.xyz = u_xlat0.xyz);
  (gl_Position = u_xlat1);
  (u_xlat0.x = (u_xlat1.y * _ProjectionParams.x));
  (u_xlat0.w = (u_xlat0.x * 0.5));
  (u_xlat0.xz = (u_xlat1.xw * vec2(0.5, 0.5)));
  (vs_TEXCOORD1.zw = u_xlat1.zw);
  (vs_TEXCOORD1.xy = (u_xlat0.zz + u_xlat0.xw));
  (u_xlat0.xy = (_Time.yy * _HeightTileSpeed.zw));
  (u_xlat0.xy = fract(u_xlat0.xy));
  (u_xlat4.xy = ((in_TEXCOORD0.xy * _MainTex_ST.xy) + _MainTex_ST.zw));
  (vs_TEXCOORD2.xy = (u_xlat0.xy + u_xlat4.xy));
  (vs_TEXCOORD3.xy = ((in_TEXCOORD0.xy * _FogOfWarMask_ST.xy) + _FogOfWarMask_ST.zw));
  return ;
}
