#version 450
uniform vec3 _WorldSpaceCameraPos;
uniform vec4 _ProjectionParams;
uniform vec4 unity_OrthoParams;
uniform vec4 hlslcc_mtx4x4unity_MatrixV[4];
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform int unity_BaseInstanceID;
layout(std140, binding = 0) uniform UnityPerDraw{
  vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
  vec4 hlslcc_mtx4x4unity_WorldToObject[4];
  vec4 unity_LODFade;
  vec4 unity_WorldTransformParams;
  vec4 unity_RenderingLayer;
  vec4 unity_LightData;
  vec4 unity_LightIndices[2];
  vec4 unity_ProbesOcclusion;
  vec4 unity_SpecCube0_HDR;
  vec4 unity_SpecCube1_HDR;
  vec4 unity_SpecCube0_BoxMax;
  vec4 unity_SpecCube0_BoxMin;
  vec4 unity_SpecCube0_ProbePosition;
  vec4 unity_SpecCube1_BoxMax;
  vec4 unity_SpecCube1_BoxMin;
  vec4 unity_SpecCube1_ProbePosition;
  vec4 unity_LightmapST;
  vec4 unity_DynamicLightmapST;
  vec4 unity_SHAr;
  vec4 unity_SHAg;
  vec4 unity_SHAb;
  vec4 unity_SHBr;
  vec4 unity_SHBg;
  vec4 unity_SHBb;
  vec4 unity_SHC;
  vec4 hlslcc_mtx4x4unity_MatrixPreviousM[4];
  vec4 hlslcc_mtx4x4unity_MatrixPreviousMI[4];
  vec4 unity_MotionVectorsParams;
};
struct unity_Builtins0Array_Type {
  vec4 hlslcc_mtx4x4unity_ObjectToWorldArray[4];
  vec4 hlslcc_mtx4x4unity_WorldToObjectArray[4];
};
layout(std140, binding = 2) uniform UnityInstancing_PerDraw0{
  unity_Builtins0Array_Type unity_Builtins0Array[128];
};
struct unity_Builtins2Array_Type {
  vec4 unity_SHArArray;
  vec4 unity_SHAgArray;
  vec4 unity_SHAbArray;
  vec4 unity_SHBrArray;
  vec4 unity_SHBgArray;
  vec4 unity_SHBbArray;
  vec4 unity_SHCArray;
};
layout(std140, binding = 3) uniform UnityInstancing_PerDraw2{
  unity_Builtins2Array_Type unity_Builtins2Array[128];
};
layout(std140, binding = 1) uniform UnityPerMaterial{
  float _AlphaScale;
  vec4 _SparkMap_ST;
  vec4 _WorldEdge;
  vec4 _Control_ST;
  vec4 _BaseNormal_ST;
  vec4 _NormalMask_ST;
  vec4 _Control_TexelSize;
  vec4 _SparkColor;
  vec4 _Color_Golobal;
  vec4 _Splat0_ST;
  vec4 _Splat1_ST;
  vec4 _Splat2_ST;
  vec4 _Splat3_ST;
  vec4 _Splat_Golobal_ST;
  vec4 _Color_Splat1;
  vec4 _Color_Splat2;
  vec4 _Color_Splat3;
  vec4 _Color_Splat4;
  vec4 _specColor;
  float _MinHeight;
  float _MaxHeight;
  float _HeightBlendScale;
  float _Weight;
  float _NormalMinHeight;
  float _NormalMaxHeight;
  float _BaseNormalScale;
  float _Color_Splat1_Intensity;
  float _Color_Splat2_Intensity;
  float _Color_Splat3_Intensity;
  float _Color_Splat4_Intensity;
  float _SparkColorIntensity;
  float _specScale;
  float _WorldUVON;
  int _HeightBlendOn;
  float _LightColorDesat;
  vec4 _BlurPlaneShadowColor;
  int _FakeNormalOn;
  vec4 _FakeNormalDir;
  float _FakeNormalChannel;
  float _FakeNormalScale;
  vec3 _EdgeColor01;
};
in vec4 in_POSITION0;
in vec3 in_NORMAL0;
in vec2 in_TEXCOORD0;
out vec4 vs_TEXCOORD0;
out vec4 vs_TEXCOORD1;
out vec4 vs_TEXCOORD2;
out vec4 vs_TEXCOORD3;
out float vs_TEXCOORD4;
out vec3 vs_TEXCOORD8;
out vec4 vs_TEXCOORD5;
out vec4 vs_TEXCOORD6;
out vec4 vs_TEXCOORD7;
vec4 u_xlat0;
bool u_xlatb0;
vec4 u_xlat1;
vec4 u_xlat2;
vec4 u_xlat3;
vec4 u_xlat16_3;
vec3 u_xlat4;
vec3 u_xlat16_5;
float u_xlat7;
vec3 u_xlat16_12;
vec3 u_xlat16_13;
int u_xlati14;
int u_xlati21;
float u_xlat22;
bool u_xlatb22;
void main(){
  (vs_TEXCOORD0.xy = in_TEXCOORD0.xy);
  (u_xlat0.xy = (vec2(1.0, 1.0) / vec2(_WorldEdge.xy)));
  (u_xlati14 = (gl_InstanceID + unity_BaseInstanceID));
  (u_xlati21 = int((u_xlati14 << 3)));
  (u_xlati14 = (u_xlati14 * 7));
  (u_xlat1.xyz = (in_POSITION0.yyy * unity_Builtins0Array[(u_xlati21 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[1].xyz));
  (u_xlat1.xyz = ((unity_Builtins0Array[(u_xlati21 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[0].xyz * in_POSITION0.xxx) + u_xlat1.xyz));
  (u_xlat1.xyz = ((unity_Builtins0Array[(u_xlati21 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[2].xyz * in_POSITION0.zzz) + u_xlat1.xyz));
  (u_xlat1.xyz = (u_xlat1.xyz + unity_Builtins0Array[(u_xlati21 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[3].xyz));
  (u_xlat2.xy = (u_xlat1.xz + _WorldEdge.zw));
  (u_xlat2.x = (u_xlat0.x * u_xlat2.x));
  (u_xlat2.z = ((u_xlat2.y * u_xlat0.y) + 1.0));
  (u_xlat0.xy = (u_xlat2.xz + (-in_TEXCOORD0.xy)));
  (vs_TEXCOORD0.zw = ((vec2(vec2(_WorldUVON, _WorldUVON)) * u_xlat0.xy) + in_TEXCOORD0.xy));
  (u_xlat2.x = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati21 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[0].xyz));
  (u_xlat2.y = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati21 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[1].xyz));
  (u_xlat2.z = dot(in_NORMAL0.xyz, unity_Builtins0Array[(u_xlati21 / 8)].hlslcc_mtx4x4unity_WorldToObjectArray[2].xyz));
  (u_xlat0.x = dot(u_xlat2.xyz, u_xlat2.xyz));
  (u_xlat0.x = max(u_xlat0.x, 0.0));
  (u_xlat0.x = inversesqrt(u_xlat0.x));
  (u_xlat2.xyz = (u_xlat0.xxx * u_xlat2.xyz));
  (vs_TEXCOORD1.xyz = u_xlat2.xyz);
  (u_xlat3.xyz = ((-u_xlat1.xyz) + _WorldSpaceCameraPos.xyz));
  (u_xlat0.x = dot(u_xlat3.xyz, u_xlat3.xyz));
  (u_xlat0.x = inversesqrt(u_xlat0.x));
  (u_xlat3.xyz = (u_xlat0.xxx * u_xlat3.xyz));
  (u_xlatb0 = (unity_OrthoParams.w == 0.0));
  (vs_TEXCOORD1.w = ((u_xlatb0) ? (u_xlat3.x) : (hlslcc_mtx4x4unity_MatrixV[0].z)));
  (u_xlat3.xw = (in_NORMAL0.yz * vec2(1.0, 0.0)));
  (u_xlat3.xw = ((in_NORMAL0.zx * vec2(0.0, 1.0)) + (-u_xlat3.xw)));
  (u_xlat4.xyz = (u_xlat3.www * unity_Builtins0Array[(u_xlati21 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[1].xyz));
  (u_xlat4.xyz = ((unity_Builtins0Array[(u_xlati21 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[0].xyz * u_xlat3.xxx) + u_xlat4.xyz));
  (u_xlat7 = dot(u_xlat4.xyz, u_xlat4.xyz));
  (u_xlat7 = max(u_xlat7, 0.0));
  (u_xlat7 = inversesqrt(u_xlat7));
  (u_xlat4.xyz = (vec3(u_xlat7) * u_xlat4.xyz));
  (vs_TEXCOORD2.xyz = u_xlat4.xyz);
  (vs_TEXCOORD2.w = ((u_xlatb0) ? (u_xlat3.y) : (hlslcc_mtx4x4unity_MatrixV[1].z)));
  (vs_TEXCOORD3.w = ((u_xlatb0) ? (u_xlat3.z) : (hlslcc_mtx4x4unity_MatrixV[2].z)));
  (u_xlat0.xyw = (u_xlat2.zxy * u_xlat4.yzx));
  (u_xlat0.xyw = ((u_xlat2.yzx * u_xlat4.zxy) + (-u_xlat0.xyw)));
  (u_xlatb22 = (unity_WorldTransformParams.w >= 0.0));
  (u_xlat22 = ((u_xlatb22) ? (1.0) : (-1.0)));
  (vs_TEXCOORD3.xyz = (u_xlat0.xyw * vec3(u_xlat22)));
  (u_xlat16_5.x = (u_xlat2.y * u_xlat2.y));
  (u_xlat16_5.x = ((u_xlat2.x * u_xlat2.x) + (-u_xlat16_5.x)));
  (u_xlat16_3 = (u_xlat2.yzzx * u_xlat2.xyzz));
  (u_xlat16_12.x = dot(unity_Builtins2Array[(u_xlati14 / 7)].unity_SHBrArray, u_xlat16_3));
  (u_xlat16_12.y = dot(unity_Builtins2Array[(u_xlati14 / 7)].unity_SHBgArray, u_xlat16_3));
  (u_xlat16_12.z = dot(unity_Builtins2Array[(u_xlati14 / 7)].unity_SHBbArray, u_xlat16_3));
  (u_xlat16_5.xyz = ((unity_Builtins2Array[(u_xlati14 / 7)].unity_SHCArray.xyz * u_xlat16_5.xxx) + u_xlat16_12.xyz));
  (u_xlat2.w = 1.0);
  (u_xlat16_13.x = dot(unity_Builtins2Array[(u_xlati14 / 7)].unity_SHArArray, u_xlat2));
  (u_xlat16_13.y = dot(unity_Builtins2Array[(u_xlati14 / 7)].unity_SHAgArray, u_xlat2));
  (u_xlat16_13.z = dot(unity_Builtins2Array[(u_xlati14 / 7)].unity_SHAbArray, u_xlat2));
  (u_xlat16_5.xyz = (u_xlat16_5.xyz + u_xlat16_13.xyz));
  (vs_TEXCOORD8.xyz = max(u_xlat16_5.xyz, vec3(0.0, 0.0, 0.0)));
  (vs_TEXCOORD4 = 0.0);
  (u_xlat16_5.x = (_MaxHeight + (-_MinHeight)));
  (u_xlat0.x = (1.0 / float(u_xlat16_5.x)));
  (u_xlat7 = (_WorldSpaceCameraPos.y + (-_MinHeight)));
  (u_xlat0.x = (u_xlat0.x * u_xlat7));
  (u_xlat0.x = clamp(u_xlat0.x, 0.0, 1.0));
  (u_xlat16_5.x = ((-_HeightBlendScale) + 1.0));
  (vs_TEXCOORD5.w = (((-u_xlat0.x) * u_xlat16_5.x) + 1.0));
  (vs_TEXCOORD5.xyz = u_xlat1.xyz);
  (vs_TEXCOORD6.xy = ((in_TEXCOORD0.xy * _Splat_Golobal_ST.xy) + _Splat_Golobal_ST.zw));
  (vs_TEXCOORD6.zw = ((in_TEXCOORD0.xy * _SparkMap_ST.xy) + _SparkMap_ST.zw));
  (u_xlat0 = (u_xlat1.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat0 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat1.xxxx) + u_xlat0));
  (u_xlat0 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat1.zzzz) + u_xlat0));
  (u_xlat0 = (u_xlat0 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (u_xlat1.x = (u_xlat0.y * _ProjectionParams.x));
  (u_xlat1.w = (u_xlat1.x * 0.5));
  (u_xlat1.xz = (u_xlat0.xw * vec2(0.5, 0.5)));
  (vs_TEXCOORD7.xy = (u_xlat1.zz + u_xlat1.xw));
  (vs_TEXCOORD7.zw = u_xlat0.zw);
  (gl_Position = u_xlat0);
  return ;
}
