#version 450
uniform vec4 _MainLightPosition;
uniform vec4 _ProjectionParams;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform int unity_BaseInstanceID;
uniform vec4 _ViewDir;
uniform vec4 _BackLightDir;
uniform float _SSSDistort;
struct unity_Builtins0Array_Type {
  vec4 hlslcc_mtx4x4unity_ObjectToWorldArray[4];
  vec4 hlslcc_mtx4x4unity_WorldToObjectArray[4];
};
layout(std140, binding = 1) uniform UnityInstancing_PerDraw0{
  unity_Builtins0Array_Type unity_Builtins0Array[128];
};
struct unity_Builtins2Array_Type {
  vec4 unity_SHArArray;
  vec4 unity_SHAgArray;
  vec4 unity_SHAbArray;
  vec4 unity_SHBrArray;
  vec4 unity_SHBgArray;
  vec4 unity_SHBbArray;
  vec4 unity_SHCArray;
};
layout(std140, binding = 2) uniform UnityInstancing_PerDraw2{
  unity_Builtins2Array_Type unity_Builtins2Array[128];
};
in vec4 in_POSITION0;
in vec3 in_NORMAL0;
in vec2 in_TEXCOORD0;
in vec2 in_TEXCOORD1;
out vec3 vs_TEXCOORD1;
out vec4 vs_TEXCOORD2;
out vec4 vs_TEXCOORD3;
out vec4 vs_TEXCOORD4;
out vec4 vs_TEXCOORD5;
out vec4 vs_TEXCOORD6;
out vec3 vs_TEXCOORD7;
flat out uint vs_SV_InstanceID0;
vec4 u_xlat0;
int u_xlati0;
vec4 u_xlat1;
vec4 u_xlat2;
vec4 u_xlat3;
vec3 u_xlat16_4;
vec4 u_xlat16_5;
vec3 u_xlat16_6;
float u_xlat7;
int u_xlati7;
void main(){
  (u_xlati0 = (gl_InstanceID + unity_BaseInstanceID));
  (u_xlati7 = int((u_xlati0 << 3)));
  (u_xlati0 = (u_xlati0 * 7));
  (u_xlat1.xyz = (in_POSITION0.yyy * unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[1].xyz));
  (u_xlat1.xyz = ((unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[0].xyz * in_POSITION0.xxx) + u_xlat1.xyz));
  (u_xlat1.xyz = ((unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[2].xyz * in_POSITION0.zzz) + u_xlat1.xyz));
  (u_xlat2.xyz = (u_xlat1.xyz + unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[3].xyz));
  (u_xlat3 = (u_xlat2.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat3 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat2.xxxx) + u_xlat3));
  (u_xlat3 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat2.zzzz) + u_xlat3));
  (vs_TEXCOORD2.xyz = u_xlat2.xyz);
  (u_xlat2 = (u_xlat3 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (gl_Position = u_xlat2);
  (u_xlat3 = (in_NORMAL0.yyyy * unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[1].xyzz));
  (u_xlat3 = ((unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[0].xyzz * in_NORMAL0.xxxx) + u_xlat3));
  (u_xlat3 = ((unity_Builtins0Array[(u_xlati7 / 8)].hlslcc_mtx4x4unity_ObjectToWorldArray[2].xyzz * in_NORMAL0.zzzz) + u_xlat3));
  (u_xlat7 = dot(u_xlat3.xyw, u_xlat3.xyw));
  (u_xlat7 = max(u_xlat7, 0.0));
  (u_xlat7 = inversesqrt(u_xlat7));
  (u_xlat3 = (vec4(u_xlat7) * u_xlat3.xywz));
  (u_xlat16_4.x = (u_xlat3.y * u_xlat3.y));
  (u_xlat16_4.x = ((u_xlat3.x * u_xlat3.x) + (-u_xlat16_4.x)));
  (u_xlat16_5 = (u_xlat3.yzwx * u_xlat3.xywz));
  (u_xlat16_6.x = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHBrArray, u_xlat16_5));
  (u_xlat16_6.y = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHBgArray, u_xlat16_5));
  (u_xlat16_6.z = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHBbArray, u_xlat16_5));
  (u_xlat16_4.xyz = ((unity_Builtins2Array[(u_xlati0 / 7)].unity_SHCArray.xyz * u_xlat16_4.xxx) + u_xlat16_6.xyz));
  (vs_TEXCOORD3.w = dot(u_xlat3.xyz, _MainLightPosition.xyz));
  (vs_TEXCOORD3.w = clamp(vs_TEXCOORD3.w, 0.0, 1.0));
  (u_xlat3.w = 1.0);
  (u_xlat16_5.x = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHArArray, u_xlat3));
  (u_xlat16_5.y = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHAgArray, u_xlat3));
  (u_xlat16_5.z = dot(unity_Builtins2Array[(u_xlati0 / 7)].unity_SHAbArray, u_xlat3));
  (vs_TEXCOORD3.xyz = u_xlat3.xyz);
  (u_xlat16_4.xyz = (u_xlat16_4.xyz + u_xlat16_5.xyz));
  (vs_TEXCOORD1.xyz = max(u_xlat16_4.xyz, vec3(0.0, 0.0, 0.0)));
  (u_xlat0.x = dot(u_xlat1.xyz, u_xlat1.xyz));
  (u_xlat0.x = inversesqrt(u_xlat0.x));
  (u_xlat0.xyz = (u_xlat0.xxx * u_xlat1.xyz));
  (u_xlat1.xyz = (u_xlat0.xyz * vec3(_SSSDistort)));
  (vs_TEXCOORD6.xyz = u_xlat0.xyz);
  (u_xlat1.w = 0.0);
  (u_xlat0 = (u_xlat1 + _BackLightDir));
  (u_xlat1.x = dot(u_xlat0, u_xlat0));
  (u_xlat1.x = inversesqrt(u_xlat1.x));
  (u_xlat0 = (u_xlat0 * u_xlat1.xxxx));
  (u_xlat16_4.x = dot((-u_xlat0), _ViewDir));
  (u_xlat16_4.x = clamp(u_xlat16_4.x, 0.0, 1.0));
  (vs_TEXCOORD2.w = u_xlat16_4.x);
  (u_xlat0.x = (u_xlat2.y * _ProjectionParams.x));
  (u_xlat0.w = (u_xlat0.x * 0.5));
  (u_xlat0.xz = (u_xlat2.xw * vec2(0.5, 0.5)));
  (vs_TEXCOORD4.zw = u_xlat2.zw);
  (vs_TEXCOORD4.xy = (u_xlat0.zz + u_xlat0.xw));
  (vs_TEXCOORD5.xy = in_TEXCOORD1.xy);
  (vs_TEXCOORD5.zw = in_TEXCOORD0.xy);
  (vs_TEXCOORD6.w = 0.0);
  (vs_TEXCOORD7.xyz = vec3(0.0, 0.0, 0.0));
  (vs_SV_InstanceID0 = uint(gl_InstanceID));
  return ;
}
