#version 450
uniform vec4 _MainLightPosition;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
layout(std140, binding = 0) uniform UnityPerDraw{
  vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
  vec4 hlslcc_mtx4x4unity_WorldToObject[4];
  vec4 unity_LODFade;
  vec4 unity_WorldTransformParams;
  vec4 unity_RenderingLayer;
  vec4 unity_LightData;
  vec4 unity_LightIndices[2];
  vec4 unity_ProbesOcclusion;
  vec4 unity_SpecCube0_HDR;
  vec4 unity_SpecCube1_HDR;
  vec4 unity_SpecCube0_BoxMax;
  vec4 unity_SpecCube0_BoxMin;
  vec4 unity_SpecCube0_ProbePosition;
  vec4 unity_SpecCube1_BoxMax;
  vec4 unity_SpecCube1_BoxMin;
  vec4 unity_SpecCube1_ProbePosition;
  vec4 unity_LightmapST;
  vec4 unity_DynamicLightmapST;
  vec4 unity_SHAr;
  vec4 unity_SHAg;
  vec4 unity_SHAb;
  vec4 unity_SHBr;
  vec4 unity_SHBg;
  vec4 unity_SHBb;
  vec4 unity_SHC;
  vec4 hlslcc_mtx4x4unity_MatrixPreviousM[4];
  vec4 hlslcc_mtx4x4unity_MatrixPreviousMI[4];
  vec4 unity_MotionVectorsParams;
};
layout(std140, binding = 1) uniform UnityPerMaterial{
  vec4 _CustomLightDir;
  vec4 _ShadowColor;
  float _UseCustomLightDir;
  float _GroundHeight;
  float _ShadowFalloff;
  float _Cut;
};
in vec4 in_POSITION0;
in vec2 in_TEXCOORD0;
out vec4 vs_COLOR0;
out vec2 vs_TEXCOORD0;
vec4 u_xlat0;
vec4 u_xlat1;
vec3 u_xlat16_1;
vec2 u_xlat2;
float u_xlat3;
float u_xlat9;
void main(){
  (u_xlat0.xyz = (in_POSITION0.yyy * hlslcc_mtx4x4unity_ObjectToWorld[1].xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[0].xyz * in_POSITION0.xxx) + u_xlat0.xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[2].xyz * in_POSITION0.zzz) + u_xlat0.xyz));
  (u_xlat0.xyz = (u_xlat0.xyz + hlslcc_mtx4x4unity_ObjectToWorld[3].xyz));
  (u_xlat9 = (u_xlat0.y + (-_GroundHeight)));
  (u_xlat9 = max(u_xlat9, 0.0));
  (u_xlat16_1.xyz = ((-_MainLightPosition.xyz) + _CustomLightDir.xyz));
  (u_xlat16_1.xyz = ((vec3(_UseCustomLightDir) * u_xlat16_1.xyz) + _MainLightPosition.xyz));
  (u_xlat2.xy = (vec2(u_xlat9) * u_xlat16_1.xz));
  (u_xlat9 = (1.0 / float(u_xlat16_1.y)));
  (u_xlat0.xz = (((-u_xlat2.xy) * vec2(u_xlat9)) + u_xlat0.xz));
  (u_xlat3 = min(u_xlat0.y, _GroundHeight));
  (u_xlat1 = (vec4(u_xlat3) * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx) + u_xlat1));
  (u_xlat0 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz) + u_xlat1));
  (gl_Position = (u_xlat0 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (vs_COLOR0.w = (_ShadowColor.w * 0.89999998));
  (vs_COLOR0.xyz = _ShadowColor.xyz);
  (vs_TEXCOORD0.xy = in_TEXCOORD0.xy);
  return ;
}
