#version 450
uniform vec3 _WorldSpaceCameraPos;
uniform vec4 unity_OrthoParams;
uniform vec4 hlslcc_mtx4x4unity_MatrixV[4];
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
layout(std140, binding = 1) uniform UnityPerDraw{
  vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
  vec4 hlslcc_mtx4x4unity_WorldToObject[4];
  vec4 unity_LODFade;
  vec4 unity_WorldTransformParams;
  vec4 unity_RenderingLayer;
  vec4 unity_LightData;
  vec4 unity_LightIndices[2];
  vec4 unity_ProbesOcclusion;
  vec4 unity_SpecCube0_HDR;
  vec4 unity_SpecCube1_HDR;
  vec4 unity_SpecCube0_BoxMax;
  vec4 unity_SpecCube0_BoxMin;
  vec4 unity_SpecCube0_ProbePosition;
  vec4 unity_SpecCube1_BoxMax;
  vec4 unity_SpecCube1_BoxMin;
  vec4 unity_SpecCube1_ProbePosition;
  vec4 unity_LightmapST;
  vec4 unity_DynamicLightmapST;
  vec4 unity_SHAr;
  vec4 unity_SHAg;
  vec4 unity_SHAb;
  vec4 unity_SHBr;
  vec4 unity_SHBg;
  vec4 unity_SHBb;
  vec4 unity_SHC;
  vec4 hlslcc_mtx4x4unity_MatrixPreviousM[4];
  vec4 hlslcc_mtx4x4unity_MatrixPreviousMI[4];
  vec4 unity_MotionVectorsParams;
};
in vec4 in_POSITION0;
in vec2 in_TEXCOORD0;
in vec2 in_TEXCOORD1;
in vec3 in_NORMAL0;
in vec4 in_TANGENT0;
out vec4 vs_TEXCOORD0;
out vec4 vs_TEXCOORD1;
out vec4 vs_TEXCOORD2;
out vec4 vs_TEXCOORD3;
out vec4 vs_TEXCOORD4;
vec4 u_xlat0;
vec4 u_xlat1;
vec3 u_xlat2;
vec3 u_xlat16_3;
float u_xlat12;
bool u_xlatb12;
void main(){
  (u_xlat0 = (in_POSITION0.yyyy * hlslcc_mtx4x4unity_ObjectToWorld[1]));
  (u_xlat0 = ((hlslcc_mtx4x4unity_ObjectToWorld[0] * in_POSITION0.xxxx) + u_xlat0));
  (u_xlat0 = ((hlslcc_mtx4x4unity_ObjectToWorld[2] * in_POSITION0.zzzz) + u_xlat0));
  (u_xlat0 = (u_xlat0 + hlslcc_mtx4x4unity_ObjectToWorld[3]));
  (u_xlat1 = (u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx) + u_xlat1));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz) + u_xlat1));
  (gl_Position = ((hlslcc_mtx4x4unity_MatrixVP[3] * u_xlat0.wwww) + u_xlat1));
  (vs_TEXCOORD0.xy = in_TEXCOORD0.xy);
  (vs_TEXCOORD0.zw = in_TEXCOORD1.xy);
  (u_xlat1.xyz = ((-u_xlat0.xyz) + _WorldSpaceCameraPos.xyz));
  (u_xlatb12 = (unity_OrthoParams.w == 0.0));
  (u_xlat2.x = ((u_xlatb12) ? (u_xlat1.x) : (hlslcc_mtx4x4unity_MatrixV[0].z)));
  (u_xlat2.y = ((u_xlatb12) ? (u_xlat1.y) : (hlslcc_mtx4x4unity_MatrixV[1].z)));
  (u_xlat2.z = ((u_xlatb12) ? (u_xlat1.z) : (hlslcc_mtx4x4unity_MatrixV[2].z)));
  (u_xlat12 = dot(u_xlat2.xyz, u_xlat2.xyz));
  (u_xlat12 = inversesqrt(u_xlat12));
  (u_xlat1.xyz = (vec3(u_xlat12) * u_xlat2.xyz));
  (vs_TEXCOORD1.xyz = u_xlat1.xyz);
  (vs_TEXCOORD1.w = 0.0);
  (vs_TEXCOORD2.w = u_xlat0.x);
  (u_xlat1.x = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[0].xyz));
  (u_xlat1.y = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[1].xyz));
  (u_xlat1.z = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[2].xyz));
  (u_xlat0.x = dot(u_xlat1.xyz, u_xlat1.xyz));
  (u_xlat0.x = max(u_xlat0.x, 0.0));
  (u_xlat0.x = inversesqrt(u_xlat0.x));
  (u_xlat1.xyz = (u_xlat0.xxx * u_xlat1.xyz));
  (vs_TEXCOORD2.xyz = u_xlat1.xyz);
  (vs_TEXCOORD3.w = u_xlat0.y);
  (vs_TEXCOORD4.w = u_xlat0.z);
  (u_xlat0.xyz = (in_TANGENT0.yyy * hlslcc_mtx4x4unity_ObjectToWorld[1].xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[0].xyz * in_TANGENT0.xxx) + u_xlat0.xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[2].xyz * in_TANGENT0.zzz) + u_xlat0.xyz));
  (u_xlat12 = dot(u_xlat0.xyz, u_xlat0.xyz));
  (u_xlat12 = max(u_xlat12, 0.0));
  (u_xlat12 = inversesqrt(u_xlat12));
  (u_xlat0.xyz = (vec3(u_xlat12) * u_xlat0.xyz));
  (vs_TEXCOORD3.xyz = u_xlat0.xyz);
  (u_xlat2.xyz = (u_xlat0.yzx * u_xlat1.zxy));
  (u_xlat0.xyz = ((u_xlat1.yzx * u_xlat0.zxy) + (-u_xlat2.xyz)));
  (u_xlatb12 = (unity_WorldTransformParams.w >= 0.0));
  (u_xlat12 = ((u_xlatb12) ? (1.0) : (-1.0)));
  (u_xlat16_3.x = (u_xlat12 * in_TANGENT0.w));
  (u_xlat16_3.xyz = (u_xlat0.xyz * u_xlat16_3.xxx));
  (vs_TEXCOORD4.xyz = u_xlat16_3.xyz);
  return ;
}
