#version 450
uniform vec4 _MainLightColor;
uniform vec2 _GlobalMipBias;
layout(std140, binding = 0) uniform UnityPerDraw{
  vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
  vec4 hlslcc_mtx4x4unity_WorldToObject[4];
  vec4 unity_LODFade;
  vec4 unity_WorldTransformParams;
  vec4 unity_RenderingLayer;
  vec4 unity_LightData;
  vec4 unity_LightIndices[2];
  vec4 unity_ProbesOcclusion;
  vec4 unity_SpecCube0_HDR;
  vec4 unity_SpecCube1_HDR;
  vec4 unity_SpecCube0_BoxMax;
  vec4 unity_SpecCube0_BoxMin;
  vec4 unity_SpecCube0_ProbePosition;
  vec4 unity_SpecCube1_BoxMax;
  vec4 unity_SpecCube1_BoxMin;
  vec4 unity_SpecCube1_ProbePosition;
  vec4 unity_LightmapST;
  vec4 unity_DynamicLightmapST;
  vec4 unity_SHAr;
  vec4 unity_SHAg;
  vec4 unity_SHAb;
  vec4 unity_SHBr;
  vec4 unity_SHBg;
  vec4 unity_SHBb;
  vec4 unity_SHC;
  vec4 hlslcc_mtx4x4unity_MatrixPreviousM[4];
  vec4 hlslcc_mtx4x4unity_MatrixPreviousMI[4];
  vec4 unity_MotionVectorsParams;
};
layout(std140, binding = 1) uniform UnityPerMaterial{
  vec4 _Control_ST;
  vec4 _DissolveTex_ST;
  vec4 _Control_TexelSize;
  vec4 _WorldEdge;
  vec4 _EnvColor;
  vec4 _Decal_Color;
  vec4 _CustomLightColor;
  vec4 _CustomLightDir;
  vec4 _DiffuseRemapScale0;
  vec4 _DiffuseRemapScale1;
  vec4 _DiffuseRemapScale2;
  vec4 _DiffuseRemapScale3;
  vec4 _Splat0_ST;
  vec4 _Splat1_ST;
  vec4 _Splat2_ST;
  vec4 _Splat3_ST;
  vec4 _EdgeColor;
  float _CustomEnv_ON;
  float _DissolveProgress;
  float _EdgeSize;
  float _DissolveMin;
  float _DissolveMax;
  float _CustomLightIntensity;
};
layout(location = 0) uniform sampler2D _PlaneBlurShadowMap;
layout(location = 1) uniform sampler2D _Control;
layout(location = 2) uniform sampler2D _Splat0;
layout(location = 3) uniform sampler2D _Splat1;
layout(location = 4) uniform sampler2D _Splat2;
layout(location = 5) uniform sampler2D _Splat3;
in vec2 vs_TEXCOORD0;
in vec4 vs_TEXCOORD1;
in vec4 vs_TEXCOORD2;
in vec4 vs_TEXCOORD3;
in vec4 vs_TEXCOORD7;
layout(location = 0) out vec4 SV_TARGET0;
vec2 u_xlat0;
vec4 u_xlat16_0;
vec3 u_xlat16_1;
vec3 u_xlat2;
vec3 u_xlat16_2;
vec3 u_xlat16_3;
vec3 u_xlat16_4;
vec2 u_xlat5;
float u_xlat16_20;
void main(){
  (u_xlat0.xy = (_Control_TexelSize.zw + vec2(-1.0, -1.0)));
  (u_xlat0.xy = ((vs_TEXCOORD0.xy * u_xlat0.xy) + vec2(0.5, 0.5)));
  (u_xlat0.xy = (u_xlat0.xy * _Control_TexelSize.xy));
  (u_xlat16_0 = texture(_Control, u_xlat0.xy, _GlobalMipBias.x));
  (u_xlat16_1.x = (u_xlat16_0.y + u_xlat16_0.x));
  (u_xlat16_1.x = (u_xlat16_0.z + u_xlat16_1.x));
  (u_xlat16_1.x = (u_xlat16_0.w + u_xlat16_1.x));
  (u_xlat16_1.x = (u_xlat16_1.x + 6.1035156e-05));
  (u_xlat16_1.x = (1.0 / float(u_xlat16_1.x)));
  (u_xlat16_0 = (u_xlat16_0 * u_xlat16_1.xxxx));
  (u_xlat16_1.xyz = (u_xlat16_0.yyy * _DiffuseRemapScale1.xyz));
  (u_xlat16_2.xyz = texture(_Splat1, vs_TEXCOORD1.zw, _GlobalMipBias.x).xyz);
  (u_xlat16_1.xyz = (u_xlat16_1.xyz * u_xlat16_2.xyz));
  (u_xlat16_3.xyz = (u_xlat16_0.xxx * _DiffuseRemapScale0.xyz));
  (u_xlat16_2.xyz = texture(_Splat0, vs_TEXCOORD1.xy, _GlobalMipBias.x).xyz);
  (u_xlat16_1.xyz = ((u_xlat16_2.xyz * u_xlat16_3.xyz) + u_xlat16_1.xyz));
  (u_xlat16_3.xyz = (u_xlat16_0.zzz * _DiffuseRemapScale2.xyz));
  (u_xlat16_4.xyz = (u_xlat16_0.www * _DiffuseRemapScale3.xyz));
  (u_xlat16_2.xyz = texture(_Splat2, vs_TEXCOORD2.xy, _GlobalMipBias.x).xyz);
  (u_xlat16_1.xyz = ((u_xlat16_2.xyz * u_xlat16_3.xyz) + u_xlat16_1.xyz));
  (u_xlat16_2.xyz = texture(_Splat3, vs_TEXCOORD2.zw, _GlobalMipBias.x).xyz);
  (u_xlat16_1.xyz = ((u_xlat16_2.xyz * u_xlat16_4.xyz) + u_xlat16_1.xyz));
  (u_xlat16_1.xyz = (u_xlat16_1.xyz * _MainLightColor.xyz));
  (u_xlat2.xyz = (u_xlat16_1.xyz * unity_LightData.zzz));
  (u_xlat2.xyz = (u_xlat2.xyz * vs_TEXCOORD3.www));
  (u_xlat16_1.xyz = (u_xlat2.xyz * vec3(0.5, 0.5, 0.5)));
  (u_xlat5.xy = (vs_TEXCOORD7.xy / vs_TEXCOORD7.ww));
  (u_xlat16_20 = texture(_PlaneBlurShadowMap, u_xlat5.xy).x);
  (u_xlat16_1.xyz = (u_xlat16_1.xyz * vec3(u_xlat16_20)));
  (SV_TARGET0.xyz = ((u_xlat2.xyz * vec3(0.5, 0.5, 0.5)) + u_xlat16_1.xyz));
  (SV_TARGET0.w = 1.0);
  return ;
}
