#version 450
uniform vec3 _WorldSpaceCameraPos;
uniform vec4 _ScreenParams;
uniform vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
uniform vec4 hlslcc_mtx4x4unity_WorldToObject[4];
uniform vec4 hlslcc_mtx4x4glstate_matrix_projection[4];
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform float _FaceDilate;
uniform float _OutlineSoftness;
uniform float _OutlineWidth;
uniform vec4 hlslcc_mtx4x4_EnvMatrix[4];
uniform float _WeightNormal;
uniform float _WeightBold;
uniform float _ScaleRatioA;
uniform float _VertexOffsetX;
uniform float _VertexOffsetY;
uniform vec4 _ClipRect;
uniform float _MaskSoftnessX;
uniform float _MaskSoftnessY;
uniform float _GradientScale;
uniform float _ScaleX;
uniform float _ScaleY;
uniform float _PerspectiveFilter;
uniform float _Sharpness;
uniform vec4 _FaceTex_ST;
uniform vec4 _OutlineTex_ST;
in vec4 in_POSITION0;
in vec3 in_NORMAL0;
in vec4 in_COLOR0;
in vec2 in_TEXCOORD0;
in vec2 in_TEXCOORD1;
out vec4 vs_COLOR0;
out vec2 vs_TEXCOORD0;
out vec4 vs_TEXCOORD1;
out vec4 vs_TEXCOORD2;
out vec3 vs_TEXCOORD3;
out vec4 vs_TEXCOORD5;
vec3 u_xlat0;
vec4 u_xlat1;
vec4 u_xlat2;
vec4 u_xlat3;
vec3 u_xlat6;
vec2 u_xlat8;
bool u_xlatb8;
float u_xlat12;
bool u_xlatb12;
float u_xlat13;
void main(){
  (u_xlat0.xy = (in_POSITION0.xy + vec2(_VertexOffsetX, _VertexOffsetY)));
  (u_xlat1 = (u_xlat0.yyyy * hlslcc_mtx4x4unity_ObjectToWorld[1]));
  (u_xlat1 = ((hlslcc_mtx4x4unity_ObjectToWorld[0] * u_xlat0.xxxx) + u_xlat1));
  (u_xlat1 = ((hlslcc_mtx4x4unity_ObjectToWorld[2] * in_POSITION0.zzzz) + u_xlat1));
  (u_xlat2 = (u_xlat1 + hlslcc_mtx4x4unity_ObjectToWorld[3]));
  (u_xlat1.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[3].xyz * in_POSITION0.www) + u_xlat1.xyz));
  (u_xlat1.xyz = ((-u_xlat1.xyz) + _WorldSpaceCameraPos.xyz));
  (u_xlat3 = (u_xlat2.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat3 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat2.xxxx) + u_xlat3));
  (u_xlat3 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat2.zzzz) + u_xlat3));
  (u_xlat2 = ((hlslcc_mtx4x4unity_MatrixVP[3] * u_xlat2.wwww) + u_xlat3));
  (gl_Position = u_xlat2);
  (vs_COLOR0 = in_COLOR0);
  (vs_TEXCOORD0.xy = in_TEXCOORD0.xy);
  (u_xlat8.xy = (_ScreenParams.yy * hlslcc_mtx4x4glstate_matrix_projection[1].xy));
  (u_xlat8.xy = ((hlslcc_mtx4x4glstate_matrix_projection[0].xy * _ScreenParams.xx) + u_xlat8.xy));
  (u_xlat8.xy = (abs(u_xlat8.xy) * vec2(_ScaleX, _ScaleY)));
  (u_xlat8.xy = (u_xlat2.ww / u_xlat8.xy));
  (u_xlat13 = dot(u_xlat8.xy, u_xlat8.xy));
  (u_xlat8.xy = ((vec2(_MaskSoftnessX, _MaskSoftnessY) * vec2(0.25, 0.25)) + u_xlat8.xy));
  (vs_TEXCOORD2.zw = (vec2(0.25, 0.25) / u_xlat8.xy));
  (u_xlat8.x = inversesqrt(u_xlat13));
  (u_xlat12 = (abs(in_TEXCOORD1.y) * _GradientScale));
  (u_xlat13 = (_Sharpness + 1.0));
  (u_xlat12 = (u_xlat12 * u_xlat13));
  (u_xlat13 = (u_xlat12 * u_xlat8.x));
  (u_xlat2.x = ((-_PerspectiveFilter) + 1.0));
  (u_xlat2.x = (abs(u_xlat13) * u_xlat2.x));
  (u_xlat8.x = ((u_xlat8.x * u_xlat12) + (-u_xlat2.x)));
  (u_xlat3.x = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[0].xyz));
  (u_xlat3.y = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[1].xyz));
  (u_xlat3.z = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[2].xyz));
  (u_xlat12 = dot(u_xlat3.xyz, u_xlat3.xyz));
  (u_xlat12 = inversesqrt(u_xlat12));
  (u_xlat6.xyz = (vec3(u_xlat12) * u_xlat3.xyz));
  (u_xlat12 = dot(u_xlat1.xyz, u_xlat1.xyz));
  (u_xlat12 = inversesqrt(u_xlat12));
  (u_xlat3.xyz = (vec3(u_xlat12) * u_xlat1.xyz));
  (u_xlat12 = dot(u_xlat6.xyz, u_xlat3.xyz));
  (u_xlat8.x = ((abs(u_xlat12) * u_xlat8.x) + u_xlat2.x));
  (u_xlatb12 = (hlslcc_mtx4x4glstate_matrix_projection[3].w == 0.0));
  (u_xlat6.x = ((u_xlatb12) ? (u_xlat8.x) : (u_xlat13)));
  (u_xlatb8 = (0.0 >= in_TEXCOORD1.y));
  (u_xlat8.x = ((u_xlatb8) ? (1.0) : (0.0)));
  (u_xlat12 = ((-_WeightNormal) + _WeightBold));
  (u_xlat8.x = ((u_xlat8.x * u_xlat12) + _WeightNormal));
  (u_xlat8.x = ((u_xlat8.x * 0.25) + _FaceDilate));
  (u_xlat8.x = (u_xlat8.x * _ScaleRatioA));
  (u_xlat6.z = (u_xlat8.x * 0.5));
  (vs_TEXCOORD1.yw = u_xlat6.xz);
  (u_xlat12 = (0.5 / u_xlat6.x));
  (u_xlat13 = (((-_OutlineWidth) * _ScaleRatioA) + 1.0));
  (u_xlat13 = (((-_OutlineSoftness) * _ScaleRatioA) + u_xlat13));
  (u_xlat13 = ((u_xlat13 * 0.5) + (-u_xlat12)));
  (vs_TEXCOORD1.x = (((-u_xlat8.x) * 0.5) + u_xlat13));
  (u_xlat8.x = (((-u_xlat8.x) * 0.5) + 0.5));
  (vs_TEXCOORD1.z = (u_xlat12 + u_xlat8.x));
  (u_xlat2 = max(_ClipRect, vec4(-20000000000.0, -20000000000.0, -20000000000.0, -20000000000.0)));
  (u_xlat2 = min(u_xlat2, vec4(20000000000.0, 20000000000.0, 20000000000.0, 20000000000.0)));
  (u_xlat0.xy = ((u_xlat0.xy * vec2(2.0, 2.0)) + (-u_xlat2.xy)));
  (vs_TEXCOORD2.xy = ((-u_xlat2.zw) + u_xlat0.xy));
  (u_xlat0.xyz = (u_xlat1.yyy * hlslcc_mtx4x4_EnvMatrix[1].xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4_EnvMatrix[0].xyz * u_xlat1.xxx) + u_xlat0.xyz));
  (vs_TEXCOORD3.xyz = ((hlslcc_mtx4x4_EnvMatrix[2].xyz * u_xlat1.zzz) + u_xlat0.xyz));
  (u_xlat0.x = (in_TEXCOORD1.x * 0.00024414062));
  (u_xlat8.x = floor(u_xlat0.x));
  (u_xlat8.y = (((-u_xlat8.x) * 4096.0) + in_TEXCOORD1.x));
  (u_xlat0.xy = (u_xlat8.xy * vec2(0.001953125, 0.001953125)));
  (vs_TEXCOORD5.xy = ((u_xlat0.xy * _FaceTex_ST.xy) + _FaceTex_ST.zw));
  (vs_TEXCOORD5.zw = ((u_xlat0.xy * _OutlineTex_ST.xy) + _OutlineTex_ST.zw));
  return ;
}
