#version 450
uniform vec3 _WorldSpaceCameraPos;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform vec4 hlslcc_mtx4x4_MainLightWorldToShadow[20];
uniform float _FogStart;
uniform float _FogEnd;
uniform float _FogGlobalDensity;
uniform float _FogFallOff;
uniform float _FogHeight;
uniform float _FogStartDis;
uniform float _FogGradientDis;
layout(std140, binding = 1) uniform UnityPerDraw{
  vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
  vec4 hlslcc_mtx4x4unity_WorldToObject[4];
  vec4 unity_LODFade;
  vec4 unity_WorldTransformParams;
  vec4 unity_RenderingLayer;
  vec4 unity_LightData;
  vec4 unity_LightIndices[2];
  vec4 unity_ProbesOcclusion;
  vec4 unity_SpecCube0_HDR;
  vec4 unity_SpecCube1_HDR;
  vec4 unity_SpecCube0_BoxMax;
  vec4 unity_SpecCube0_BoxMin;
  vec4 unity_SpecCube0_ProbePosition;
  vec4 unity_SpecCube1_BoxMax;
  vec4 unity_SpecCube1_BoxMin;
  vec4 unity_SpecCube1_ProbePosition;
  vec4 unity_LightmapST;
  vec4 unity_DynamicLightmapST;
  vec4 unity_SHAr;
  vec4 unity_SHAg;
  vec4 unity_SHAb;
  vec4 unity_SHBr;
  vec4 unity_SHBg;
  vec4 unity_SHBb;
  vec4 unity_SHC;
  vec4 hlslcc_mtx4x4unity_MatrixPreviousM[4];
  vec4 hlslcc_mtx4x4unity_MatrixPreviousMI[4];
  vec4 unity_MotionVectorsParams;
};
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _SepcularGloss_ST;
  vec4 _MainTex_ST;
  vec4 _ReflectionMap_HDR;
  vec4 _BaseColor;
  vec4 ReflectionDir;
  float _Reflectivity;
  float _Smoothness0;
  float _CutValue;
  float _ReflectionIntenSity;
};
in vec4 in_POSITION0;
in vec3 in_NORMAL0;
in vec4 in_TEXCOORD0;
out vec3 vs_TEXCOORD0;
out float vs_TEXCOORD2;
out vec4 vs_TEXCOORD1;
out vec4 vs_TEXCOORD3;
out vec3 vs_TEXCOORD4;
vec4 u_xlat0;
vec4 u_xlat1;
float u_xlat3;
float u_xlat6;
void main(){
  (u_xlat0.xyz = (in_POSITION0.yyy * hlslcc_mtx4x4unity_ObjectToWorld[1].xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[0].xyz * in_POSITION0.xxx) + u_xlat0.xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[2].xyz * in_POSITION0.zzz) + u_xlat0.xyz));
  (u_xlat0.xyz = (u_xlat0.xyz + hlslcc_mtx4x4unity_ObjectToWorld[3].xyz));
  (u_xlat1 = (u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx) + u_xlat1));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz) + u_xlat1));
  (gl_Position = (u_xlat1 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (u_xlat6 = (_FogFallOff * 0.0099999998));
  (u_xlat1.x = (u_xlat0.y + (-_WorldSpaceCameraPos.y)));
  (u_xlat1.x = (u_xlat1.x + (-_FogHeight)));
  (u_xlat6 = (u_xlat6 * u_xlat1.x));
  (u_xlat1.x = exp2((-u_xlat6)));
  (u_xlat3 = ((-u_xlat1.x) + 1.0));
  (u_xlat1.x = (u_xlat1.x * _FogGlobalDensity));
  (u_xlat6 = (u_xlat3 / u_xlat6));
  (u_xlat6 = (u_xlat1.x * u_xlat6));
  (u_xlat1.xyz = ((-u_xlat0.xyz) + _WorldSpaceCameraPos.xyz));
  (u_xlat1.x = dot(u_xlat1.xyz, u_xlat1.xyz));
  (u_xlat1.x = max(u_xlat1.x, 6.1035156e-05));
  (u_xlat1.x = sqrt(u_xlat1.x));
  (u_xlat1.x = (u_xlat1.x + (-_FogStartDis)));
  (u_xlat1.x = (u_xlat1.x / _FogGradientDis));
  (u_xlat1.x = max(u_xlat1.x, 0.0));
  (u_xlat6 = ((u_xlat6 * u_xlat1.x) + (-_FogStart)));
  (u_xlat1.x = ((-_FogStart) + _FogEnd));
  (u_xlat1.x = (1.0 / u_xlat1.x));
  (u_xlat6 = (u_xlat6 * u_xlat1.x));
  (u_xlat6 = clamp(u_xlat6, 0.0, 1.0));
  (u_xlat1.x = ((u_xlat6 * -2.0) + 3.0));
  (u_xlat6 = (u_xlat6 * u_xlat6));
  (vs_TEXCOORD2 = (u_xlat6 * u_xlat1.x));
  (vs_TEXCOORD0.xyz = u_xlat0.xyz);
  (u_xlat1.xyz = (u_xlat0.yyy * hlslcc_mtx4x4_MainLightWorldToShadow[1].xyz));
  (u_xlat0.xyw = ((hlslcc_mtx4x4_MainLightWorldToShadow[0].xyz * u_xlat0.xxx) + u_xlat1.xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4_MainLightWorldToShadow[2].xyz * u_xlat0.zzz) + u_xlat0.xyw));
  (vs_TEXCOORD1.xyz = (u_xlat0.xyz + hlslcc_mtx4x4_MainLightWorldToShadow[3].xyz));
  (vs_TEXCOORD1.w = 0.0);
  (vs_TEXCOORD3.xy = ((in_TEXCOORD0.xy * _MainTex_ST.xy) + _MainTex_ST.zw));
  (vs_TEXCOORD3.zw = ((in_TEXCOORD0.xy * _SepcularGloss_ST.xy) + _SepcularGloss_ST.zw));
  (u_xlat0.x = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[0].xyz));
  (u_xlat0.y = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[1].xyz));
  (u_xlat0.z = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[2].xyz));
  (u_xlat6 = dot(u_xlat0.xyz, u_xlat0.xyz));
  (u_xlat6 = max(u_xlat6, 0.0));
  (u_xlat6 = inversesqrt(u_xlat6));
  (vs_TEXCOORD4.xyz = (vec3(u_xlat6) * u_xlat0.xyz));
  return ;
}
