#version 450
uniform vec4 _Time;
uniform vec3 _WorldSpaceCameraPos;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
layout(std140, binding = 1) uniform UnityPerDraw{
  vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
  vec4 hlslcc_mtx4x4unity_WorldToObject[4];
  vec4 unity_LODFade;
  vec4 unity_WorldTransformParams;
  vec4 unity_RenderingLayer;
  vec4 unity_LightData;
  vec4 unity_LightIndices[2];
  vec4 unity_ProbesOcclusion;
  vec4 unity_SpecCube0_HDR;
  vec4 unity_SpecCube1_HDR;
  vec4 unity_SpecCube0_BoxMax;
  vec4 unity_SpecCube0_BoxMin;
  vec4 unity_SpecCube0_ProbePosition;
  vec4 unity_SpecCube1_BoxMax;
  vec4 unity_SpecCube1_BoxMin;
  vec4 unity_SpecCube1_ProbePosition;
  vec4 unity_LightmapST;
  vec4 unity_DynamicLightmapST;
  vec4 unity_SHAr;
  vec4 unity_SHAg;
  vec4 unity_SHAb;
  vec4 unity_SHBr;
  vec4 unity_SHBg;
  vec4 unity_SHBb;
  vec4 unity_SHC;
  vec4 hlslcc_mtx4x4unity_MatrixPreviousM[4];
  vec4 hlslcc_mtx4x4unity_MatrixPreviousMI[4];
  vec4 unity_MotionVectorsParams;
};
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _Turb_Noise_ST;
  vec4 _Mask_ST;
  vec4 _Tex_2_ST;
  vec4 _Main_Tex_ST;
  vec4 _Diss_Tex_ST;
  vec4 _Vertex_offset_ST;
  vec4 _Polar_UV;
  vec4 _Diss_Edge_color;
  vec4 _Main_Color;
  vec4 _VertexOffset_Value;
  vec2 _Tex_2_UV;
  vec2 _Diss_UV;
  vec2 _Remap_01;
  vec2 _Main_UV;
  vec2 _Turb_UV;
  vec2 _VertexOffset_UV;
  vec2 _Mask_UV;
  float _ZTest;
  float _Mask_Tex_Rotator;
  float _Fresnel_Scale;
  float _Fresnel_Power;
  float _Fresnel_speed;
  float _Fresnel_Bias;
  float _Alpha;
  float _AlphaSub;
  float _Diss_Soft_value;
  float _EdgeWidth;
  float _Diss_value;
  float _Turb_Diss_Value;
  float _Turb_Tex2_Value;
  float _Brightness;
  float _Saturation;
  float _Contrast;
  float _Main_tex_Rotator;
  float _Turb_MainTex_Value;
  float _Alpha_NO_R;
  float _Tex2_A_NO_R;
  vec4 _Tex02_Color;
  float _Mask_A;
  float _Diss_Edge_NO;
  float _Particle_diss_ON;
  float _Particle_SpeedUV;
  float _Polar_UV_offset;
  float _Tex2_Particle_SpeedUV;
  int _FlipBookBlend_On;
  int _AlphaPremultiply;
  int _InvertFresnel;
  int _ParallaxOn;
  int _ParallaxChannel;
  float _ParallaxScale;
  vec4 _ParallaxEdgeColor;
};
in vec4 in_POSITION0;
in vec4 in_TEXCOORD0;
in vec4 in_TEXCOORD1;
in vec4 in_TEXCOORD2;
in vec4 in_COLOR0;
in vec4 in_TANGENT0;
out vec3 vs_TEXCOORD0;
out vec4 vs_TEXCOORD1;
out vec4 vs_TEXCOORD2;
out vec4 vs_TEXCOORD3;
out vec4 vs_TEXCOORD4;
out vec4 vs_TEXCOORD5;
out vec2 vs_TEXCOORD7;
out float vs_TEXCOORD6;
out vec4 vs_COLOR0;
out vec3 vs_TEXCOORD8;
vec3 u_xlat0;
vec4 u_xlat1;
float u_xlat16_2;
vec3 u_xlat3;
vec3 u_xlat4;
vec3 u_xlat5;
vec2 u_xlat13;
float u_xlat18;
void main(){
  (u_xlat0.xyz = (in_POSITION0.yyy * hlslcc_mtx4x4unity_ObjectToWorld[1].xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[0].xyz * in_POSITION0.xxx) + u_xlat0.xyz));
  (u_xlat0.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[2].xyz * in_POSITION0.zzz) + u_xlat0.xyz));
  (u_xlat0.xyz = (u_xlat0.xyz + hlslcc_mtx4x4unity_ObjectToWorld[3].xyz));
  (u_xlat1 = (u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx) + u_xlat1));
  (u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz) + u_xlat1));
  (gl_Position = (u_xlat1 + hlslcc_mtx4x4unity_MatrixVP[3]));
  (u_xlat1.xy = ((in_TEXCOORD0.xy * _Main_Tex_ST.xy) + _Main_Tex_ST.zw));
  (u_xlat13.xy = ((_Time.yy * vec2(_Main_UV.x, _Main_UV.y)) + u_xlat1.xy));
  (u_xlat1.xy = (u_xlat1.xy + in_TEXCOORD1.xy));
  (u_xlat1.xy = ((-u_xlat13.xy) + u_xlat1.xy));
  (u_xlat1.xy = ((vec2(vec2(_Particle_SpeedUV, _Particle_SpeedUV)) * u_xlat1.xy) + u_xlat13.xy));
  (u_xlat16_2 = (_Main_tex_Rotator * 0.017453294));
  (u_xlat3.x = sin(u_xlat16_2));
  (u_xlat4.x = cos(u_xlat16_2));
  (u_xlat5.x = (-u_xlat3.x));
  (u_xlat5.y = u_xlat4.x);
  (u_xlat5.z = u_xlat3.x);
  (vs_TEXCOORD4.x = dot(u_xlat1.xy, u_xlat5.yz));
  (vs_TEXCOORD4.y = dot(u_xlat1.xy, u_xlat5.xy));
  (u_xlat1.xy = ((in_TEXCOORD0.xy * _Mask_ST.xy) + _Mask_ST.zw));
  (u_xlat1.xy = ((_Time.yy * _Mask_UV.xy) + u_xlat1.xy));
  (u_xlat16_2 = (_Mask_Tex_Rotator * 0.017453294));
  (u_xlat3.x = sin(u_xlat16_2));
  (u_xlat4.x = cos(u_xlat16_2));
  (u_xlat5.x = (-u_xlat3.x));
  (u_xlat5.y = u_xlat4.x);
  (u_xlat5.z = u_xlat3.x);
  (vs_TEXCOORD5.x = dot(u_xlat1.xy, u_xlat5.yz));
  (vs_TEXCOORD5.y = dot(u_xlat1.xy, u_xlat5.xy));
  (u_xlat1.xy = ((in_TEXCOORD0.xy * _Tex_2_ST.xy) + _Tex_2_ST.zw));
  (vs_TEXCOORD5.zw = ((_Time.yy * _Tex_2_UV.xy) + u_xlat1.xy));
  if ((_ParallaxOn != 0))
  {
    (u_xlat1.xyz = (in_TANGENT0.yyy * hlslcc_mtx4x4unity_ObjectToWorld[1].xyz));
    (u_xlat1.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[0].xyz * in_TANGENT0.xxx) + u_xlat1.xyz));
    (u_xlat1.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[2].xyz * in_TANGENT0.zzz) + u_xlat1.xyz));
    (u_xlat18 = dot(u_xlat1.xyz, u_xlat1.xyz));
    (u_xlat18 = max(u_xlat18, 0.0));
    (u_xlat18 = inversesqrt(u_xlat18));
    (u_xlat1.xyz = (vec3(u_xlat18) * u_xlat1.xyz));
    (u_xlat3.xyz = ((-u_xlat0.xyz) + _WorldSpaceCameraPos.xyz));
    (u_xlat18 = dot(u_xlat3.xyz, u_xlat3.xyz));
    (u_xlat18 = inversesqrt(u_xlat18));
    (u_xlat3.xyz = (vec3(u_xlat18) * u_xlat3.xyz));
    (u_xlat4.x = (u_xlat1.x * u_xlat3.x));
    (u_xlat4.y = 0.0);
    (u_xlat4.z = 0.0);
    (u_xlat5.x = (u_xlat1.y * u_xlat3.y));
    (u_xlat5.y = 0.0);
    (u_xlat5.z = 0.0);
    (u_xlat1.xyw = (u_xlat4.xyz + u_xlat5.xyz));
    (u_xlat3.x = (u_xlat1.z * u_xlat3.z));
    (u_xlat3.y = 0.0);
    (u_xlat3.z = 0.0);
    (vs_TEXCOORD8.xyz = (u_xlat1.xyw + u_xlat3.xyz));
  }
  else
  {
    (vs_TEXCOORD8.xyz = vec3(0.0, 0.0, 0.0));
  }
  (vs_TEXCOORD1.xy = in_TEXCOORD0.xy);
  (vs_TEXCOORD1.zw = vec2(0.0, 0.0));
  (vs_TEXCOORD2 = in_TEXCOORD1);
  (vs_TEXCOORD3 = vec4(0.0, 0.0, 0.0, 0.0));
  (vs_TEXCOORD4.zw = vec2(0.0, 0.0));
  (vs_TEXCOORD0.xyz = u_xlat0.xyz);
  (vs_TEXCOORD7.xy = in_TEXCOORD0.zw);
  (vs_TEXCOORD6 = in_TEXCOORD2.x);
  (vs_COLOR0 = in_COLOR0);
  return ;
}
