#version 450
uniform vec3 _WorldSpaceCameraPos;
uniform vec2 _GlobalMipBias;
layout(std140, binding = 0) uniform UnityPerMaterial{
  vec4 _MainTex_ST;
  vec4 _MainColor;
  vec4 _Main02Color;
  vec4 _MainTex02_ST;
  vec4 _mainUVMove;
  vec4 _main02UVMove;
  vec4 _NoiseColor;
  vec4 _NoiseTex_ST;
  vec4 _noiseUVMove;
  vec4 _WPODir;
  vec4 _DissolveTex_ST;
  vec4 _EdgeColor;
  vec4 _depc;
  vec4 _dissolveUVMove;
  vec4 _MaskTex_ST;
  vec4 _maskUVMove;
  vec4 _FresnelColor;
  vec4 _FalseViewDir;
  vec4 _HeightFadeParam;
  int _MaskType;
  float _HeightFade;
  float _MWarpMode;
  float _M02WarpMode;
  float _UVChannel;
  float _BlackOff;
  float _BlackOff_1;
  float _NWarpMode;
  float _DistortIntensity;
  float _DissolveDirToggle;
  float _DissolveDir;
  float _InvertDissolveDir;
  float _particleUV;
  float _dissolveMode;
  float _DWarpMode;
  float _DistortMod;
  float _WPOMod;
  float _MaskTexUV;
  float _MKWarpMode;
  float _CameraOffset;
  float _BlendMode;
  float _InvertMode;
  float _FalseFresnel;
  float _FresnelPower;
  float _Desaturate;
  float _MainColorIntensity;
  float _Main02ColorIntensity;
  float _NoiseColorIntensity;
  float _EdgeColorIntensity;
  float _FresnelColorIntensity;
  float _MainAngle;
  float _Main02Angle;
  float _NoiseAngle;
  float _DissolveAngle;
  float _MaskAngle;
  float _RimIntencity;
  float _ScreenSpaceUV_ON;
  float _MNBlendMode;
};
layout(location = 0) uniform sampler2D _MainTex;
in vec4 vs_TEXCOORD0;
in vec4 vs_TEXCOORD3;
in vec3 vs_TEXCOORD4;
in vec3 vs_TEXCOORD5;
layout(location = 0) out vec4 SV_Target0;
vec4 u_xlat16_0;
vec3 u_xlat1;
vec4 u_xlat16_1;
vec3 u_xlat2;
vec4 u_xlat16_2;
vec4 u_xlat16_3;
vec4 u_xlat16_4;
float u_xlat6;
float u_xlat16_15;
float u_xlat16;
void main(){
  (u_xlat16_0.x = dot(_FalseViewDir.xyz, _FalseViewDir.xyz));
  (u_xlat16_0.x = inversesqrt(u_xlat16_0.x));
  (u_xlat1.xyz = ((-vs_TEXCOORD5.xyz) + _WorldSpaceCameraPos.xyz));
  (u_xlat16 = dot(u_xlat1.xyz, u_xlat1.xyz));
  (u_xlat16 = inversesqrt(u_xlat16));
  (u_xlat1.xyz = (vec3(u_xlat16) * u_xlat1.xyz));
  (u_xlat2.xyz = ((_FalseViewDir.xyz * u_xlat16_0.xxx) + (-u_xlat1.xyz)));
  (u_xlat1.xyz = ((vec3(vec3(_FalseFresnel, _FalseFresnel, _FalseFresnel)) * u_xlat2.xyz) + u_xlat1.xyz));
  (u_xlat1.x = dot(vs_TEXCOORD4.xyz, u_xlat1.xyz));
  (u_xlat16_0.x = ((-u_xlat1.x) + 1.0));
  (u_xlat16_0.x = clamp(u_xlat16_0.x, 0.0, 1.0));
  (u_xlat1.x = log2(u_xlat16_0.x));
  (u_xlat1.x = (u_xlat1.x * _FresnelPower));
  (u_xlat1.x = exp2(u_xlat1.x));
  (u_xlat16_0.x = ((u_xlat1.x * -2.0) + 1.0));
  (u_xlat16_0.x = ((_InvertMode * u_xlat16_0.x) + u_xlat1.x));
  (u_xlat16_0 = (u_xlat16_0.xxxx * _FresnelColor));
  (u_xlat1.xy = vs_TEXCOORD0.xy);
  (u_xlat1.xy = clamp(u_xlat1.xy, 0.0, 1.0));
  (u_xlat1.xy = (u_xlat1.xy + (-vs_TEXCOORD0.xy)));
  (u_xlat1.xy = ((vec2(vec2(_MWarpMode, _MWarpMode)) * u_xlat1.xy) + vs_TEXCOORD0.xy));
  (u_xlat16_1 = texture(_MainTex, u_xlat1.xy, _GlobalMipBias.x));
  (u_xlat16_2 = (u_xlat16_1 * _MainColor));
  (u_xlat16_2 = (u_xlat16_2 * vec4(_MainColorIntensity)));
  (u_xlat16_3.x = ((-_MNBlendMode) + 1.0));
  (u_xlat16_4 = (u_xlat16_3.xxxx * _Main02Color));
  (u_xlat16_3 = (u_xlat16_1 * u_xlat16_3.xxxx));
  (u_xlat16_3 = (u_xlat16_3 * _MainColor));
  (u_xlat16_2 = ((u_xlat16_4 * vec4(vec4(_Main02ColorIntensity, _Main02ColorIntensity, _Main02ColorIntensity, _Main02ColorIntensity))) + u_xlat16_2));
  (u_xlat16_2 = (((-u_xlat16_3) * vec4(_MainColorIntensity)) + u_xlat16_2));
  (u_xlat16_3 = (u_xlat16_3 * vec4(_MainColorIntensity)));
  (u_xlat16_2 = ((vec4(_MNBlendMode) * u_xlat16_2) + u_xlat16_3));
  (u_xlat16_3 = ((u_xlat16_0 * vec4(_FresnelColorIntensity)) + u_xlat16_2));
  (u_xlat16_0 = (u_xlat16_0 * vec4(_FresnelColorIntensity)));
  (u_xlat16_4 = (u_xlat16_0 * u_xlat16_2));
  (u_xlat16_2 = (((-u_xlat16_2) * u_xlat16_0) + u_xlat16_3));
  (u_xlat16_0 = ((u_xlat16_3 * u_xlat16_0.wwww) + (-u_xlat16_4)));
  (u_xlat16_0 = ((vec4(vec4(_BlendMode, _BlendMode, _BlendMode, _BlendMode)) * u_xlat16_0) + u_xlat16_4));
  (u_xlat16_2 = ((vec4(vec4(_BlendMode, _BlendMode, _BlendMode, _BlendMode)) * u_xlat16_2) + u_xlat16_4));
  (u_xlat16_0 = (u_xlat16_0 + (-u_xlat16_2)));
  (u_xlat16_0 = ((vec4(_InvertMode) * u_xlat16_0) + u_xlat16_2));
  (u_xlat16_3.x = dot(u_xlat16_0.xyz, vec3(0.22, 0.70700002, 0.071000002)));
  (u_xlat16_3.xyz = ((-u_xlat16_0.xyz) + u_xlat16_3.xxx));
  (u_xlat16_0.xyz = ((vec3(vec3(_Desaturate, _Desaturate, _Desaturate)) * u_xlat16_3.xyz) + u_xlat16_0.xyz));
  (u_xlat16_0.xyz = (u_xlat16_0.xyz * vs_TEXCOORD3.xyz));
  (u_xlat16_3.x = ((u_xlat16_0.w * u_xlat16_1.x) + (-u_xlat16_0.w)));
  (u_xlat16_15 = ((_BlackOff * u_xlat16_3.x) + u_xlat16_0.w));
  (u_xlat16_15 = clamp(u_xlat16_15, 0.0, 1.0));
  (u_xlat1.x = ((-_HeightFadeParam.x) + _HeightFadeParam.y));
  (u_xlat1.x = (1.0 / float(u_xlat1.x)));
  (u_xlat6 = (vs_TEXCOORD5.y + (-_HeightFadeParam.x)));
  (u_xlat1.x = (u_xlat1.x * u_xlat6));
  (u_xlat1.x = clamp(u_xlat1.x, 0.0, 1.0));
  (u_xlat1.x = (u_xlat1.x + -1.0));
  (u_xlat1.x = ((_HeightFade * u_xlat1.x) + 1.0));
  (u_xlat1.x = (u_xlat16_15 * u_xlat1.x));
  (u_xlat16_15 = (u_xlat1.x * vs_TEXCOORD3.w));
  (SV_Target0.xyz = (vec3(u_xlat16_15) * u_xlat16_0.xyz));
  (SV_Target0.w = u_xlat16_15);
  return ;
}
