#version 450
uniform vec4 _MainLightColor;
uniform float _Timeline;
uniform vec4 _TopColor;
uniform vec4 _BottomColor;
uniform vec4 _TopColor11;
uniform vec4 _BottomColor11;
layout(std140, binding = 0) uniform UnityPerDraw{
  vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
  vec4 hlslcc_mtx4x4unity_WorldToObject[4];
  vec4 unity_LODFade;
  vec4 unity_WorldTransformParams;
  vec4 unity_RenderingLayer;
  vec4 unity_LightData;
  vec4 unity_LightIndices[2];
  vec4 unity_ProbesOcclusion;
  vec4 unity_SpecCube0_HDR;
  vec4 unity_SpecCube1_HDR;
  vec4 unity_SpecCube0_BoxMax;
  vec4 unity_SpecCube0_BoxMin;
  vec4 unity_SpecCube0_ProbePosition;
  vec4 unity_SpecCube1_BoxMax;
  vec4 unity_SpecCube1_BoxMin;
  vec4 unity_SpecCube1_ProbePosition;
  vec4 unity_LightmapST;
  vec4 unity_DynamicLightmapST;
  vec4 unity_SHAr;
  vec4 unity_SHAg;
  vec4 unity_SHAb;
  vec4 unity_SHBr;
  vec4 unity_SHBg;
  vec4 unity_SHBb;
  vec4 unity_SHC;
  vec4 hlslcc_mtx4x4unity_MatrixPreviousM[4];
  vec4 hlslcc_mtx4x4unity_MatrixPreviousMI[4];
  vec4 unity_MotionVectorsParams;
};
layout(location = 0) uniform sampler2D _PlaneBlurShadowMap;
in vec2 vs_TEXCOORD1;
in vec4 vs_TEXCOORD4;
layout(location = 0) out vec4 SV_Target0;
vec3 u_xlat0;
vec3 u_xlat1;
vec3 u_xlat16_2;
float u_xlat16_9;
void main(){
  (u_xlat0.xyz = (_TopColor.xyz + (-_BottomColor.xyz)));
  (u_xlat0.xyz = ((vs_TEXCOORD1.yyy * u_xlat0.xyz) + _BottomColor.xyz));
  (u_xlat1.xyz = (_TopColor11.xyz + (-_BottomColor11.xyz)));
  (u_xlat1.xyz = ((vs_TEXCOORD1.yyy * u_xlat1.xyz) + _BottomColor11.xyz));
  (u_xlat16_2.xyz = (u_xlat0.xyz + (-u_xlat1.xyz)));
  (u_xlat16_2.xyz = ((vec3(vec3(_Timeline, _Timeline, _Timeline)) * u_xlat16_2.xyz) + u_xlat1.xyz));
  (u_xlat0.xyz = (_MainLightColor.xyz * unity_LightData.zzz));
  (u_xlat0.xyz = (u_xlat0.xyz * u_xlat16_2.xyz));
  (u_xlat16_2.xyz = (u_xlat0.xyz * vec3(0.5, 0.5, 0.5)));
  (u_xlat1.xy = (vs_TEXCOORD4.xy / vs_TEXCOORD4.ww));
  (u_xlat16_9 = texture(_PlaneBlurShadowMap, u_xlat1.xy).x);
  (u_xlat16_2.xyz = (u_xlat16_2.xyz * vec3(u_xlat16_9)));
  (SV_Target0.xyz = ((u_xlat0.xyz * vec3(0.5, 0.5, 0.5)) + u_xlat16_2.xyz));
  (SV_Target0.w = 1.0);
  return ;
}
